#!/bin/bash

perform_check() {
    local tool_name="$1"
    local cmd="$2"
    local suggestion="$3"

    OUTPUT=$($cmd 2>&1)
    if [ $? -eq 0 ]; then
        echo "$tool_name ✅"
    else
        echo -e "$tool_name ❌ \nsuggestion: run - $suggestion\n"
        FAILURE=1
    fi
    echo "$OUTPUT"
}

# Formatter
ruff-formatter-check() {
    perform_check "ruff" "ruff format --check ." "ruff format ."
}

# Linter
ruff-linter-check() {
    perform_check "ruff" " ruff check ." " ruff check ."
}

# Static type checker
mypy-check() {
    perform_check "mypy" "mypy pyatlan tests" "mypy pyatlan tests"
}

ruff-formatter-check
ruff-linter-check
mypy-check
exit $FAILURE
