#!/bin/bash

perform_check() {
    local tool_name="$1"
    local cmd="$2"
    local suggestion="$3"

    OUTPUT=$($cmd 2>&1)
    if [ $? -eq 0 ]; then
        echo "$tool_name ✅"
    else
        echo -e "$tool_name ❌ \nsuggestion: run - $suggestion\n"
        FAILURE=1
    fi
    echo "$OUTPUT"
}

# Formatter
black-check() {
    perform_check "black" "black --check --quiet ." "black ."
}

# Linter
flake8-check() {
    perform_check "flake8" "flake8" "flake8 ."
}

# Static type checker
mypy-check() {
    perform_check "mypy" "mypy pyatlan tests" "mypy pyatlan tests"
}

black-check
flake8-check
mypy-check
exit $FAILURE
