# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
Resource module exports.

This module provides convenient imports for all Resource types and their Related variants.
"""

from .file import File
from .link import Link
from .readme import Readme
from .readme_template import ReadmeTemplate
from .resource import Resource
from .resource_related import (
    Related__internal,
    RelatedBadge,
    RelatedFile,
    RelatedLink,
    RelatedReadme,
    RelatedReadmeTemplate,
    RelatedResource,
)

__all__ = [
    "File",
    "Link",
    "Readme",
    "ReadmeTemplate",
    "RelatedBadge",
    "RelatedFile",
    "RelatedLink",
    "RelatedReadme",
    "RelatedReadmeTemplate",
    "RelatedResource",
    "Related__internal",
    "Resource",
]
