# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
Airflow asset model with flattened inheritance.

This module provides:
- Airflow: Flat asset class (easy to use)
- AirflowAttributes: Nested attributes struct (extends AssetAttributes)
- AirflowNested: Nested API format struct
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.model.conversion_utils import (
    categorize_relationships,
    merge_relationships,
)
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset

from .asset import Asset, AssetAttributes, AssetNested, AssetRelationshipAttributes

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class Airflow(Asset):
    """
    Base class for Airflow assets.
    """

    # Override type_name with Airflow-specific default
    type_name: Union[str, UnsetType] = "Airflow"

    airflow_tags: Union[list[str], None, UnsetType] = UNSET
    """Tags assigned to the asset in Airflow."""

    airflow_run_version: Union[str, None, UnsetType] = UNSET
    """Version of the run in Airflow."""

    airflow_run_open_lineage_version: Union[str, None, UnsetType] = UNSET
    """Version of the run in OpenLineage."""

    airflow_run_name: Union[str, None, UnsetType] = UNSET
    """Name of the run."""

    airflow_run_type: Union[str, None, UnsetType] = UNSET
    """Type of the run."""

    airflow_run_start_time: Union[int, None, UnsetType] = UNSET
    """Start time of the run."""

    airflow_run_end_time: Union[int, None, UnsetType] = UNSET
    """End time of the run."""

    airflow_run_open_lineage_state: Union[str, None, UnsetType] = UNSET
    """State of the run in OpenLineage."""

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return _airflow_to_nested_bytes(self, serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    @staticmethod
    def from_json(
        json_data: Union[str, bytes], serde: Serde | None = None
    ) -> "Airflow":
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            Airflow instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _airflow_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class AirflowAttributes(AssetAttributes):
    """Airflow-specific attributes for nested API format."""

    airflow_tags: Union[list[str], None, UnsetType] = UNSET
    """Tags assigned to the asset in Airflow."""

    airflow_run_version: Union[str, None, UnsetType] = UNSET
    """Version of the run in Airflow."""

    airflow_run_open_lineage_version: Union[str, None, UnsetType] = UNSET
    """Version of the run in OpenLineage."""

    airflow_run_name: Union[str, None, UnsetType] = UNSET
    """Name of the run."""

    airflow_run_type: Union[str, None, UnsetType] = UNSET
    """Type of the run."""

    airflow_run_start_time: Union[int, None, UnsetType] = UNSET
    """Start time of the run."""

    airflow_run_end_time: Union[int, None, UnsetType] = UNSET
    """End time of the run."""

    airflow_run_open_lineage_state: Union[str, None, UnsetType] = UNSET
    """State of the run in OpenLineage."""


class AirflowRelationshipAttributes(AssetRelationshipAttributes):
    """Airflow-specific relationship attributes for nested API format."""

    pass


class AirflowNested(AssetNested):
    """Airflow in nested API format for high-performance serialization."""

    attributes: Union[AirflowAttributes, UnsetType] = UNSET
    relationship_attributes: Union[AirflowRelationshipAttributes, UnsetType] = UNSET
    append_relationship_attributes: Union[AirflowRelationshipAttributes, UnsetType] = (
        UNSET
    )
    remove_relationship_attributes: Union[AirflowRelationshipAttributes, UnsetType] = (
        UNSET
    )


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _airflow_to_nested(airflow: Airflow) -> AirflowNested:
    """Convert flat Airflow to nested format."""
    attrs = AirflowAttributes(
        airflow_tags=airflow.airflow_tags,
        airflow_run_version=airflow.airflow_run_version,
        airflow_run_open_lineage_version=airflow.airflow_run_open_lineage_version,
        airflow_run_name=airflow.airflow_run_name,
        airflow_run_type=airflow.airflow_run_type,
        airflow_run_start_time=airflow.airflow_run_start_time,
        airflow_run_end_time=airflow.airflow_run_end_time,
        airflow_run_open_lineage_state=airflow.airflow_run_open_lineage_state,
    )
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    rel_fields: list[str] = []
    replace_rels, append_rels, remove_rels = categorize_relationships(
        airflow, rel_fields, AirflowRelationshipAttributes
    )
    return AirflowNested(
        guid=airflow.guid,
        type_name=airflow.type_name,
        status=airflow.status,
        version=airflow.version,
        create_time=airflow.create_time,
        update_time=airflow.update_time,
        created_by=airflow.created_by,
        updated_by=airflow.updated_by,
        classifications=airflow.classifications,
        classification_names=airflow.classification_names,
        meanings=airflow.meanings,
        labels=airflow.labels,
        business_attributes=airflow.business_attributes,
        custom_attributes=airflow.custom_attributes,
        pending_tasks=airflow.pending_tasks,
        proxy=airflow.proxy,
        is_incomplete=airflow.is_incomplete,
        provenance_type=airflow.provenance_type,
        home_id=airflow.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _airflow_from_nested(nested: AirflowNested) -> Airflow:
    """Convert nested format to flat Airflow."""
    attrs = nested.attributes if nested.attributes is not UNSET else AirflowAttributes()
    # Merge relationships from all three buckets
    rel_fields: list[str] = []
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        rel_fields,
        AirflowRelationshipAttributes,
    )
    return Airflow(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        airflow_tags=attrs.airflow_tags,
        airflow_run_version=attrs.airflow_run_version,
        airflow_run_open_lineage_version=attrs.airflow_run_open_lineage_version,
        airflow_run_name=attrs.airflow_run_name,
        airflow_run_type=attrs.airflow_run_type,
        airflow_run_start_time=attrs.airflow_run_start_time,
        airflow_run_end_time=attrs.airflow_run_end_time,
        airflow_run_open_lineage_state=attrs.airflow_run_open_lineage_state,
        # Merged relationship attributes
        **merged_rels,
    )


def _airflow_to_nested_bytes(airflow: Airflow, serde: Serde) -> bytes:
    """Convert flat Airflow to nested JSON bytes."""
    return serde.encode(_airflow_to_nested(airflow))


def _airflow_from_nested_bytes(data: bytes, serde: Serde) -> Airflow:
    """Convert nested JSON bytes to flat Airflow."""
    nested = serde.decode(data, AirflowNested)
    return _airflow_from_nested(nested)
