# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# ruff: noqa: ARG002
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
CassandraIndex asset model with flattened inheritance.

This module provides:
- CassandraIndex: Flat asset class (easy to use)
- CassandraIndexAttributes: Nested attributes struct (extends AssetAttributes)
- CassandraIndexNested: Nested API format struct
"""

from __future__ import annotations

import re
from typing import Any, ClassVar, Dict, List, Union

import msgspec
from msgspec import UNSET, UnsetType

from pyatlan_v9.model.conversion_utils import (
    categorize_relationships,
    merge_relationships,
)
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset

from .airflow_related import RelatedAirflowTask
from .anomalo_related import RelatedAnomaloCheck
from .app_related import RelatedApplication, RelatedApplicationField
from .asset import (
    _ASSET_REL_FIELDS,
    Asset,
    AssetAttributes,
    AssetNested,
    AssetRelationshipAttributes,
    _extract_asset_attrs,
    _populate_asset_attrs,
)
from .cassandra_related import RelatedCassandraTable
from .context_related import RelatedContextRepository
from .data_contract_related import RelatedDataContract
from .data_mesh_related import RelatedDataProduct
from .data_quality_related import RelatedDataQualityRule, RelatedMetric
from .gcp_dataplex_related import RelatedGCPDataplexAspectType
from .gtc_related import RelatedAtlasGlossaryTerm
from .model_related import RelatedModelAttribute, RelatedModelEntity
from .monte_carlo_related import RelatedMCIncident, RelatedMCMonitor
from .partial_related import RelatedPartialField, RelatedPartialObject
from .process_related import RelatedProcess
from .referenceable_related import RelatedReferenceable
from .resource_related import RelatedFile, RelatedLink, RelatedReadme
from .schema_registry_related import RelatedSchemaRegistrySubject
from .soda_related import RelatedSodaCheck
from .spark_related import RelatedSparkJob

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class CassandraIndex(Asset):
    """
    Instances of a CassandraIndex in Atlan.
    """

    CASSANDRA_INDEX_KIND: ClassVar[Any] = None
    CASSANDRA_INDEX_OPTIONS: ClassVar[Any] = None
    CASSANDRA_INDEX_QUERY: ClassVar[Any] = None
    CASSANDRA_KEYSPACE_NAME: ClassVar[Any] = None
    CASSANDRA_TABLE_NAME: ClassVar[Any] = None
    CASSANDRA_VIEW_NAME: ClassVar[Any] = None
    CASSANDRA_TABLE_QUALIFIED_NAME: ClassVar[Any] = None
    CASSANDRA_VIEW_QUALIFIED_NAME: ClassVar[Any] = None
    NO_SQL_SCHEMA_DEFINITION: ClassVar[Any] = None
    CATALOG_DATASET_GUID: ClassVar[Any] = None
    INPUT_TO_AIRFLOW_TASKS: ClassVar[Any] = None
    OUTPUT_FROM_AIRFLOW_TASKS: ClassVar[Any] = None
    ANOMALO_CHECKS: ClassVar[Any] = None
    APPLICATION: ClassVar[Any] = None
    APPLICATION_FIELD: ClassVar[Any] = None
    CASSANDRA_TABLE: ClassVar[Any] = None
    CONTEXT_REPOSITORIES: ClassVar[Any] = None
    DATA_CONTRACT_LATEST: ClassVar[Any] = None
    DATA_CONTRACT_LATEST_CERTIFIED: ClassVar[Any] = None
    OUTPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    INPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ENTITIES: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ATTRIBUTES: ClassVar[Any] = None
    METRICS: ClassVar[Any] = None
    DQ_BASE_DATASET_RULES: ClassVar[Any] = None
    DQ_REFERENCE_DATASET_RULES: ClassVar[Any] = None
    GCP_DATAPLEX_ASPECT_TYPE_METADATA_ENTITIES: ClassVar[Any] = None
    MEANINGS: ClassVar[Any] = None
    MC_MONITORS: ClassVar[Any] = None
    MC_INCIDENTS: ClassVar[Any] = None
    PARTIAL_CHILD_FIELDS: ClassVar[Any] = None
    PARTIAL_CHILD_OBJECTS: ClassVar[Any] = None
    INPUT_TO_PROCESSES: ClassVar[Any] = None
    OUTPUT_FROM_PROCESSES: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_TO: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_FROM: ClassVar[Any] = None
    FILES: ClassVar[Any] = None
    LINKS: ClassVar[Any] = None
    README: ClassVar[Any] = None
    SCHEMA_REGISTRY_SUBJECTS: ClassVar[Any] = None
    SODA_CHECKS: ClassVar[Any] = None
    INPUT_TO_SPARK_JOBS: ClassVar[Any] = None
    OUTPUT_FROM_SPARK_JOBS: ClassVar[Any] = None

    type_name: Union[str, UnsetType] = "CassandraIndex"

    cassandra_index_kind: Union[str, None, UnsetType] = UNSET
    """Kind of index (e.g. COMPOSITES)."""

    cassandra_index_options: Union[Dict[str, str], None, UnsetType] = UNSET
    """Options for the index."""

    cassandra_index_query: Union[str, None, UnsetType] = UNSET
    """Query used to create the index."""

    cassandra_keyspace_name: Union[str, None, UnsetType] = UNSET
    """Name of the keyspace for the Cassandra asset."""

    cassandra_table_name: Union[str, None, UnsetType] = UNSET
    """Name of the table for the Cassandra asset."""

    cassandra_view_name: Union[str, None, UnsetType] = UNSET
    """Name of view for Cassandra asset"""

    cassandra_table_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of table for Cassandra asset"""

    cassandra_view_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of view for Cassandra asset"""

    no_sql_schema_definition: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="noSQLSchemaDefinition"
    )
    """Represents attributes for describing the key schema for the table and indexes."""

    catalog_dataset_guid: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the dataset this asset belongs to."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    cassandra_table: Union[RelatedCassandraTable, None, UnsetType] = UNSET
    """Table containing the index."""

    context_repositories: Union[List[RelatedContextRepository], None, UnsetType] = UNSET
    """Context repositories that use this asset as input."""

    data_contract_latest: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest version of the data contract (in any status) for this asset."""

    data_contract_latest_certified: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest certified version of the data contract for this asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[
        List[RelatedModelAttribute], None, UnsetType
    ] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    gcp_dataplex_aspect_type_metadata_entities: Union[
        List[RelatedGCPDataplexAspectType], None, UnsetType
    ] = UNSET
    """Dataplex entries (assets) that have aspects of this Aspect Type attached."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """Schema registry subjects associated with this asset."""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        self.type_name = "CassandraIndex"

    # =========================================================================
    # SDK Methods
    # =========================================================================

    _QUALIFIED_NAME_PATTERN: ClassVar[re.Pattern] = re.compile(
        r"^.+/[^/]+/[^/]+/[^/]+$"
    )

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return self.to_nested_bytes(serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    def to_nested_bytes(self, serde: Serde | None = None) -> bytes:
        """Serialize to Atlas nested-format JSON bytes (pure msgspec, no dict intermediate)."""
        if serde is None:
            serde = get_serde()
        return _cassandra_index_to_nested_bytes(self, serde)

    @staticmethod
    def from_json(json_data: str | bytes, serde: Serde | None = None) -> CassandraIndex:
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            CassandraIndex instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _cassandra_index_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class CassandraIndexAttributes(AssetAttributes):
    """CassandraIndex-specific attributes for nested API format."""

    cassandra_index_kind: Union[str, None, UnsetType] = UNSET
    """Kind of index (e.g. COMPOSITES)."""

    cassandra_index_options: Union[Dict[str, str], None, UnsetType] = UNSET
    """Options for the index."""

    cassandra_index_query: Union[str, None, UnsetType] = UNSET
    """Query used to create the index."""

    cassandra_keyspace_name: Union[str, None, UnsetType] = UNSET
    """Name of the keyspace for the Cassandra asset."""

    cassandra_table_name: Union[str, None, UnsetType] = UNSET
    """Name of the table for the Cassandra asset."""

    cassandra_view_name: Union[str, None, UnsetType] = UNSET
    """Name of view for Cassandra asset"""

    cassandra_table_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of table for Cassandra asset"""

    cassandra_view_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of view for Cassandra asset"""

    no_sql_schema_definition: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="noSQLSchemaDefinition"
    )
    """Represents attributes for describing the key schema for the table and indexes."""

    catalog_dataset_guid: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the dataset this asset belongs to."""


class CassandraIndexRelationshipAttributes(AssetRelationshipAttributes):
    """CassandraIndex-specific relationship attributes for nested API format."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    cassandra_table: Union[RelatedCassandraTable, None, UnsetType] = UNSET
    """Table containing the index."""

    context_repositories: Union[List[RelatedContextRepository], None, UnsetType] = UNSET
    """Context repositories that use this asset as input."""

    data_contract_latest: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest version of the data contract (in any status) for this asset."""

    data_contract_latest_certified: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest certified version of the data contract for this asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[
        List[RelatedModelAttribute], None, UnsetType
    ] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    gcp_dataplex_aspect_type_metadata_entities: Union[
        List[RelatedGCPDataplexAspectType], None, UnsetType
    ] = UNSET
    """Dataplex entries (assets) that have aspects of this Aspect Type attached."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """Schema registry subjects associated with this asset."""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""


class CassandraIndexNested(AssetNested):
    """CassandraIndex in nested API format for high-performance serialization."""

    attributes: Union[CassandraIndexAttributes, UnsetType] = UNSET
    relationship_attributes: Union[CassandraIndexRelationshipAttributes, UnsetType] = (
        UNSET
    )
    append_relationship_attributes: Union[
        CassandraIndexRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        CassandraIndexRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION HELPERS & CONSTANTS
# =============================================================================

_CASSANDRA_INDEX_REL_FIELDS: List[str] = [
    *_ASSET_REL_FIELDS,
    "input_to_airflow_tasks",
    "output_from_airflow_tasks",
    "anomalo_checks",
    "application",
    "application_field",
    "cassandra_table",
    "context_repositories",
    "data_contract_latest",
    "data_contract_latest_certified",
    "output_port_data_products",
    "input_port_data_products",
    "model_implemented_entities",
    "model_implemented_attributes",
    "metrics",
    "dq_base_dataset_rules",
    "dq_reference_dataset_rules",
    "gcp_dataplex_aspect_type_metadata_entities",
    "meanings",
    "mc_monitors",
    "mc_incidents",
    "partial_child_fields",
    "partial_child_objects",
    "input_to_processes",
    "output_from_processes",
    "user_def_relationship_to",
    "user_def_relationship_from",
    "files",
    "links",
    "readme",
    "schema_registry_subjects",
    "soda_checks",
    "input_to_spark_jobs",
    "output_from_spark_jobs",
]


def _populate_cassandra_index_attrs(
    attrs: CassandraIndexAttributes, obj: CassandraIndex
) -> None:
    """Populate CassandraIndex-specific attributes on the attrs struct."""
    _populate_asset_attrs(attrs, obj)
    attrs.cassandra_index_kind = obj.cassandra_index_kind
    attrs.cassandra_index_options = obj.cassandra_index_options
    attrs.cassandra_index_query = obj.cassandra_index_query
    attrs.cassandra_keyspace_name = obj.cassandra_keyspace_name
    attrs.cassandra_table_name = obj.cassandra_table_name
    attrs.cassandra_view_name = obj.cassandra_view_name
    attrs.cassandra_table_qualified_name = obj.cassandra_table_qualified_name
    attrs.cassandra_view_qualified_name = obj.cassandra_view_qualified_name
    attrs.no_sql_schema_definition = obj.no_sql_schema_definition
    attrs.catalog_dataset_guid = obj.catalog_dataset_guid


def _extract_cassandra_index_attrs(attrs: CassandraIndexAttributes) -> dict:
    """Extract all CassandraIndex attributes from the attrs struct into a flat dict."""
    result = _extract_asset_attrs(attrs)
    result["cassandra_index_kind"] = attrs.cassandra_index_kind
    result["cassandra_index_options"] = attrs.cassandra_index_options
    result["cassandra_index_query"] = attrs.cassandra_index_query
    result["cassandra_keyspace_name"] = attrs.cassandra_keyspace_name
    result["cassandra_table_name"] = attrs.cassandra_table_name
    result["cassandra_view_name"] = attrs.cassandra_view_name
    result["cassandra_table_qualified_name"] = attrs.cassandra_table_qualified_name
    result["cassandra_view_qualified_name"] = attrs.cassandra_view_qualified_name
    result["no_sql_schema_definition"] = attrs.no_sql_schema_definition
    result["catalog_dataset_guid"] = attrs.catalog_dataset_guid
    return result


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _cassandra_index_to_nested(cassandra_index: CassandraIndex) -> CassandraIndexNested:
    """Convert flat CassandraIndex to nested format."""
    attrs = CassandraIndexAttributes()
    _populate_cassandra_index_attrs(attrs, cassandra_index)
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    replace_rels, append_rels, remove_rels = categorize_relationships(
        cassandra_index,
        _CASSANDRA_INDEX_REL_FIELDS,
        CassandraIndexRelationshipAttributes,
    )
    return CassandraIndexNested(
        guid=cassandra_index.guid,
        type_name=cassandra_index.type_name,
        status=cassandra_index.status,
        version=cassandra_index.version,
        create_time=cassandra_index.create_time,
        update_time=cassandra_index.update_time,
        created_by=cassandra_index.created_by,
        updated_by=cassandra_index.updated_by,
        classifications=cassandra_index.classifications,
        classification_names=cassandra_index.classification_names,
        meanings=cassandra_index.meanings,
        labels=cassandra_index.labels,
        business_attributes=cassandra_index.business_attributes,
        custom_attributes=cassandra_index.custom_attributes,
        pending_tasks=cassandra_index.pending_tasks,
        proxy=cassandra_index.proxy,
        is_incomplete=cassandra_index.is_incomplete,
        provenance_type=cassandra_index.provenance_type,
        home_id=cassandra_index.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _cassandra_index_from_nested(nested: CassandraIndexNested) -> CassandraIndex:
    """Convert nested format to flat CassandraIndex."""
    attrs = (
        nested.attributes
        if nested.attributes is not UNSET
        else CassandraIndexAttributes()
    )
    # Merge relationships from all three buckets
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        _CASSANDRA_INDEX_REL_FIELDS,
        CassandraIndexRelationshipAttributes,
    )
    return CassandraIndex(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        **_extract_cassandra_index_attrs(attrs),
        # Merged relationship attributes
        **merged_rels,
    )


def _cassandra_index_to_nested_bytes(
    cassandra_index: CassandraIndex, serde: Serde
) -> bytes:
    """Convert flat CassandraIndex to nested JSON bytes."""
    return serde.encode(_cassandra_index_to_nested(cassandra_index))


def _cassandra_index_from_nested_bytes(data: bytes, serde: Serde) -> CassandraIndex:
    """Convert nested JSON bytes to flat CassandraIndex."""
    nested = serde.decode(data, CassandraIndexNested)
    return _cassandra_index_from_nested(nested)


# ---------------------------------------------------------------------------
# Deferred field descriptor initialization
# ---------------------------------------------------------------------------
from pyatlan.model.fields.atlan_fields import KeywordField, RelationField  # noqa: E402

CassandraIndex.CASSANDRA_INDEX_KIND = KeywordField(
    "cassandraIndexKind", "cassandraIndexKind"
)
CassandraIndex.CASSANDRA_INDEX_OPTIONS = KeywordField(
    "cassandraIndexOptions", "cassandraIndexOptions"
)
CassandraIndex.CASSANDRA_INDEX_QUERY = KeywordField(
    "cassandraIndexQuery", "cassandraIndexQuery"
)
CassandraIndex.CASSANDRA_KEYSPACE_NAME = KeywordField(
    "cassandraKeyspaceName", "cassandraKeyspaceName"
)
CassandraIndex.CASSANDRA_TABLE_NAME = KeywordField(
    "cassandraTableName", "cassandraTableName"
)
CassandraIndex.CASSANDRA_VIEW_NAME = KeywordField(
    "cassandraViewName", "cassandraViewName"
)
CassandraIndex.CASSANDRA_TABLE_QUALIFIED_NAME = KeywordField(
    "cassandraTableQualifiedName", "cassandraTableQualifiedName"
)
CassandraIndex.CASSANDRA_VIEW_QUALIFIED_NAME = KeywordField(
    "cassandraViewQualifiedName", "cassandraViewQualifiedName"
)
CassandraIndex.NO_SQL_SCHEMA_DEFINITION = KeywordField(
    "noSQLSchemaDefinition", "noSQLSchemaDefinition"
)
CassandraIndex.CATALOG_DATASET_GUID = KeywordField(
    "catalogDatasetGuid", "catalogDatasetGuid"
)
CassandraIndex.INPUT_TO_AIRFLOW_TASKS = RelationField("inputToAirflowTasks")
CassandraIndex.OUTPUT_FROM_AIRFLOW_TASKS = RelationField("outputFromAirflowTasks")
CassandraIndex.ANOMALO_CHECKS = RelationField("anomaloChecks")
CassandraIndex.APPLICATION = RelationField("application")
CassandraIndex.APPLICATION_FIELD = RelationField("applicationField")
CassandraIndex.CASSANDRA_TABLE = RelationField("cassandraTable")
CassandraIndex.CONTEXT_REPOSITORIES = RelationField("contextRepositories")
CassandraIndex.DATA_CONTRACT_LATEST = RelationField("dataContractLatest")
CassandraIndex.DATA_CONTRACT_LATEST_CERTIFIED = RelationField(
    "dataContractLatestCertified"
)
CassandraIndex.OUTPUT_PORT_DATA_PRODUCTS = RelationField("outputPortDataProducts")
CassandraIndex.INPUT_PORT_DATA_PRODUCTS = RelationField("inputPortDataProducts")
CassandraIndex.MODEL_IMPLEMENTED_ENTITIES = RelationField("modelImplementedEntities")
CassandraIndex.MODEL_IMPLEMENTED_ATTRIBUTES = RelationField(
    "modelImplementedAttributes"
)
CassandraIndex.METRICS = RelationField("metrics")
CassandraIndex.DQ_BASE_DATASET_RULES = RelationField("dqBaseDatasetRules")
CassandraIndex.DQ_REFERENCE_DATASET_RULES = RelationField("dqReferenceDatasetRules")
CassandraIndex.GCP_DATAPLEX_ASPECT_TYPE_METADATA_ENTITIES = RelationField(
    "gcpDataplexAspectTypeMetadataEntities"
)
CassandraIndex.MEANINGS = RelationField("meanings")
CassandraIndex.MC_MONITORS = RelationField("mcMonitors")
CassandraIndex.MC_INCIDENTS = RelationField("mcIncidents")
CassandraIndex.PARTIAL_CHILD_FIELDS = RelationField("partialChildFields")
CassandraIndex.PARTIAL_CHILD_OBJECTS = RelationField("partialChildObjects")
CassandraIndex.INPUT_TO_PROCESSES = RelationField("inputToProcesses")
CassandraIndex.OUTPUT_FROM_PROCESSES = RelationField("outputFromProcesses")
CassandraIndex.USER_DEF_RELATIONSHIP_TO = RelationField("userDefRelationshipTo")
CassandraIndex.USER_DEF_RELATIONSHIP_FROM = RelationField("userDefRelationshipFrom")
CassandraIndex.FILES = RelationField("files")
CassandraIndex.LINKS = RelationField("links")
CassandraIndex.README = RelationField("readme")
CassandraIndex.SCHEMA_REGISTRY_SUBJECTS = RelationField("schemaRegistrySubjects")
CassandraIndex.SODA_CHECKS = RelationField("sodaChecks")
CassandraIndex.INPUT_TO_SPARK_JOBS = RelationField("inputToSparkJobs")
CassandraIndex.OUTPUT_FROM_SPARK_JOBS = RelationField("outputFromSparkJobs")
