# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# ruff: noqa: ARG002
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
Connection asset model with flattened inheritance.

This module provides:
- Connection: Flat asset class (easy to use)
- ConnectionAttributes: Nested attributes struct (extends AssetAttributes)
- ConnectionNested: Nested API format struct
"""

from __future__ import annotations

import re
from typing import Any, ClassVar, Dict, List, Optional, Union

import msgspec
from msgspec import UNSET, UnsetType

from pyatlan.model.enums import AtlanConnectorType
from pyatlan_v9.model.conversion_utils import (
    categorize_relationships,
    merge_relationships,
)
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset
from pyatlan_v9.utils import init_guid, validate_required_fields

from .anomalo_related import RelatedAnomaloCheck
from .app_related import RelatedApplication, RelatedApplicationField
from .asset import (
    _ASSET_REL_FIELDS,
    Asset,
    AssetAttributes,
    AssetNested,
    AssetRelationshipAttributes,
    _extract_asset_attrs,
    _populate_asset_attrs,
)
from .data_mesh_related import RelatedDataProduct
from .data_quality_related import RelatedDataQualityRule, RelatedMetric
from .gtc_related import RelatedAtlasGlossaryTerm
from .monte_carlo_related import RelatedMCIncident, RelatedMCMonitor
from .process_related import RelatedConnectionProcess
from .referenceable_related import RelatedReferenceable
from .resource_related import RelatedFile, RelatedLink, RelatedReadme
from .schema_registry_related import RelatedSchemaRegistrySubject
from .soda_related import RelatedSodaCheck

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class Connection(Asset):
    """
    Instance of a connection to a data source in Atlan.
    """

    CATEGORY: ClassVar[Any] = None
    SUB_CATEGORY: ClassVar[Any] = None
    HOST: ClassVar[Any] = None
    PORT: ClassVar[Any] = None
    ALLOW_QUERY: ClassVar[Any] = None
    ALLOW_QUERY_PREVIEW: ClassVar[Any] = None
    QUERY_PREVIEW_CONFIG: ClassVar[Any] = None
    CONNECTION_WORKFLOW_CONFIGURATION: ClassVar[Any] = None
    QUERY_CONFIG: ClassVar[Any] = None
    CREDENTIAL_STRATEGY: ClassVar[Any] = None
    PREVIEW_CREDENTIAL_STRATEGY: ClassVar[Any] = None
    POLICY_STRATEGY: ClassVar[Any] = None
    POLICY_STRATEGY_FOR_SAMPLE_PREVIEW: ClassVar[Any] = None
    QUERY_USERNAME_STRATEGY: ClassVar[Any] = None
    ROW_LIMIT: ClassVar[Any] = None
    QUERY_TIMEOUT: ClassVar[Any] = None
    DEFAULT_CREDENTIAL_GUID: ClassVar[Any] = None
    CONNECTION_DQ_CREDENTIAL_GUID: ClassVar[Any] = None
    CONNECTION_IS_DQ_ENABLED: ClassVar[Any] = None
    CONNECTION_DQ_ENVIRONMENT_SETUP_STATUS: ClassVar[Any] = None
    CONNECTION_DQ_ENVIRONMENT_SETUP_ERROR_MESSAGE: ClassVar[Any] = None
    CONNECTION_DQ_ENVIRONMENT_SETUP_STATUS_UPDATED_AT: ClassVar[Any] = None
    CONNECTION_DQ_ENVIRONMENT_SOURCE_DATABASE_NAME: ClassVar[Any] = None
    CONNECTOR_ICON: ClassVar[Any] = None
    CONNECTOR_IMAGE: ClassVar[Any] = None
    SOURCE_LOGO: ClassVar[Any] = None
    IS_SAMPLE_DATA_PREVIEW_ENABLED: ClassVar[Any] = None
    POPULARITY_INSIGHTS_TIMEFRAME: ClassVar[Any] = None
    HAS_POPULARITY_INSIGHTS: ClassVar[Any] = None
    CONNECTION_DBT_ENVIRONMENTS: ClassVar[Any] = None
    CONNECTION_SSO_CREDENTIAL_GUID: ClassVar[Any] = None
    USE_OBJECT_STORAGE: ClassVar[Any] = None
    CONNECTION_INSIGHTS_VIA_OAUTH_COOKIE: ClassVar[Any] = None
    OBJECT_STORAGE_UPLOAD_THRESHOLD: ClassVar[Any] = None
    VECTOR_EMBEDDINGS_ENABLED: ClassVar[Any] = None
    VECTOR_EMBEDDINGS_UPDATED_AT: ClassVar[Any] = None
    ANOMALO_CHECKS: ClassVar[Any] = None
    APPLICATION: ClassVar[Any] = None
    APPLICATION_FIELD: ClassVar[Any] = None
    OUTPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    INPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    METRICS: ClassVar[Any] = None
    DQ_BASE_DATASET_RULES: ClassVar[Any] = None
    DQ_REFERENCE_DATASET_RULES: ClassVar[Any] = None
    MEANINGS: ClassVar[Any] = None
    MC_MONITORS: ClassVar[Any] = None
    MC_INCIDENTS: ClassVar[Any] = None
    INPUT_TO_CONNECTION_PROCESSES: ClassVar[Any] = None
    OUTPUT_FROM_CONNECTION_PROCESSES: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_TO: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_FROM: ClassVar[Any] = None
    FILES: ClassVar[Any] = None
    LINKS: ClassVar[Any] = None
    README: ClassVar[Any] = None
    SCHEMA_REGISTRY_SUBJECTS: ClassVar[Any] = None
    SODA_CHECKS: ClassVar[Any] = None

    category: Union[str, None, UnsetType] = UNSET
    """Type of connection, for example WAREHOUSE, RDBMS, etc."""

    sub_category: Union[str, None, UnsetType] = UNSET
    """Subcategory of this connection."""

    host: Union[str, None, UnsetType] = UNSET
    """Host name of this connection's source."""

    port: Union[int, None, UnsetType] = UNSET
    """Port number to this connection's source."""

    allow_query: Union[bool, None, UnsetType] = UNSET
    """Whether using this connection to run queries on the source is allowed (true) or not (false)."""

    allow_query_preview: Union[bool, None, UnsetType] = UNSET
    """Whether using this connection to run preview queries on the source is allowed (true) or not (false)."""

    query_preview_config: Union[Dict[str, str], None, UnsetType] = UNSET
    """Configuration for preview queries."""

    connection_workflow_configuration: Union[Dict[str, str], None, UnsetType] = UNSET
    """Configuration for a workflow run."""

    query_config: Union[str, None, UnsetType] = UNSET
    """Query config for this connection."""

    credential_strategy: Union[str, None, UnsetType] = UNSET
    """Credential strategy to use for this connection for queries."""

    preview_credential_strategy: Union[str, None, UnsetType] = UNSET
    """Credential strategy to use for this connection for preview queries."""

    policy_strategy: Union[str, None, UnsetType] = UNSET
    """Policy strategy is a configuration that determines whether the Atlan policy will be applied to the results of insight queries and whether the query will be rewritten, applicable for stream api call made from insight screen"""

    policy_strategy_for_sample_preview: Union[str, None, UnsetType] = UNSET
    """Policy strategy is a configuration that determines whether the Atlan policy will be applied to the results of insight queries and whether the query will be rewritten. policyStrategyForSamplePreview config is applicable for sample preview call from assets screen"""

    query_username_strategy: Union[str, None, UnsetType] = UNSET
    """Username strategy to use for this connection for queries."""

    row_limit: Union[int, None, UnsetType] = UNSET
    """Maximum number of rows that can be returned for the source."""

    query_timeout: Union[int, None, UnsetType] = UNSET
    """Maximum time a query should be allowed to run before timing out."""

    default_credential_guid: Union[str, None, UnsetType] = UNSET
    """Unique identifier (GUID) for the default credentials to use for this connection."""

    connection_dq_credential_guid: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionDQCredentialGuid"
    )
    """Unique identifier (GUID) for the data quality credentials to use for this connection."""

    connection_is_dq_enabled: Union[bool, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionIsDQEnabled"
    )
    """Whether data quality is enabled for this connection (true) or not (false)."""

    connection_dq_environment_setup_status: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionDQEnvironmentSetupStatus"
    )
    """Status of the data quality environment setup for this connection."""

    connection_dq_environment_setup_error_message: Union[str, None, UnsetType] = (
        msgspec.field(default=UNSET, name="connectionDQEnvironmentSetupErrorMessage")
    )
    """Error message if data quality environment setup failed for this connection."""

    connection_dq_environment_setup_status_updated_at: Union[int, None, UnsetType] = (
        msgspec.field(default=UNSET, name="connectionDQEnvironmentSetupStatusUpdatedAt")
    )
    """Timestamp when the data quality environment setup status was last updated."""

    connection_dq_environment_source_database_name: Union[str, None, UnsetType] = (
        msgspec.field(default=UNSET, name="connectionDQEnvironmentSourceDatabaseName")
    )
    """Name of the database in the source environment for data quality."""

    connector_icon: Union[str, None, UnsetType] = UNSET
    """Unused. Only the value of connectorType impacts icons."""

    connector_image: Union[str, None, UnsetType] = UNSET
    """Unused. Only the value of connectorType impacts icons."""

    source_logo: Union[str, None, UnsetType] = UNSET
    """Unused. Only the value of connectorType impacts icons."""

    is_sample_data_preview_enabled: Union[bool, None, UnsetType] = UNSET
    """Whether sample data can be previewed for this connection (true) or not (false)."""

    popularity_insights_timeframe: Union[int, None, UnsetType] = UNSET
    """Number of days over which popularity is calculated, for example 30 days."""

    has_popularity_insights: Union[bool, None, UnsetType] = UNSET
    """Whether this connection has popularity insights (true) or not (false)."""

    connection_dbt_environments: Union[List[str], None, UnsetType] = UNSET
    """"""

    connection_sso_credential_guid: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionSSOCredentialGuid"
    )
    """Unique identifier (GUID) for the SSO credentials to use for this connection."""

    use_object_storage: Union[bool, None, UnsetType] = UNSET
    """Whether to upload to S3, GCP, or another storage location (true) or not (false)."""

    connection_insights_via_oauth_cookie: Union[bool, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionInsightsViaOAuthCookie"
    )
    """Whether cookie based OAuth is enabled in Insights for this connection (true) or not (false)."""

    object_storage_upload_threshold: Union[int, None, UnsetType] = UNSET
    """Number of rows after which results should be uploaded to storage."""

    vector_embeddings_enabled: Union[bool, None, UnsetType] = UNSET
    """"""

    vector_embeddings_updated_at: Union[int, None, UnsetType] = UNSET
    """"""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    input_to_connection_processes: Union[
        List[RelatedConnectionProcess], None, UnsetType
    ] = UNSET
    """Connection process to which this asset provides input."""

    output_from_connection_processes: Union[
        List[RelatedConnectionProcess], None, UnsetType
    ] = UNSET
    """Connection processs from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """"""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        self.type_name = "Connection"

    # =========================================================================
    # SDK Methods
    # =========================================================================

    _QUALIFIED_NAME_PATTERN: ClassVar[re.Pattern] = re.compile(r"^default/[^/]+/[^/]+$")

    @classmethod
    @init_guid
    def creator(
        cls,
        *,
        client: AtlanClient,
        name: str,
        connector_type: AtlanConnectorType,
        admin_users: Optional[List[str]] = None,
        admin_groups: Optional[List[str]] = None,
        admin_roles: Optional[List[str]] = None,
        host: Optional[str] = None,
        port: Optional[int] = None,
    ) -> "Connection":
        """
        Create a new Connection asset.

        Args:
            client: AtlanClient for cache validation
            name: Simple name of the connection
            connector_type: Type of connector for the connection
            admin_users: List of admin usernames
            admin_groups: List of admin group names
            admin_roles: List of admin role GUIDs
            host: Optional hostname for the connection
            port: Optional port number for the connection

        Returns:
            New Connection instance with all fields populated

        Raises:
            ValueError: If required parameters are missing or invalid
        """
        validate_required_fields(
            ["client", "name", "connector_type"], [client, name, connector_type]
        )
        if not admin_users and not admin_groups and not admin_roles:
            raise ValueError(
                "One of admin_user, admin_groups or admin_roles is required"
            )
        client.user_cache.validate_names(names=admin_users or [])
        client.role_cache.validate_idstrs(idstrs=admin_roles or [])
        client.group_cache.validate_aliases(aliases=admin_groups or [])

        kwargs: dict = dict(
            name=name,
            qualified_name=connector_type.to_qualified_name(),
            connector_name=connector_type.value,
            category=connector_type.category.value,
            admin_users=set() if admin_users is None else set(admin_users),
            admin_groups=set() if admin_groups is None else set(admin_groups),
            admin_roles=set() if admin_roles is None else set(admin_roles),
        )
        if host is not None:
            kwargs["host"] = host
        if port is not None:
            kwargs["port"] = port
        return cls(**kwargs)

    @classmethod
    @init_guid
    async def creator_async(
        cls,
        *,
        client: Any,
        name: str,
        connector_type: AtlanConnectorType,
        admin_users: Optional[List[str]] = None,
        admin_groups: Optional[List[str]] = None,
        admin_roles: Optional[List[str]] = None,
        host: Optional[str] = None,
        port: Optional[int] = None,
    ) -> "Connection":
        """
        Async version of creator() for creating a new Connection asset.

        :param client: async Atlan client for cache validation
        :param name: name for the connection
        :param connector_type: type of connector
        :param admin_users: list of admin usernames
        :param admin_groups: list of admin group names
        :param admin_roles: list of admin role GUIDs
        :param host: optional hostname
        :param port: optional port number
        :returns: the new connection object
        :raises ValueError: if required parameters are missing or invalid
        """
        validate_required_fields(
            ["client", "name", "connector_type"], [client, name, connector_type]
        )
        if not admin_users and not admin_groups and not admin_roles:
            raise ValueError(
                "One of admin_user, admin_groups or admin_roles is required"
            )
        await client.user_cache.validate_names(names=admin_users or [])
        await client.role_cache.validate_idstrs(idstrs=admin_roles or [])
        await client.group_cache.validate_aliases(aliases=admin_groups or [])

        kwargs: dict = dict(
            name=name,
            qualified_name=connector_type.to_qualified_name(),
            connector_name=connector_type.value,
            category=connector_type.category.value,
            admin_users=set() if admin_users is None else set(admin_users),
            admin_groups=set() if admin_groups is None else set(admin_groups),
            admin_roles=set() if admin_roles is None else set(admin_roles),
        )
        if host is not None:
            kwargs["host"] = host
        if port is not None:
            kwargs["port"] = port
        return cls(**kwargs)

    @classmethod
    def updater(cls, *, qualified_name: str, name: str) -> "Connection":
        """
        Create a Connection instance for updating an existing asset.

        Args:
            qualified_name: Unique name of the connection to update
            name: Simple name of the connection

        Returns:
            Connection instance configured for updates

        Raises:
            ValueError: If required parameters are missing
        """
        validate_required_fields(["qualified_name", "name"], [qualified_name, name])
        return cls(qualified_name=qualified_name, name=name)

    def trim_to_required(self) -> "Connection":
        """
        Return a Connection with only required fields for reference.

        Returns:
            Connection instance with only qualified_name and name set
        """
        return Connection(qualified_name=self.qualified_name, name=self.name)

    @classmethod
    def create(cls, **kwargs) -> "Connection":
        """Backward compatibility alias for creator()."""
        return cls.creator(**kwargs)

    @classmethod
    def create_for_modification(cls, **kwargs) -> "Connection":
        """Backward compatibility alias for updater()."""
        return cls.updater(**kwargs)

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return self.to_nested_bytes(serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    def to_nested_bytes(self, serde: Serde | None = None) -> bytes:
        """Serialize to Atlas nested-format JSON bytes (pure msgspec, no dict intermediate)."""
        if serde is None:
            serde = get_serde()
        return _connection_to_nested_bytes(self, serde)

    @staticmethod
    def from_json(json_data: str | bytes, serde: Serde | None = None) -> Connection:
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            Connection instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _connection_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class ConnectionAttributes(AssetAttributes):
    """Connection-specific attributes for nested API format."""

    category: Union[str, None, UnsetType] = UNSET
    """Type of connection, for example WAREHOUSE, RDBMS, etc."""

    sub_category: Union[str, None, UnsetType] = UNSET
    """Subcategory of this connection."""

    host: Union[str, None, UnsetType] = UNSET
    """Host name of this connection's source."""

    port: Union[int, None, UnsetType] = UNSET
    """Port number to this connection's source."""

    allow_query: Union[bool, None, UnsetType] = UNSET
    """Whether using this connection to run queries on the source is allowed (true) or not (false)."""

    allow_query_preview: Union[bool, None, UnsetType] = UNSET
    """Whether using this connection to run preview queries on the source is allowed (true) or not (false)."""

    query_preview_config: Union[Dict[str, str], None, UnsetType] = UNSET
    """Configuration for preview queries."""

    connection_workflow_configuration: Union[Dict[str, str], None, UnsetType] = UNSET
    """Configuration for a workflow run."""

    query_config: Union[str, None, UnsetType] = UNSET
    """Query config for this connection."""

    credential_strategy: Union[str, None, UnsetType] = UNSET
    """Credential strategy to use for this connection for queries."""

    preview_credential_strategy: Union[str, None, UnsetType] = UNSET
    """Credential strategy to use for this connection for preview queries."""

    policy_strategy: Union[str, None, UnsetType] = UNSET
    """Policy strategy is a configuration that determines whether the Atlan policy will be applied to the results of insight queries and whether the query will be rewritten, applicable for stream api call made from insight screen"""

    policy_strategy_for_sample_preview: Union[str, None, UnsetType] = UNSET
    """Policy strategy is a configuration that determines whether the Atlan policy will be applied to the results of insight queries and whether the query will be rewritten. policyStrategyForSamplePreview config is applicable for sample preview call from assets screen"""

    query_username_strategy: Union[str, None, UnsetType] = UNSET
    """Username strategy to use for this connection for queries."""

    row_limit: Union[int, None, UnsetType] = UNSET
    """Maximum number of rows that can be returned for the source."""

    query_timeout: Union[int, None, UnsetType] = UNSET
    """Maximum time a query should be allowed to run before timing out."""

    default_credential_guid: Union[str, None, UnsetType] = UNSET
    """Unique identifier (GUID) for the default credentials to use for this connection."""

    connection_dq_credential_guid: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionDQCredentialGuid"
    )
    """Unique identifier (GUID) for the data quality credentials to use for this connection."""

    connection_is_dq_enabled: Union[bool, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionIsDQEnabled"
    )
    """Whether data quality is enabled for this connection (true) or not (false)."""

    connection_dq_environment_setup_status: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionDQEnvironmentSetupStatus"
    )
    """Status of the data quality environment setup for this connection."""

    connection_dq_environment_setup_error_message: Union[str, None, UnsetType] = (
        msgspec.field(default=UNSET, name="connectionDQEnvironmentSetupErrorMessage")
    )
    """Error message if data quality environment setup failed for this connection."""

    connection_dq_environment_setup_status_updated_at: Union[int, None, UnsetType] = (
        msgspec.field(default=UNSET, name="connectionDQEnvironmentSetupStatusUpdatedAt")
    )
    """Timestamp when the data quality environment setup status was last updated."""

    connection_dq_environment_source_database_name: Union[str, None, UnsetType] = (
        msgspec.field(default=UNSET, name="connectionDQEnvironmentSourceDatabaseName")
    )
    """Name of the database in the source environment for data quality."""

    connector_icon: Union[str, None, UnsetType] = UNSET
    """Unused. Only the value of connectorType impacts icons."""

    connector_image: Union[str, None, UnsetType] = UNSET
    """Unused. Only the value of connectorType impacts icons."""

    source_logo: Union[str, None, UnsetType] = UNSET
    """Unused. Only the value of connectorType impacts icons."""

    is_sample_data_preview_enabled: Union[bool, None, UnsetType] = UNSET
    """Whether sample data can be previewed for this connection (true) or not (false)."""

    popularity_insights_timeframe: Union[int, None, UnsetType] = UNSET
    """Number of days over which popularity is calculated, for example 30 days."""

    has_popularity_insights: Union[bool, None, UnsetType] = UNSET
    """Whether this connection has popularity insights (true) or not (false)."""

    connection_dbt_environments: Union[List[str], None, UnsetType] = UNSET
    """"""

    connection_sso_credential_guid: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionSSOCredentialGuid"
    )
    """Unique identifier (GUID) for the SSO credentials to use for this connection."""

    use_object_storage: Union[bool, None, UnsetType] = UNSET
    """Whether to upload to S3, GCP, or another storage location (true) or not (false)."""

    connection_insights_via_oauth_cookie: Union[bool, None, UnsetType] = msgspec.field(
        default=UNSET, name="connectionInsightsViaOAuthCookie"
    )
    """Whether cookie based OAuth is enabled in Insights for this connection (true) or not (false)."""

    object_storage_upload_threshold: Union[int, None, UnsetType] = UNSET
    """Number of rows after which results should be uploaded to storage."""

    vector_embeddings_enabled: Union[bool, None, UnsetType] = UNSET
    """"""

    vector_embeddings_updated_at: Union[int, None, UnsetType] = UNSET
    """"""


class ConnectionRelationshipAttributes(AssetRelationshipAttributes):
    """Connection-specific relationship attributes for nested API format."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    input_to_connection_processes: Union[
        List[RelatedConnectionProcess], None, UnsetType
    ] = UNSET
    """Connection process to which this asset provides input."""

    output_from_connection_processes: Union[
        List[RelatedConnectionProcess], None, UnsetType
    ] = UNSET
    """Connection processs from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """"""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""


class ConnectionNested(AssetNested):
    """Connection in nested API format for high-performance serialization."""

    attributes: Union[ConnectionAttributes, UnsetType] = UNSET
    relationship_attributes: Union[ConnectionRelationshipAttributes, UnsetType] = UNSET
    append_relationship_attributes: Union[
        ConnectionRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        ConnectionRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION HELPERS & CONSTANTS
# =============================================================================

_CONNECTION_REL_FIELDS: List[str] = [
    *_ASSET_REL_FIELDS,
    "anomalo_checks",
    "application",
    "application_field",
    "output_port_data_products",
    "input_port_data_products",
    "metrics",
    "dq_base_dataset_rules",
    "dq_reference_dataset_rules",
    "meanings",
    "mc_monitors",
    "mc_incidents",
    "input_to_connection_processes",
    "output_from_connection_processes",
    "user_def_relationship_to",
    "user_def_relationship_from",
    "files",
    "links",
    "readme",
    "schema_registry_subjects",
    "soda_checks",
]


def _populate_connection_attrs(attrs: ConnectionAttributes, obj: Connection) -> None:
    """Populate Connection-specific attributes on the attrs struct."""
    _populate_asset_attrs(attrs, obj)
    attrs.category = obj.category
    attrs.sub_category = obj.sub_category
    attrs.host = obj.host
    attrs.port = obj.port
    attrs.allow_query = obj.allow_query
    attrs.allow_query_preview = obj.allow_query_preview
    attrs.query_preview_config = obj.query_preview_config
    attrs.connection_workflow_configuration = obj.connection_workflow_configuration
    attrs.query_config = obj.query_config
    attrs.credential_strategy = obj.credential_strategy
    attrs.preview_credential_strategy = obj.preview_credential_strategy
    attrs.policy_strategy = obj.policy_strategy
    attrs.policy_strategy_for_sample_preview = obj.policy_strategy_for_sample_preview
    attrs.query_username_strategy = obj.query_username_strategy
    attrs.row_limit = obj.row_limit
    attrs.query_timeout = obj.query_timeout
    attrs.default_credential_guid = obj.default_credential_guid
    attrs.connection_dq_credential_guid = obj.connection_dq_credential_guid
    attrs.connection_is_dq_enabled = obj.connection_is_dq_enabled
    attrs.connection_dq_environment_setup_status = (
        obj.connection_dq_environment_setup_status
    )
    attrs.connection_dq_environment_setup_error_message = (
        obj.connection_dq_environment_setup_error_message
    )
    attrs.connection_dq_environment_setup_status_updated_at = (
        obj.connection_dq_environment_setup_status_updated_at
    )
    attrs.connection_dq_environment_source_database_name = (
        obj.connection_dq_environment_source_database_name
    )
    attrs.connector_icon = obj.connector_icon
    attrs.connector_image = obj.connector_image
    attrs.source_logo = obj.source_logo
    attrs.is_sample_data_preview_enabled = obj.is_sample_data_preview_enabled
    attrs.popularity_insights_timeframe = obj.popularity_insights_timeframe
    attrs.has_popularity_insights = obj.has_popularity_insights
    attrs.connection_dbt_environments = obj.connection_dbt_environments
    attrs.connection_sso_credential_guid = obj.connection_sso_credential_guid
    attrs.use_object_storage = obj.use_object_storage
    attrs.connection_insights_via_oauth_cookie = (
        obj.connection_insights_via_oauth_cookie
    )
    attrs.object_storage_upload_threshold = obj.object_storage_upload_threshold
    attrs.vector_embeddings_enabled = obj.vector_embeddings_enabled
    attrs.vector_embeddings_updated_at = obj.vector_embeddings_updated_at


def _extract_connection_attrs(attrs: ConnectionAttributes) -> dict:
    """Extract all Connection attributes from the attrs struct into a flat dict."""
    result = _extract_asset_attrs(attrs)
    result["category"] = attrs.category
    result["sub_category"] = attrs.sub_category
    result["host"] = attrs.host
    result["port"] = attrs.port
    result["allow_query"] = attrs.allow_query
    result["allow_query_preview"] = attrs.allow_query_preview
    result["query_preview_config"] = attrs.query_preview_config
    result["connection_workflow_configuration"] = (
        attrs.connection_workflow_configuration
    )
    result["query_config"] = attrs.query_config
    result["credential_strategy"] = attrs.credential_strategy
    result["preview_credential_strategy"] = attrs.preview_credential_strategy
    result["policy_strategy"] = attrs.policy_strategy
    result["policy_strategy_for_sample_preview"] = (
        attrs.policy_strategy_for_sample_preview
    )
    result["query_username_strategy"] = attrs.query_username_strategy
    result["row_limit"] = attrs.row_limit
    result["query_timeout"] = attrs.query_timeout
    result["default_credential_guid"] = attrs.default_credential_guid
    result["connection_dq_credential_guid"] = attrs.connection_dq_credential_guid
    result["connection_is_dq_enabled"] = attrs.connection_is_dq_enabled
    result["connection_dq_environment_setup_status"] = (
        attrs.connection_dq_environment_setup_status
    )
    result["connection_dq_environment_setup_error_message"] = (
        attrs.connection_dq_environment_setup_error_message
    )
    result["connection_dq_environment_setup_status_updated_at"] = (
        attrs.connection_dq_environment_setup_status_updated_at
    )
    result["connection_dq_environment_source_database_name"] = (
        attrs.connection_dq_environment_source_database_name
    )
    result["connector_icon"] = attrs.connector_icon
    result["connector_image"] = attrs.connector_image
    result["source_logo"] = attrs.source_logo
    result["is_sample_data_preview_enabled"] = attrs.is_sample_data_preview_enabled
    result["popularity_insights_timeframe"] = attrs.popularity_insights_timeframe
    result["has_popularity_insights"] = attrs.has_popularity_insights
    result["connection_dbt_environments"] = attrs.connection_dbt_environments
    result["connection_sso_credential_guid"] = attrs.connection_sso_credential_guid
    result["use_object_storage"] = attrs.use_object_storage
    result["connection_insights_via_oauth_cookie"] = (
        attrs.connection_insights_via_oauth_cookie
    )
    result["object_storage_upload_threshold"] = attrs.object_storage_upload_threshold
    result["vector_embeddings_enabled"] = attrs.vector_embeddings_enabled
    result["vector_embeddings_updated_at"] = attrs.vector_embeddings_updated_at
    return result


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _connection_to_nested(connection: Connection) -> ConnectionNested:
    """Convert flat Connection to nested format."""
    attrs = ConnectionAttributes()
    _populate_connection_attrs(attrs, connection)
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    replace_rels, append_rels, remove_rels = categorize_relationships(
        connection, _CONNECTION_REL_FIELDS, ConnectionRelationshipAttributes
    )
    return ConnectionNested(
        guid=connection.guid,
        type_name=connection.type_name,
        status=connection.status,
        version=connection.version,
        create_time=connection.create_time,
        update_time=connection.update_time,
        created_by=connection.created_by,
        updated_by=connection.updated_by,
        classifications=connection.classifications,
        classification_names=connection.classification_names,
        meanings=connection.meanings,
        labels=connection.labels,
        business_attributes=connection.business_attributes,
        custom_attributes=connection.custom_attributes,
        pending_tasks=connection.pending_tasks,
        proxy=connection.proxy,
        is_incomplete=connection.is_incomplete,
        provenance_type=connection.provenance_type,
        home_id=connection.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _connection_from_nested(nested: ConnectionNested) -> Connection:
    """Convert nested format to flat Connection."""
    attrs = (
        nested.attributes if nested.attributes is not UNSET else ConnectionAttributes()
    )
    # Merge relationships from all three buckets
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        _CONNECTION_REL_FIELDS,
        ConnectionRelationshipAttributes,
    )
    return Connection(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        **_extract_connection_attrs(attrs),
        # Merged relationship attributes
        **merged_rels,
    )


def _connection_to_nested_bytes(connection: Connection, serde: Serde) -> bytes:
    """Convert flat Connection to nested JSON bytes."""
    return serde.encode(_connection_to_nested(connection))


def _connection_from_nested_bytes(data: bytes, serde: Serde) -> Connection:
    """Convert nested JSON bytes to flat Connection."""
    nested = serde.decode(data, ConnectionNested)
    return _connection_from_nested(nested)


# ---------------------------------------------------------------------------
# Deferred field descriptor initialization
# ---------------------------------------------------------------------------
from pyatlan.model.fields.atlan_fields import (  # noqa: E402
    BooleanField,
    KeywordField,
    NumericField,
    RelationField,
    TextField,
)

Connection.CATEGORY = KeywordField("category", "category")
Connection.SUB_CATEGORY = KeywordField("subCategory", "subCategory")
Connection.HOST = KeywordField("host", "host")
Connection.PORT = NumericField("port", "port")
Connection.ALLOW_QUERY = BooleanField("allowQuery", "allowQuery")
Connection.ALLOW_QUERY_PREVIEW = BooleanField("allowQueryPreview", "allowQueryPreview")
Connection.QUERY_PREVIEW_CONFIG = KeywordField(
    "queryPreviewConfig", "queryPreviewConfig"
)
Connection.CONNECTION_WORKFLOW_CONFIGURATION = KeywordField(
    "connectionWorkflowConfiguration", "connectionWorkflowConfiguration"
)
Connection.QUERY_CONFIG = KeywordField("queryConfig", "queryConfig")
Connection.CREDENTIAL_STRATEGY = KeywordField(
    "credentialStrategy", "credentialStrategy"
)
Connection.PREVIEW_CREDENTIAL_STRATEGY = KeywordField(
    "previewCredentialStrategy", "previewCredentialStrategy"
)
Connection.POLICY_STRATEGY = KeywordField("policyStrategy", "policyStrategy")
Connection.POLICY_STRATEGY_FOR_SAMPLE_PREVIEW = KeywordField(
    "policyStrategyForSamplePreview", "policyStrategyForSamplePreview"
)
Connection.QUERY_USERNAME_STRATEGY = KeywordField(
    "queryUsernameStrategy", "queryUsernameStrategy"
)
Connection.ROW_LIMIT = NumericField("rowLimit", "rowLimit")
Connection.QUERY_TIMEOUT = NumericField("queryTimeout", "queryTimeout")
Connection.DEFAULT_CREDENTIAL_GUID = KeywordField(
    "defaultCredentialGuid", "defaultCredentialGuid"
)
Connection.CONNECTION_DQ_CREDENTIAL_GUID = KeywordField(
    "connectionDQCredentialGuid", "connectionDQCredentialGuid"
)
Connection.CONNECTION_IS_DQ_ENABLED = BooleanField(
    "connectionIsDQEnabled", "connectionIsDQEnabled"
)
Connection.CONNECTION_DQ_ENVIRONMENT_SETUP_STATUS = KeywordField(
    "connectionDQEnvironmentSetupStatus", "connectionDQEnvironmentSetupStatus"
)
Connection.CONNECTION_DQ_ENVIRONMENT_SETUP_ERROR_MESSAGE = TextField(
    "connectionDQEnvironmentSetupErrorMessage",
    "connectionDQEnvironmentSetupErrorMessage",
)
Connection.CONNECTION_DQ_ENVIRONMENT_SETUP_STATUS_UPDATED_AT = NumericField(
    "connectionDQEnvironmentSetupStatusUpdatedAt",
    "connectionDQEnvironmentSetupStatusUpdatedAt",
)
Connection.CONNECTION_DQ_ENVIRONMENT_SOURCE_DATABASE_NAME = KeywordField(
    "connectionDQEnvironmentSourceDatabaseName",
    "connectionDQEnvironmentSourceDatabaseName",
)
Connection.CONNECTOR_ICON = KeywordField("connectorIcon", "connectorIcon")
Connection.CONNECTOR_IMAGE = KeywordField("connectorImage", "connectorImage")
Connection.SOURCE_LOGO = KeywordField("sourceLogo", "sourceLogo")
Connection.IS_SAMPLE_DATA_PREVIEW_ENABLED = BooleanField(
    "isSampleDataPreviewEnabled", "isSampleDataPreviewEnabled"
)
Connection.POPULARITY_INSIGHTS_TIMEFRAME = NumericField(
    "popularityInsightsTimeframe", "popularityInsightsTimeframe"
)
Connection.HAS_POPULARITY_INSIGHTS = BooleanField(
    "hasPopularityInsights", "hasPopularityInsights"
)
Connection.CONNECTION_DBT_ENVIRONMENTS = KeywordField(
    "connectionDbtEnvironments", "connectionDbtEnvironments"
)
Connection.CONNECTION_SSO_CREDENTIAL_GUID = KeywordField(
    "connectionSSOCredentialGuid", "connectionSSOCredentialGuid"
)
Connection.USE_OBJECT_STORAGE = BooleanField("useObjectStorage", "useObjectStorage")
Connection.CONNECTION_INSIGHTS_VIA_OAUTH_COOKIE = BooleanField(
    "connectionInsightsViaOAuthCookie", "connectionInsightsViaOAuthCookie"
)
Connection.OBJECT_STORAGE_UPLOAD_THRESHOLD = NumericField(
    "objectStorageUploadThreshold", "objectStorageUploadThreshold"
)
Connection.VECTOR_EMBEDDINGS_ENABLED = BooleanField(
    "vectorEmbeddingsEnabled", "vectorEmbeddingsEnabled"
)
Connection.VECTOR_EMBEDDINGS_UPDATED_AT = NumericField(
    "vectorEmbeddingsUpdatedAt", "vectorEmbeddingsUpdatedAt"
)
Connection.ANOMALO_CHECKS = RelationField("anomaloChecks")
Connection.APPLICATION = RelationField("application")
Connection.APPLICATION_FIELD = RelationField("applicationField")
Connection.OUTPUT_PORT_DATA_PRODUCTS = RelationField("outputPortDataProducts")
Connection.INPUT_PORT_DATA_PRODUCTS = RelationField("inputPortDataProducts")
Connection.METRICS = RelationField("metrics")
Connection.DQ_BASE_DATASET_RULES = RelationField("dqBaseDatasetRules")
Connection.DQ_REFERENCE_DATASET_RULES = RelationField("dqReferenceDatasetRules")
Connection.MEANINGS = RelationField("meanings")
Connection.MC_MONITORS = RelationField("mcMonitors")
Connection.MC_INCIDENTS = RelationField("mcIncidents")
Connection.INPUT_TO_CONNECTION_PROCESSES = RelationField("inputToConnectionProcesses")
Connection.OUTPUT_FROM_CONNECTION_PROCESSES = RelationField(
    "outputFromConnectionProcesses"
)
Connection.USER_DEF_RELATIONSHIP_TO = RelationField("userDefRelationshipTo")
Connection.USER_DEF_RELATIONSHIP_FROM = RelationField("userDefRelationshipFrom")
Connection.FILES = RelationField("files")
Connection.LINKS = RelationField("links")
Connection.README = RelationField("readme")
Connection.SCHEMA_REGISTRY_SUBJECTS = RelationField("schemaRegistrySubjects")
Connection.SODA_CHECKS = RelationField("sodaChecks")
