# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# ruff: noqa: ARG002
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
DbtDimension asset model with flattened inheritance.

This module provides:
- DbtDimension: Flat asset class (easy to use)
- DbtDimensionAttributes: Nested attributes struct (extends AssetAttributes)
- DbtDimensionNested: Nested API format struct
"""

from __future__ import annotations

from typing import Any, ClassVar, Union

from msgspec import UNSET, UnsetType

from .airflow_related import RelatedAirflowTask
from .anomalo_related import RelatedAnomaloCheck
from .app_related import RelatedApplication, RelatedApplicationField
from .asset import (
    _ASSET_REL_FIELDS,
    Asset,
    AssetAttributes,
    AssetNested,
    AssetRelationshipAttributes,
    _extract_asset_attrs,
    _populate_asset_attrs,
)
from .data_mesh_related import RelatedDataProduct
from .data_quality_related import RelatedDataQualityRule, RelatedMetric
from .gtc_related import RelatedAtlasGlossaryTerm
from .model_related import RelatedModelAttribute, RelatedModelEntity
from .monte_carlo_related import RelatedMCIncident, RelatedMCMonitor
from .partial_related import RelatedPartialField, RelatedPartialObject
from .process_related import RelatedProcess
from .referenceable_related import RelatedReferenceable
from .resource_related import RelatedFile, RelatedLink, RelatedReadme
from .schema_registry_related import RelatedSchemaRegistrySubject
from .semantic_related import RelatedSemanticModel
from .soda_related import RelatedSodaCheck
from .spark_related import RelatedSparkJob
from pyatlan_v9.model.conversion_utils import (
    categorize_relationships,
    merge_relationships,
)
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class DbtDimension(Asset):
    """
    Instance of a dbt semantic dimension in Atlan.
    """

    DBT_SEMANTIC_MODEL_QUALIFIED_NAME: ClassVar[Any] = None
    DBT_SEMANTIC_FIELD_TIME_GRANULARITY: ClassVar[Any] = None
    DBT_ALIAS: ClassVar[Any] = None
    DBT_META: ClassVar[Any] = None
    DBT_UNIQUE_ID: ClassVar[Any] = None
    DBT_ACCOUNT_NAME: ClassVar[Any] = None
    DBT_PROJECT_NAME: ClassVar[Any] = None
    DBT_PACKAGE_NAME: ClassVar[Any] = None
    DBT_JOB_NAME: ClassVar[Any] = None
    DBT_JOB_SCHEDULE: ClassVar[Any] = None
    DBT_JOB_STATUS: ClassVar[Any] = None
    DBT_JOB_SCHEDULE_CRON_HUMANIZED: ClassVar[Any] = None
    DBT_JOB_LAST_RUN: ClassVar[Any] = None
    DBT_JOB_NEXT_RUN: ClassVar[Any] = None
    DBT_JOB_NEXT_RUN_HUMANIZED: ClassVar[Any] = None
    DBT_ENVIRONMENT_NAME: ClassVar[Any] = None
    DBT_ENVIRONMENT_DBT_VERSION: ClassVar[Any] = None
    DBT_TAGS: ClassVar[Any] = None
    DBT_CONNECTION_CONTEXT: ClassVar[Any] = None
    DBT_SEMANTIC_LAYER_PROXY_URL: ClassVar[Any] = None
    DBT_JOB_RUNS: ClassVar[Any] = None
    SEMANTIC_EXPRESSION: ClassVar[Any] = None
    SEMANTIC_TYPE: ClassVar[Any] = None
    INPUT_TO_AIRFLOW_TASKS: ClassVar[Any] = None
    OUTPUT_FROM_AIRFLOW_TASKS: ClassVar[Any] = None
    ANOMALO_CHECKS: ClassVar[Any] = None
    APPLICATION: ClassVar[Any] = None
    APPLICATION_FIELD: ClassVar[Any] = None
    OUTPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    INPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ENTITIES: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ATTRIBUTES: ClassVar[Any] = None
    METRICS: ClassVar[Any] = None
    DQ_BASE_DATASET_RULES: ClassVar[Any] = None
    DQ_REFERENCE_DATASET_RULES: ClassVar[Any] = None
    MEANINGS: ClassVar[Any] = None
    MC_MONITORS: ClassVar[Any] = None
    MC_INCIDENTS: ClassVar[Any] = None
    PARTIAL_CHILD_FIELDS: ClassVar[Any] = None
    PARTIAL_CHILD_OBJECTS: ClassVar[Any] = None
    INPUT_TO_PROCESSES: ClassVar[Any] = None
    OUTPUT_FROM_PROCESSES: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_TO: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_FROM: ClassVar[Any] = None
    FILES: ClassVar[Any] = None
    LINKS: ClassVar[Any] = None
    README: ClassVar[Any] = None
    SCHEMA_REGISTRY_SUBJECTS: ClassVar[Any] = None
    SEMANTIC_MODEL: ClassVar[Any] = None
    SODA_CHECKS: ClassVar[Any] = None
    INPUT_TO_SPARK_JOBS: ClassVar[Any] = None
    OUTPUT_FROM_SPARK_JOBS: ClassVar[Any] = None

    type_name: Union[str, UnsetType] = "DbtDimension"

    dbt_semantic_model_qualified_name: str | None | UnsetType = UNSET
    """Qualified name of the dbt semantic model this dimension belongs to."""

    dbt_semantic_field_time_granularity: str | None | UnsetType = UNSET
    """Time granularity for time dimensions only (day/week/month/quarter/year)."""

    dbt_alias: str | None | UnsetType = UNSET
    """Alias of this asset in dbt."""

    dbt_meta: str | None | UnsetType = UNSET
    """Metadata for this asset in dbt, specifically everything under the 'meta' key in the dbt object."""

    dbt_unique_id: str | None | UnsetType = UNSET
    """Unique identifier of this asset in dbt."""

    dbt_account_name: str | None | UnsetType = UNSET
    """Name of the account in which this asset exists in dbt."""

    dbt_project_name: str | None | UnsetType = UNSET
    """Name of the project in which this asset exists in dbt."""

    dbt_package_name: str | None | UnsetType = UNSET
    """Name of the package in which this asset exists in dbt."""

    dbt_job_name: str | None | UnsetType = UNSET
    """Name of the job that materialized this asset in dbt."""

    dbt_job_schedule: str | None | UnsetType = UNSET
    """Schedule of the job that materialized this asset in dbt."""

    dbt_job_status: str | None | UnsetType = UNSET
    """Status of the job that materialized this asset in dbt."""

    dbt_job_schedule_cron_humanized: str | None | UnsetType = UNSET
    """Human-readable cron schedule of the job that materialized this asset in dbt."""

    dbt_job_last_run: int | None | UnsetType = UNSET
    """Time (epoch) at which the job that materialized this asset in dbt last ran, in milliseconds."""

    dbt_job_next_run: int | None | UnsetType = UNSET
    """Time (epoch) at which the job that materialized this asset in dbt will next run, in milliseconds."""

    dbt_job_next_run_humanized: str | None | UnsetType = UNSET
    """Human-readable time at which the job that materialized this asset in dbt will next run."""

    dbt_environment_name: str | None | UnsetType = UNSET
    """Name of the environment in which this asset exists in dbt."""

    dbt_environment_dbt_version: str | None | UnsetType = UNSET
    """Version of dbt used in the environment."""

    dbt_tags: list[str] | None | UnsetType = UNSET
    """List of tags attached to this asset in dbt."""

    dbt_connection_context: str | None | UnsetType = UNSET
    """Connection context for this asset in dbt."""

    dbt_semantic_layer_proxy_url: str | None | UnsetType = UNSET
    """URL of the semantic layer proxy for this asset in dbt."""

    dbt_job_runs: list[dict[str, Any]] | None | UnsetType = UNSET
    """List of latest dbt job runs across all environments."""

    semantic_expression: str | None | UnsetType = UNSET
    """Column name or SQL expression for the semantic field."""

    semantic_type: str | None | UnsetType = UNSET
    """Detailed type of the semantic field (e.g., type of measure, type of dimension, or type of entity)."""

    input_to_airflow_tasks: list[RelatedAirflowTask] | None | UnsetType = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: list[RelatedAirflowTask] | None | UnsetType = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: list[RelatedAnomaloCheck] | None | UnsetType = UNSET
    """Checks that run on this asset."""

    application: RelatedApplication | None | UnsetType = UNSET
    """Application owning the Asset."""

    application_field: RelatedApplicationField | None | UnsetType = UNSET
    """ApplicationField owning the Asset."""

    output_port_data_products: list[RelatedDataProduct] | None | UnsetType = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: list[RelatedDataProduct] | None | UnsetType = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: list[RelatedModelEntity] | None | UnsetType = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: list[RelatedModelAttribute] | None | UnsetType = UNSET
    """Attributes implemented by this asset."""

    metrics: list[RelatedMetric] | None | UnsetType = UNSET
    """"""

    dq_base_dataset_rules: list[RelatedDataQualityRule] | None | UnsetType = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: list[RelatedDataQualityRule] | None | UnsetType = UNSET
    """Rules where this dataset is referenced."""

    meanings: list[RelatedAtlasGlossaryTerm] | None | UnsetType = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: list[RelatedMCMonitor] | None | UnsetType = UNSET
    """Monitors that observe this asset."""

    mc_incidents: list[RelatedMCIncident] | None | UnsetType = UNSET
    """"""

    partial_child_fields: list[RelatedPartialField] | None | UnsetType = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: list[RelatedPartialObject] | None | UnsetType = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: list[RelatedProcess] | None | UnsetType = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: list[RelatedProcess] | None | UnsetType = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: list[RelatedReferenceable] | None | UnsetType = UNSET
    """"""

    user_def_relationship_from: list[RelatedReferenceable] | None | UnsetType = UNSET
    """"""

    files: list[RelatedFile] | None | UnsetType = UNSET
    """"""

    links: list[RelatedLink] | None | UnsetType = UNSET
    """Links that are attached to this asset."""

    readme: RelatedReadme | None | UnsetType = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: list[RelatedSchemaRegistrySubject] | None | UnsetType = (
        UNSET
    )
    """"""

    semantic_model: RelatedSemanticModel | None | UnsetType = UNSET
    """Semantic model in which this dimension exists."""

    soda_checks: list[RelatedSodaCheck] | None | UnsetType = UNSET
    """"""

    input_to_spark_jobs: list[RelatedSparkJob] | None | UnsetType = UNSET
    """"""

    output_from_spark_jobs: list[RelatedSparkJob] | None | UnsetType = UNSET
    """"""

    def __post_init__(self) -> None:
        self.type_name = "DbtDimension"

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return self.to_nested_bytes(serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    def to_nested_bytes(self, serde: Serde | None = None) -> bytes:
        """Serialize to Atlas nested-format JSON bytes (pure msgspec, no dict intermediate)."""
        if serde is None:
            serde = get_serde()
        return _dbt_dimension_to_nested_bytes(self, serde)

    @staticmethod
    def from_json(json_data: str | bytes, serde: Serde | None = None) -> DbtDimension:
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            DbtDimension instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _dbt_dimension_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class DbtDimensionAttributes(AssetAttributes):
    """DbtDimension-specific attributes for nested API format."""

    dbt_semantic_model_qualified_name: str | None | UnsetType = UNSET
    """Qualified name of the dbt semantic model this dimension belongs to."""

    dbt_semantic_field_time_granularity: str | None | UnsetType = UNSET
    """Time granularity for time dimensions only (day/week/month/quarter/year)."""

    dbt_alias: str | None | UnsetType = UNSET
    """Alias of this asset in dbt."""

    dbt_meta: str | None | UnsetType = UNSET
    """Metadata for this asset in dbt, specifically everything under the 'meta' key in the dbt object."""

    dbt_unique_id: str | None | UnsetType = UNSET
    """Unique identifier of this asset in dbt."""

    dbt_account_name: str | None | UnsetType = UNSET
    """Name of the account in which this asset exists in dbt."""

    dbt_project_name: str | None | UnsetType = UNSET
    """Name of the project in which this asset exists in dbt."""

    dbt_package_name: str | None | UnsetType = UNSET
    """Name of the package in which this asset exists in dbt."""

    dbt_job_name: str | None | UnsetType = UNSET
    """Name of the job that materialized this asset in dbt."""

    dbt_job_schedule: str | None | UnsetType = UNSET
    """Schedule of the job that materialized this asset in dbt."""

    dbt_job_status: str | None | UnsetType = UNSET
    """Status of the job that materialized this asset in dbt."""

    dbt_job_schedule_cron_humanized: str | None | UnsetType = UNSET
    """Human-readable cron schedule of the job that materialized this asset in dbt."""

    dbt_job_last_run: int | None | UnsetType = UNSET
    """Time (epoch) at which the job that materialized this asset in dbt last ran, in milliseconds."""

    dbt_job_next_run: int | None | UnsetType = UNSET
    """Time (epoch) at which the job that materialized this asset in dbt will next run, in milliseconds."""

    dbt_job_next_run_humanized: str | None | UnsetType = UNSET
    """Human-readable time at which the job that materialized this asset in dbt will next run."""

    dbt_environment_name: str | None | UnsetType = UNSET
    """Name of the environment in which this asset exists in dbt."""

    dbt_environment_dbt_version: str | None | UnsetType = UNSET
    """Version of dbt used in the environment."""

    dbt_tags: list[str] | None | UnsetType = UNSET
    """List of tags attached to this asset in dbt."""

    dbt_connection_context: str | None | UnsetType = UNSET
    """Connection context for this asset in dbt."""

    dbt_semantic_layer_proxy_url: str | None | UnsetType = UNSET
    """URL of the semantic layer proxy for this asset in dbt."""

    dbt_job_runs: list[dict[str, Any]] | None | UnsetType = UNSET
    """List of latest dbt job runs across all environments."""

    semantic_expression: str | None | UnsetType = UNSET
    """Column name or SQL expression for the semantic field."""

    semantic_type: str | None | UnsetType = UNSET
    """Detailed type of the semantic field (e.g., type of measure, type of dimension, or type of entity)."""


class DbtDimensionRelationshipAttributes(AssetRelationshipAttributes):
    """DbtDimension-specific relationship attributes for nested API format."""

    input_to_airflow_tasks: list[RelatedAirflowTask] | None | UnsetType = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: list[RelatedAirflowTask] | None | UnsetType = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: list[RelatedAnomaloCheck] | None | UnsetType = UNSET
    """Checks that run on this asset."""

    application: RelatedApplication | None | UnsetType = UNSET
    """Application owning the Asset."""

    application_field: RelatedApplicationField | None | UnsetType = UNSET
    """ApplicationField owning the Asset."""

    output_port_data_products: list[RelatedDataProduct] | None | UnsetType = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: list[RelatedDataProduct] | None | UnsetType = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: list[RelatedModelEntity] | None | UnsetType = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: list[RelatedModelAttribute] | None | UnsetType = UNSET
    """Attributes implemented by this asset."""

    metrics: list[RelatedMetric] | None | UnsetType = UNSET
    """"""

    dq_base_dataset_rules: list[RelatedDataQualityRule] | None | UnsetType = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: list[RelatedDataQualityRule] | None | UnsetType = UNSET
    """Rules where this dataset is referenced."""

    meanings: list[RelatedAtlasGlossaryTerm] | None | UnsetType = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: list[RelatedMCMonitor] | None | UnsetType = UNSET
    """Monitors that observe this asset."""

    mc_incidents: list[RelatedMCIncident] | None | UnsetType = UNSET
    """"""

    partial_child_fields: list[RelatedPartialField] | None | UnsetType = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: list[RelatedPartialObject] | None | UnsetType = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: list[RelatedProcess] | None | UnsetType = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: list[RelatedProcess] | None | UnsetType = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: list[RelatedReferenceable] | None | UnsetType = UNSET
    """"""

    user_def_relationship_from: list[RelatedReferenceable] | None | UnsetType = UNSET
    """"""

    files: list[RelatedFile] | None | UnsetType = UNSET
    """"""

    links: list[RelatedLink] | None | UnsetType = UNSET
    """Links that are attached to this asset."""

    readme: RelatedReadme | None | UnsetType = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: list[RelatedSchemaRegistrySubject] | None | UnsetType = (
        UNSET
    )
    """"""

    semantic_model: RelatedSemanticModel | None | UnsetType = UNSET
    """Semantic model in which this dimension exists."""

    soda_checks: list[RelatedSodaCheck] | None | UnsetType = UNSET
    """"""

    input_to_spark_jobs: list[RelatedSparkJob] | None | UnsetType = UNSET
    """"""

    output_from_spark_jobs: list[RelatedSparkJob] | None | UnsetType = UNSET
    """"""


class DbtDimensionNested(AssetNested):
    """DbtDimension in nested API format for high-performance serialization."""

    attributes: DbtDimensionAttributes | UnsetType = UNSET
    relationship_attributes: DbtDimensionRelationshipAttributes | UnsetType = UNSET
    append_relationship_attributes: DbtDimensionRelationshipAttributes | UnsetType = (
        UNSET
    )
    remove_relationship_attributes: DbtDimensionRelationshipAttributes | UnsetType = (
        UNSET
    )


# =============================================================================
# CONVERSION HELPERS & CONSTANTS
# =============================================================================

_DBT_DIMENSION_REL_FIELDS: list[str] = [
    *_ASSET_REL_FIELDS,
    "input_to_airflow_tasks",
    "output_from_airflow_tasks",
    "anomalo_checks",
    "application",
    "application_field",
    "output_port_data_products",
    "input_port_data_products",
    "model_implemented_entities",
    "model_implemented_attributes",
    "metrics",
    "dq_base_dataset_rules",
    "dq_reference_dataset_rules",
    "meanings",
    "mc_monitors",
    "mc_incidents",
    "partial_child_fields",
    "partial_child_objects",
    "input_to_processes",
    "output_from_processes",
    "user_def_relationship_to",
    "user_def_relationship_from",
    "files",
    "links",
    "readme",
    "schema_registry_subjects",
    "semantic_model",
    "soda_checks",
    "input_to_spark_jobs",
    "output_from_spark_jobs",
]


def _populate_dbt_dimension_attrs(
    attrs: DbtDimensionAttributes, obj: DbtDimension
) -> None:
    """Populate DbtDimension-specific attributes on the attrs struct."""
    _populate_asset_attrs(attrs, obj)
    attrs.dbt_semantic_model_qualified_name = obj.dbt_semantic_model_qualified_name
    attrs.dbt_semantic_field_time_granularity = obj.dbt_semantic_field_time_granularity
    attrs.dbt_alias = obj.dbt_alias
    attrs.dbt_meta = obj.dbt_meta
    attrs.dbt_unique_id = obj.dbt_unique_id
    attrs.dbt_account_name = obj.dbt_account_name
    attrs.dbt_project_name = obj.dbt_project_name
    attrs.dbt_package_name = obj.dbt_package_name
    attrs.dbt_job_name = obj.dbt_job_name
    attrs.dbt_job_schedule = obj.dbt_job_schedule
    attrs.dbt_job_status = obj.dbt_job_status
    attrs.dbt_job_schedule_cron_humanized = obj.dbt_job_schedule_cron_humanized
    attrs.dbt_job_last_run = obj.dbt_job_last_run
    attrs.dbt_job_next_run = obj.dbt_job_next_run
    attrs.dbt_job_next_run_humanized = obj.dbt_job_next_run_humanized
    attrs.dbt_environment_name = obj.dbt_environment_name
    attrs.dbt_environment_dbt_version = obj.dbt_environment_dbt_version
    attrs.dbt_tags = obj.dbt_tags
    attrs.dbt_connection_context = obj.dbt_connection_context
    attrs.dbt_semantic_layer_proxy_url = obj.dbt_semantic_layer_proxy_url
    attrs.dbt_job_runs = obj.dbt_job_runs
    attrs.semantic_expression = obj.semantic_expression
    attrs.semantic_type = obj.semantic_type


def _extract_dbt_dimension_attrs(attrs: DbtDimensionAttributes) -> dict:
    """Extract all DbtDimension attributes from the attrs struct into a flat dict."""
    result = _extract_asset_attrs(attrs)
    result["dbt_semantic_model_qualified_name"] = (
        attrs.dbt_semantic_model_qualified_name
    )
    result["dbt_semantic_field_time_granularity"] = (
        attrs.dbt_semantic_field_time_granularity
    )
    result["dbt_alias"] = attrs.dbt_alias
    result["dbt_meta"] = attrs.dbt_meta
    result["dbt_unique_id"] = attrs.dbt_unique_id
    result["dbt_account_name"] = attrs.dbt_account_name
    result["dbt_project_name"] = attrs.dbt_project_name
    result["dbt_package_name"] = attrs.dbt_package_name
    result["dbt_job_name"] = attrs.dbt_job_name
    result["dbt_job_schedule"] = attrs.dbt_job_schedule
    result["dbt_job_status"] = attrs.dbt_job_status
    result["dbt_job_schedule_cron_humanized"] = attrs.dbt_job_schedule_cron_humanized
    result["dbt_job_last_run"] = attrs.dbt_job_last_run
    result["dbt_job_next_run"] = attrs.dbt_job_next_run
    result["dbt_job_next_run_humanized"] = attrs.dbt_job_next_run_humanized
    result["dbt_environment_name"] = attrs.dbt_environment_name
    result["dbt_environment_dbt_version"] = attrs.dbt_environment_dbt_version
    result["dbt_tags"] = attrs.dbt_tags
    result["dbt_connection_context"] = attrs.dbt_connection_context
    result["dbt_semantic_layer_proxy_url"] = attrs.dbt_semantic_layer_proxy_url
    result["dbt_job_runs"] = attrs.dbt_job_runs
    result["semantic_expression"] = attrs.semantic_expression
    result["semantic_type"] = attrs.semantic_type
    return result


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _dbt_dimension_to_nested(dbt_dimension: DbtDimension) -> DbtDimensionNested:
    """Convert flat DbtDimension to nested format."""
    attrs = DbtDimensionAttributes()
    _populate_dbt_dimension_attrs(attrs, dbt_dimension)
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    replace_rels, append_rels, remove_rels = categorize_relationships(
        dbt_dimension, _DBT_DIMENSION_REL_FIELDS, DbtDimensionRelationshipAttributes
    )
    return DbtDimensionNested(
        guid=dbt_dimension.guid,
        type_name=dbt_dimension.type_name,
        status=dbt_dimension.status,
        version=dbt_dimension.version,
        create_time=dbt_dimension.create_time,
        update_time=dbt_dimension.update_time,
        created_by=dbt_dimension.created_by,
        updated_by=dbt_dimension.updated_by,
        classifications=dbt_dimension.classifications,
        classification_names=dbt_dimension.classification_names,
        meanings=dbt_dimension.meanings,
        labels=dbt_dimension.labels,
        business_attributes=dbt_dimension.business_attributes,
        custom_attributes=dbt_dimension.custom_attributes,
        pending_tasks=dbt_dimension.pending_tasks,
        proxy=dbt_dimension.proxy,
        is_incomplete=dbt_dimension.is_incomplete,
        provenance_type=dbt_dimension.provenance_type,
        home_id=dbt_dimension.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _dbt_dimension_from_nested(nested: DbtDimensionNested) -> DbtDimension:
    """Convert nested format to flat DbtDimension."""
    attrs = (
        nested.attributes
        if nested.attributes is not UNSET
        else DbtDimensionAttributes()
    )
    # Merge relationships from all three buckets
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        _DBT_DIMENSION_REL_FIELDS,
        DbtDimensionRelationshipAttributes,
    )
    return DbtDimension(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        **_extract_dbt_dimension_attrs(attrs),
        # Merged relationship attributes
        **merged_rels,
    )


def _dbt_dimension_to_nested_bytes(dbt_dimension: DbtDimension, serde: Serde) -> bytes:
    """Convert flat DbtDimension to nested JSON bytes."""
    return serde.encode(_dbt_dimension_to_nested(dbt_dimension))


def _dbt_dimension_from_nested_bytes(data: bytes, serde: Serde) -> DbtDimension:
    """Convert nested JSON bytes to flat DbtDimension."""
    nested = serde.decode(data, DbtDimensionNested)
    return _dbt_dimension_from_nested(nested)


# ---------------------------------------------------------------------------
# Deferred field descriptor initialization
# ---------------------------------------------------------------------------
from pyatlan.model.fields.atlan_fields import (  # noqa: E402
    KeywordField,
    NumericField,
    RelationField,
)

DbtDimension.DBT_SEMANTIC_MODEL_QUALIFIED_NAME = KeywordField(
    "dbtSemanticModelQualifiedName", "dbtSemanticModelQualifiedName"
)
DbtDimension.DBT_SEMANTIC_FIELD_TIME_GRANULARITY = KeywordField(
    "dbtSemanticFieldTimeGranularity", "dbtSemanticFieldTimeGranularity"
)
DbtDimension.DBT_ALIAS = KeywordField("dbtAlias", "dbtAlias")
DbtDimension.DBT_META = KeywordField("dbtMeta", "dbtMeta")
DbtDimension.DBT_UNIQUE_ID = KeywordField("dbtUniqueId", "dbtUniqueId")
DbtDimension.DBT_ACCOUNT_NAME = KeywordField("dbtAccountName", "dbtAccountName")
DbtDimension.DBT_PROJECT_NAME = KeywordField("dbtProjectName", "dbtProjectName")
DbtDimension.DBT_PACKAGE_NAME = KeywordField("dbtPackageName", "dbtPackageName")
DbtDimension.DBT_JOB_NAME = KeywordField("dbtJobName", "dbtJobName")
DbtDimension.DBT_JOB_SCHEDULE = KeywordField("dbtJobSchedule", "dbtJobSchedule")
DbtDimension.DBT_JOB_STATUS = KeywordField("dbtJobStatus", "dbtJobStatus")
DbtDimension.DBT_JOB_SCHEDULE_CRON_HUMANIZED = KeywordField(
    "dbtJobScheduleCronHumanized", "dbtJobScheduleCronHumanized"
)
DbtDimension.DBT_JOB_LAST_RUN = NumericField("dbtJobLastRun", "dbtJobLastRun")
DbtDimension.DBT_JOB_NEXT_RUN = NumericField("dbtJobNextRun", "dbtJobNextRun")
DbtDimension.DBT_JOB_NEXT_RUN_HUMANIZED = KeywordField(
    "dbtJobNextRunHumanized", "dbtJobNextRunHumanized"
)
DbtDimension.DBT_ENVIRONMENT_NAME = KeywordField(
    "dbtEnvironmentName", "dbtEnvironmentName"
)
DbtDimension.DBT_ENVIRONMENT_DBT_VERSION = KeywordField(
    "dbtEnvironmentDbtVersion", "dbtEnvironmentDbtVersion"
)
DbtDimension.DBT_TAGS = KeywordField("dbtTags", "dbtTags")
DbtDimension.DBT_CONNECTION_CONTEXT = KeywordField(
    "dbtConnectionContext", "dbtConnectionContext"
)
DbtDimension.DBT_SEMANTIC_LAYER_PROXY_URL = KeywordField(
    "dbtSemanticLayerProxyUrl", "dbtSemanticLayerProxyUrl"
)
DbtDimension.DBT_JOB_RUNS = KeywordField("dbtJobRuns", "dbtJobRuns")
DbtDimension.SEMANTIC_EXPRESSION = KeywordField(
    "semanticExpression", "semanticExpression"
)
DbtDimension.SEMANTIC_TYPE = KeywordField("semanticType", "semanticType")
DbtDimension.INPUT_TO_AIRFLOW_TASKS = RelationField("inputToAirflowTasks")
DbtDimension.OUTPUT_FROM_AIRFLOW_TASKS = RelationField("outputFromAirflowTasks")
DbtDimension.ANOMALO_CHECKS = RelationField("anomaloChecks")
DbtDimension.APPLICATION = RelationField("application")
DbtDimension.APPLICATION_FIELD = RelationField("applicationField")
DbtDimension.OUTPUT_PORT_DATA_PRODUCTS = RelationField("outputPortDataProducts")
DbtDimension.INPUT_PORT_DATA_PRODUCTS = RelationField("inputPortDataProducts")
DbtDimension.MODEL_IMPLEMENTED_ENTITIES = RelationField("modelImplementedEntities")
DbtDimension.MODEL_IMPLEMENTED_ATTRIBUTES = RelationField("modelImplementedAttributes")
DbtDimension.METRICS = RelationField("metrics")
DbtDimension.DQ_BASE_DATASET_RULES = RelationField("dqBaseDatasetRules")
DbtDimension.DQ_REFERENCE_DATASET_RULES = RelationField("dqReferenceDatasetRules")
DbtDimension.MEANINGS = RelationField("meanings")
DbtDimension.MC_MONITORS = RelationField("mcMonitors")
DbtDimension.MC_INCIDENTS = RelationField("mcIncidents")
DbtDimension.PARTIAL_CHILD_FIELDS = RelationField("partialChildFields")
DbtDimension.PARTIAL_CHILD_OBJECTS = RelationField("partialChildObjects")
DbtDimension.INPUT_TO_PROCESSES = RelationField("inputToProcesses")
DbtDimension.OUTPUT_FROM_PROCESSES = RelationField("outputFromProcesses")
DbtDimension.USER_DEF_RELATIONSHIP_TO = RelationField("userDefRelationshipTo")
DbtDimension.USER_DEF_RELATIONSHIP_FROM = RelationField("userDefRelationshipFrom")
DbtDimension.FILES = RelationField("files")
DbtDimension.LINKS = RelationField("links")
DbtDimension.README = RelationField("readme")
DbtDimension.SCHEMA_REGISTRY_SUBJECTS = RelationField("schemaRegistrySubjects")
DbtDimension.SEMANTIC_MODEL = RelationField("semanticModel")
DbtDimension.SODA_CHECKS = RelationField("sodaChecks")
DbtDimension.INPUT_TO_SPARK_JOBS = RelationField("inputToSparkJobs")
DbtDimension.OUTPUT_FROM_SPARK_JOBS = RelationField("outputFromSparkJobs")
