# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
Fabric asset model with flattened inheritance.

This module provides:
- Fabric: Flat asset class (easy to use)
- FabricAttributes: Nested attributes struct (extends AssetAttributes)
- FabricNested: Nested API format struct
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.model.conversion_utils import (
    categorize_relationships,
    merge_relationships,
)
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset

from .asset import Asset, AssetAttributes, AssetNested, AssetRelationshipAttributes

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class Fabric(Asset):
    """
    Base class for all Fabric types.
    """

    # Override type_name with Fabric-specific default
    type_name: Union[str, UnsetType] = "Fabric"

    fabric_column_count: Union[int, None, UnsetType] = UNSET
    """Number of columns in this asset."""

    fabric_data_type: Union[str, None, UnsetType] = UNSET
    """Data type of this asset."""

    fabric_ordinal: Union[int, None, UnsetType] = UNSET
    """Order/position of this asset within its parent."""

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return _fabric_to_nested_bytes(self, serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    @staticmethod
    def from_json(json_data: Union[str, bytes], serde: Serde | None = None) -> "Fabric":
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            Fabric instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _fabric_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class FabricAttributes(AssetAttributes):
    """Fabric-specific attributes for nested API format."""

    fabric_column_count: Union[int, None, UnsetType] = UNSET
    """Number of columns in this asset."""

    fabric_data_type: Union[str, None, UnsetType] = UNSET
    """Data type of this asset."""

    fabric_ordinal: Union[int, None, UnsetType] = UNSET
    """Order/position of this asset within its parent."""


class FabricRelationshipAttributes(AssetRelationshipAttributes):
    """Fabric-specific relationship attributes for nested API format."""

    pass


class FabricNested(AssetNested):
    """Fabric in nested API format for high-performance serialization."""

    attributes: Union[FabricAttributes, UnsetType] = UNSET
    relationship_attributes: Union[FabricRelationshipAttributes, UnsetType] = UNSET
    append_relationship_attributes: Union[FabricRelationshipAttributes, UnsetType] = (
        UNSET
    )
    remove_relationship_attributes: Union[FabricRelationshipAttributes, UnsetType] = (
        UNSET
    )


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _fabric_to_nested(fabric: Fabric) -> FabricNested:
    """Convert flat Fabric to nested format."""
    attrs = FabricAttributes(
        fabric_column_count=fabric.fabric_column_count,
        fabric_data_type=fabric.fabric_data_type,
        fabric_ordinal=fabric.fabric_ordinal,
    )
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    rel_fields: list[str] = []
    replace_rels, append_rels, remove_rels = categorize_relationships(
        fabric, rel_fields, FabricRelationshipAttributes
    )
    return FabricNested(
        guid=fabric.guid,
        type_name=fabric.type_name,
        status=fabric.status,
        version=fabric.version,
        create_time=fabric.create_time,
        update_time=fabric.update_time,
        created_by=fabric.created_by,
        updated_by=fabric.updated_by,
        classifications=fabric.classifications,
        classification_names=fabric.classification_names,
        meanings=fabric.meanings,
        labels=fabric.labels,
        business_attributes=fabric.business_attributes,
        custom_attributes=fabric.custom_attributes,
        pending_tasks=fabric.pending_tasks,
        proxy=fabric.proxy,
        is_incomplete=fabric.is_incomplete,
        provenance_type=fabric.provenance_type,
        home_id=fabric.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _fabric_from_nested(nested: FabricNested) -> Fabric:
    """Convert nested format to flat Fabric."""
    attrs = nested.attributes if nested.attributes is not UNSET else FabricAttributes()
    # Merge relationships from all three buckets
    rel_fields: list[str] = []
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        rel_fields,
        FabricRelationshipAttributes,
    )
    return Fabric(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        fabric_column_count=attrs.fabric_column_count,
        fabric_data_type=attrs.fabric_data_type,
        fabric_ordinal=attrs.fabric_ordinal,
        # Merged relationship attributes
        **merged_rels,
    )


def _fabric_to_nested_bytes(fabric: Fabric, serde: Serde) -> bytes:
    """Convert flat Fabric to nested JSON bytes."""
    return serde.encode(_fabric_to_nested(fabric))


def _fabric_from_nested_bytes(data: bytes, serde: Serde) -> Fabric:
    """Convert nested JSON bytes to flat Fabric."""
    nested = serde.decode(data, FabricNested)
    return _fabric_from_nested(nested)
