# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# ruff: noqa: ARG002
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
FabricDataPipeline asset model with flattened inheritance.

This module provides:
- FabricDataPipeline: Flat asset class (easy to use)
- FabricDataPipelineAttributes: Nested attributes struct (extends AssetAttributes)
- FabricDataPipelineNested: Nested API format struct
"""

from __future__ import annotations

import re
from typing import Any, ClassVar, List, Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.model.conversion_utils import (
    categorize_relationships,
    merge_relationships,
)
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset

from .airflow_related import RelatedAirflowTask
from .anomalo_related import RelatedAnomaloCheck
from .app_related import RelatedApplication, RelatedApplicationField
from .asset import (
    _ASSET_REL_FIELDS,
    Asset,
    AssetAttributes,
    AssetNested,
    AssetRelationshipAttributes,
    _extract_asset_attrs,
    _populate_asset_attrs,
)
from .data_contract_related import RelatedDataContract
from .data_mesh_related import RelatedDataProduct
from .data_quality_related import RelatedDataQualityRule, RelatedMetric
from .fabric_related import RelatedFabricActivity, RelatedFabricWorkspace
from .gtc_related import RelatedAtlasGlossaryTerm
from .model_related import RelatedModelAttribute, RelatedModelEntity
from .monte_carlo_related import RelatedMCIncident, RelatedMCMonitor
from .partial_related import RelatedPartialField, RelatedPartialObject
from .process_related import RelatedProcess
from .referenceable_related import RelatedReferenceable
from .resource_related import RelatedFile, RelatedLink, RelatedReadme
from .schema_registry_related import RelatedSchemaRegistrySubject
from .soda_related import RelatedSodaCheck
from .spark_related import RelatedSparkJob

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class FabricDataPipeline(Asset):
    """
    Instance of a Microsoft Fabric data pipeline in Atlan.
    """

    FABRIC_COLUMN_COUNT: ClassVar[Any] = None
    FABRIC_DATA_TYPE: ClassVar[Any] = None
    FABRIC_ORDINAL: ClassVar[Any] = None
    INPUT_TO_AIRFLOW_TASKS: ClassVar[Any] = None
    OUTPUT_FROM_AIRFLOW_TASKS: ClassVar[Any] = None
    ANOMALO_CHECKS: ClassVar[Any] = None
    APPLICATION: ClassVar[Any] = None
    APPLICATION_FIELD: ClassVar[Any] = None
    DATA_CONTRACT_LATEST: ClassVar[Any] = None
    DATA_CONTRACT_LATEST_CERTIFIED: ClassVar[Any] = None
    OUTPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    INPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ENTITIES: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ATTRIBUTES: ClassVar[Any] = None
    METRICS: ClassVar[Any] = None
    DQ_BASE_DATASET_RULES: ClassVar[Any] = None
    DQ_REFERENCE_DATASET_RULES: ClassVar[Any] = None
    FABRIC_WORKSPACE: ClassVar[Any] = None
    FABRIC_ACTIVITIES: ClassVar[Any] = None
    MEANINGS: ClassVar[Any] = None
    MC_MONITORS: ClassVar[Any] = None
    MC_INCIDENTS: ClassVar[Any] = None
    PARTIAL_CHILD_FIELDS: ClassVar[Any] = None
    PARTIAL_CHILD_OBJECTS: ClassVar[Any] = None
    INPUT_TO_PROCESSES: ClassVar[Any] = None
    OUTPUT_FROM_PROCESSES: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_TO: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_FROM: ClassVar[Any] = None
    FILES: ClassVar[Any] = None
    LINKS: ClassVar[Any] = None
    README: ClassVar[Any] = None
    SCHEMA_REGISTRY_SUBJECTS: ClassVar[Any] = None
    SODA_CHECKS: ClassVar[Any] = None
    INPUT_TO_SPARK_JOBS: ClassVar[Any] = None
    OUTPUT_FROM_SPARK_JOBS: ClassVar[Any] = None

    type_name: Union[str, UnsetType] = "FabricDataPipeline"

    fabric_column_count: Union[int, None, UnsetType] = UNSET
    """Number of columns in this asset."""

    fabric_data_type: Union[str, None, UnsetType] = UNSET
    """Data type of this asset."""

    fabric_ordinal: Union[int, None, UnsetType] = UNSET
    """Order/position of this asset within its parent."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    data_contract_latest: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest version of the data contract (in any status) for this asset."""

    data_contract_latest_certified: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest certified version of the data contract for this asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[
        List[RelatedModelAttribute], None, UnsetType
    ] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    fabric_workspace: Union[RelatedFabricWorkspace, None, UnsetType] = UNSET
    """Workspace containing the data pipeline."""

    fabric_activities: Union[List[RelatedFabricActivity], None, UnsetType] = UNSET
    """Individual activities contained in the data pipeline."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """Schema registry subjects associated with this asset."""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        self.type_name = "FabricDataPipeline"

    # =========================================================================
    # SDK Methods
    # =========================================================================

    _QUALIFIED_NAME_PATTERN: ClassVar[re.Pattern] = re.compile(r"^.+/[^/]+/[^/]+$")

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return self.to_nested_bytes(serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    def to_nested_bytes(self, serde: Serde | None = None) -> bytes:
        """Serialize to Atlas nested-format JSON bytes (pure msgspec, no dict intermediate)."""
        if serde is None:
            serde = get_serde()
        return _fabric_data_pipeline_to_nested_bytes(self, serde)

    @staticmethod
    def from_json(
        json_data: str | bytes, serde: Serde | None = None
    ) -> FabricDataPipeline:
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            FabricDataPipeline instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _fabric_data_pipeline_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class FabricDataPipelineAttributes(AssetAttributes):
    """FabricDataPipeline-specific attributes for nested API format."""

    fabric_column_count: Union[int, None, UnsetType] = UNSET
    """Number of columns in this asset."""

    fabric_data_type: Union[str, None, UnsetType] = UNSET
    """Data type of this asset."""

    fabric_ordinal: Union[int, None, UnsetType] = UNSET
    """Order/position of this asset within its parent."""


class FabricDataPipelineRelationshipAttributes(AssetRelationshipAttributes):
    """FabricDataPipeline-specific relationship attributes for nested API format."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    data_contract_latest: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest version of the data contract (in any status) for this asset."""

    data_contract_latest_certified: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest certified version of the data contract for this asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[
        List[RelatedModelAttribute], None, UnsetType
    ] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    fabric_workspace: Union[RelatedFabricWorkspace, None, UnsetType] = UNSET
    """Workspace containing the data pipeline."""

    fabric_activities: Union[List[RelatedFabricActivity], None, UnsetType] = UNSET
    """Individual activities contained in the data pipeline."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """Schema registry subjects associated with this asset."""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""


class FabricDataPipelineNested(AssetNested):
    """FabricDataPipeline in nested API format for high-performance serialization."""

    attributes: Union[FabricDataPipelineAttributes, UnsetType] = UNSET
    relationship_attributes: Union[
        FabricDataPipelineRelationshipAttributes, UnsetType
    ] = UNSET
    append_relationship_attributes: Union[
        FabricDataPipelineRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        FabricDataPipelineRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION HELPERS & CONSTANTS
# =============================================================================

_FABRIC_DATA_PIPELINE_REL_FIELDS: List[str] = [
    *_ASSET_REL_FIELDS,
    "input_to_airflow_tasks",
    "output_from_airflow_tasks",
    "anomalo_checks",
    "application",
    "application_field",
    "data_contract_latest",
    "data_contract_latest_certified",
    "output_port_data_products",
    "input_port_data_products",
    "model_implemented_entities",
    "model_implemented_attributes",
    "metrics",
    "dq_base_dataset_rules",
    "dq_reference_dataset_rules",
    "fabric_workspace",
    "fabric_activities",
    "meanings",
    "mc_monitors",
    "mc_incidents",
    "partial_child_fields",
    "partial_child_objects",
    "input_to_processes",
    "output_from_processes",
    "user_def_relationship_to",
    "user_def_relationship_from",
    "files",
    "links",
    "readme",
    "schema_registry_subjects",
    "soda_checks",
    "input_to_spark_jobs",
    "output_from_spark_jobs",
]


def _populate_fabric_data_pipeline_attrs(
    attrs: FabricDataPipelineAttributes, obj: FabricDataPipeline
) -> None:
    """Populate FabricDataPipeline-specific attributes on the attrs struct."""
    _populate_asset_attrs(attrs, obj)
    attrs.fabric_column_count = obj.fabric_column_count
    attrs.fabric_data_type = obj.fabric_data_type
    attrs.fabric_ordinal = obj.fabric_ordinal


def _extract_fabric_data_pipeline_attrs(attrs: FabricDataPipelineAttributes) -> dict:
    """Extract all FabricDataPipeline attributes from the attrs struct into a flat dict."""
    result = _extract_asset_attrs(attrs)
    result["fabric_column_count"] = attrs.fabric_column_count
    result["fabric_data_type"] = attrs.fabric_data_type
    result["fabric_ordinal"] = attrs.fabric_ordinal
    return result


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _fabric_data_pipeline_to_nested(
    fabric_data_pipeline: FabricDataPipeline,
) -> FabricDataPipelineNested:
    """Convert flat FabricDataPipeline to nested format."""
    attrs = FabricDataPipelineAttributes()
    _populate_fabric_data_pipeline_attrs(attrs, fabric_data_pipeline)
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    replace_rels, append_rels, remove_rels = categorize_relationships(
        fabric_data_pipeline,
        _FABRIC_DATA_PIPELINE_REL_FIELDS,
        FabricDataPipelineRelationshipAttributes,
    )
    return FabricDataPipelineNested(
        guid=fabric_data_pipeline.guid,
        type_name=fabric_data_pipeline.type_name,
        status=fabric_data_pipeline.status,
        version=fabric_data_pipeline.version,
        create_time=fabric_data_pipeline.create_time,
        update_time=fabric_data_pipeline.update_time,
        created_by=fabric_data_pipeline.created_by,
        updated_by=fabric_data_pipeline.updated_by,
        classifications=fabric_data_pipeline.classifications,
        classification_names=fabric_data_pipeline.classification_names,
        meanings=fabric_data_pipeline.meanings,
        labels=fabric_data_pipeline.labels,
        business_attributes=fabric_data_pipeline.business_attributes,
        custom_attributes=fabric_data_pipeline.custom_attributes,
        pending_tasks=fabric_data_pipeline.pending_tasks,
        proxy=fabric_data_pipeline.proxy,
        is_incomplete=fabric_data_pipeline.is_incomplete,
        provenance_type=fabric_data_pipeline.provenance_type,
        home_id=fabric_data_pipeline.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _fabric_data_pipeline_from_nested(
    nested: FabricDataPipelineNested,
) -> FabricDataPipeline:
    """Convert nested format to flat FabricDataPipeline."""
    attrs = (
        nested.attributes
        if nested.attributes is not UNSET
        else FabricDataPipelineAttributes()
    )
    # Merge relationships from all three buckets
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        _FABRIC_DATA_PIPELINE_REL_FIELDS,
        FabricDataPipelineRelationshipAttributes,
    )
    return FabricDataPipeline(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        **_extract_fabric_data_pipeline_attrs(attrs),
        # Merged relationship attributes
        **merged_rels,
    )


def _fabric_data_pipeline_to_nested_bytes(
    fabric_data_pipeline: FabricDataPipeline, serde: Serde
) -> bytes:
    """Convert flat FabricDataPipeline to nested JSON bytes."""
    return serde.encode(_fabric_data_pipeline_to_nested(fabric_data_pipeline))


def _fabric_data_pipeline_from_nested_bytes(
    data: bytes, serde: Serde
) -> FabricDataPipeline:
    """Convert nested JSON bytes to flat FabricDataPipeline."""
    nested = serde.decode(data, FabricDataPipelineNested)
    return _fabric_data_pipeline_from_nested(nested)


# ---------------------------------------------------------------------------
# Deferred field descriptor initialization
# ---------------------------------------------------------------------------
from pyatlan.model.fields.atlan_fields import (  # noqa: E402
    KeywordField,
    NumericField,
    RelationField,
)

FabricDataPipeline.FABRIC_COLUMN_COUNT = NumericField(
    "fabricColumnCount", "fabricColumnCount"
)
FabricDataPipeline.FABRIC_DATA_TYPE = KeywordField("fabricDataType", "fabricDataType")
FabricDataPipeline.FABRIC_ORDINAL = NumericField("fabricOrdinal", "fabricOrdinal")
FabricDataPipeline.INPUT_TO_AIRFLOW_TASKS = RelationField("inputToAirflowTasks")
FabricDataPipeline.OUTPUT_FROM_AIRFLOW_TASKS = RelationField("outputFromAirflowTasks")
FabricDataPipeline.ANOMALO_CHECKS = RelationField("anomaloChecks")
FabricDataPipeline.APPLICATION = RelationField("application")
FabricDataPipeline.APPLICATION_FIELD = RelationField("applicationField")
FabricDataPipeline.DATA_CONTRACT_LATEST = RelationField("dataContractLatest")
FabricDataPipeline.DATA_CONTRACT_LATEST_CERTIFIED = RelationField(
    "dataContractLatestCertified"
)
FabricDataPipeline.OUTPUT_PORT_DATA_PRODUCTS = RelationField("outputPortDataProducts")
FabricDataPipeline.INPUT_PORT_DATA_PRODUCTS = RelationField("inputPortDataProducts")
FabricDataPipeline.MODEL_IMPLEMENTED_ENTITIES = RelationField(
    "modelImplementedEntities"
)
FabricDataPipeline.MODEL_IMPLEMENTED_ATTRIBUTES = RelationField(
    "modelImplementedAttributes"
)
FabricDataPipeline.METRICS = RelationField("metrics")
FabricDataPipeline.DQ_BASE_DATASET_RULES = RelationField("dqBaseDatasetRules")
FabricDataPipeline.DQ_REFERENCE_DATASET_RULES = RelationField("dqReferenceDatasetRules")
FabricDataPipeline.FABRIC_WORKSPACE = RelationField("fabricWorkspace")
FabricDataPipeline.FABRIC_ACTIVITIES = RelationField("fabricActivities")
FabricDataPipeline.MEANINGS = RelationField("meanings")
FabricDataPipeline.MC_MONITORS = RelationField("mcMonitors")
FabricDataPipeline.MC_INCIDENTS = RelationField("mcIncidents")
FabricDataPipeline.PARTIAL_CHILD_FIELDS = RelationField("partialChildFields")
FabricDataPipeline.PARTIAL_CHILD_OBJECTS = RelationField("partialChildObjects")
FabricDataPipeline.INPUT_TO_PROCESSES = RelationField("inputToProcesses")
FabricDataPipeline.OUTPUT_FROM_PROCESSES = RelationField("outputFromProcesses")
FabricDataPipeline.USER_DEF_RELATIONSHIP_TO = RelationField("userDefRelationshipTo")
FabricDataPipeline.USER_DEF_RELATIONSHIP_FROM = RelationField("userDefRelationshipFrom")
FabricDataPipeline.FILES = RelationField("files")
FabricDataPipeline.LINKS = RelationField("links")
FabricDataPipeline.README = RelationField("readme")
FabricDataPipeline.SCHEMA_REGISTRY_SUBJECTS = RelationField("schemaRegistrySubjects")
FabricDataPipeline.SODA_CHECKS = RelationField("sodaChecks")
FabricDataPipeline.INPUT_TO_SPARK_JOBS = RelationField("inputToSparkJobs")
FabricDataPipeline.OUTPUT_FROM_SPARK_JOBS = RelationField("outputFromSparkJobs")
