# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# ruff: noqa: ARG002
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
GCSObject asset model with flattened inheritance.

This module provides:
- GCSObject: Flat asset class (easy to use)
- GCSObjectAttributes: Nested attributes struct (extends AssetAttributes)
- GCSObjectNested: Nested API format struct
"""

from __future__ import annotations

import re
from typing import Any, ClassVar, Dict, List, Union

import msgspec
from msgspec import UNSET, UnsetType

from pyatlan_v9.model.conversion_utils import (
    categorize_relationships,
    merge_relationships,
)
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset

from .airflow_related import RelatedAirflowTask
from .anomalo_related import RelatedAnomaloCheck
from .app_related import RelatedApplication, RelatedApplicationField
from .asset import (
    _ASSET_REL_FIELDS,
    Asset,
    AssetAttributes,
    AssetNested,
    AssetRelationshipAttributes,
    _extract_asset_attrs,
    _populate_asset_attrs,
)
from .data_mesh_related import RelatedDataProduct
from .data_quality_related import RelatedDataQualityRule, RelatedMetric
from .gcs_related import RelatedGCSBucket
from .gtc_related import RelatedAtlasGlossaryTerm
from .model_related import RelatedModelAttribute, RelatedModelEntity
from .monte_carlo_related import RelatedMCIncident, RelatedMCMonitor
from .partial_related import RelatedPartialField, RelatedPartialObject
from .process_related import RelatedProcess
from .referenceable_related import RelatedReferenceable
from .resource_related import RelatedFile, RelatedLink, RelatedReadme
from .schema_registry_related import RelatedSchemaRegistrySubject
from .soda_related import RelatedSodaCheck
from .spark_related import RelatedSparkJob

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class GCSObject(Asset):
    """
    Instance of a Google Cloud Storage object in Atlan.
    """

    GCS_BUCKET_NAME: ClassVar[Any] = None
    GCS_BUCKET_QUALIFIED_NAME: ClassVar[Any] = None
    GCS_OBJECT_SIZE: ClassVar[Any] = None
    GCS_OBJECT_KEY: ClassVar[Any] = None
    GCS_OBJECT_MEDIA_LINK: ClassVar[Any] = None
    GCS_OBJECT_HOLD_TYPE: ClassVar[Any] = None
    GCS_OBJECT_GENERATION_ID: ClassVar[Any] = None
    GCS_OBJECT_CRC32C_HASH: ClassVar[Any] = None
    GCS_OBJECT_MD5_HASH: ClassVar[Any] = None
    GCS_OBJECT_DATA_LAST_MODIFIED_TIME: ClassVar[Any] = None
    GCS_OBJECT_CONTENT_TYPE: ClassVar[Any] = None
    GCS_OBJECT_CONTENT_ENCODING: ClassVar[Any] = None
    GCS_OBJECT_CONTENT_DISPOSITION: ClassVar[Any] = None
    GCS_OBJECT_CONTENT_LANGUAGE: ClassVar[Any] = None
    GCS_OBJECT_RETENTION_EXPIRATION_DATE: ClassVar[Any] = None
    GCS_STORAGE_CLASS: ClassVar[Any] = None
    GCS_ENCRYPTION_TYPE: ClassVar[Any] = None
    GCS_ETAG: ClassVar[Any] = None
    GCS_REQUESTER_PAYS: ClassVar[Any] = None
    GCS_ACCESS_CONTROL: ClassVar[Any] = None
    GCS_META_GENERATION_ID: ClassVar[Any] = None
    GOOGLE_SERVICE: ClassVar[Any] = None
    GOOGLE_PROJECT_NAME: ClassVar[Any] = None
    GOOGLE_PROJECT_ID: ClassVar[Any] = None
    GOOGLE_PROJECT_NUMBER: ClassVar[Any] = None
    GOOGLE_LOCATION: ClassVar[Any] = None
    GOOGLE_LOCATION_TYPE: ClassVar[Any] = None
    GOOGLE_LABELS: ClassVar[Any] = None
    GOOGLE_TAGS: ClassVar[Any] = None
    CLOUD_UNIFORM_RESOURCE_NAME: ClassVar[Any] = None
    INPUT_TO_AIRFLOW_TASKS: ClassVar[Any] = None
    OUTPUT_FROM_AIRFLOW_TASKS: ClassVar[Any] = None
    ANOMALO_CHECKS: ClassVar[Any] = None
    APPLICATION: ClassVar[Any] = None
    APPLICATION_FIELD: ClassVar[Any] = None
    OUTPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    INPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ENTITIES: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ATTRIBUTES: ClassVar[Any] = None
    METRICS: ClassVar[Any] = None
    DQ_BASE_DATASET_RULES: ClassVar[Any] = None
    DQ_REFERENCE_DATASET_RULES: ClassVar[Any] = None
    GCS_BUCKET: ClassVar[Any] = None
    MEANINGS: ClassVar[Any] = None
    MC_MONITORS: ClassVar[Any] = None
    MC_INCIDENTS: ClassVar[Any] = None
    PARTIAL_CHILD_FIELDS: ClassVar[Any] = None
    PARTIAL_CHILD_OBJECTS: ClassVar[Any] = None
    INPUT_TO_PROCESSES: ClassVar[Any] = None
    OUTPUT_FROM_PROCESSES: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_TO: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_FROM: ClassVar[Any] = None
    FILES: ClassVar[Any] = None
    LINKS: ClassVar[Any] = None
    README: ClassVar[Any] = None
    SCHEMA_REGISTRY_SUBJECTS: ClassVar[Any] = None
    SODA_CHECKS: ClassVar[Any] = None
    INPUT_TO_SPARK_JOBS: ClassVar[Any] = None
    OUTPUT_FROM_SPARK_JOBS: ClassVar[Any] = None

    type_name: Union[str, UnsetType] = "GCSObject"

    gcs_bucket_name: Union[str, None, UnsetType] = UNSET
    """Simple name of the bucket in which this object exists."""

    gcs_bucket_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the bucket in which this object exists."""

    gcs_object_size: Union[int, None, UnsetType] = UNSET
    """Object size in bytes."""

    gcs_object_key: Union[str, None, UnsetType] = UNSET
    """Key of this object, in GCS."""

    gcs_object_media_link: Union[str, None, UnsetType] = UNSET
    """Media link to this object."""

    gcs_object_hold_type: Union[str, None, UnsetType] = UNSET
    """Type of hold on this object."""

    gcs_object_generation_id: Union[int, None, UnsetType] = UNSET
    """Generation ID of this object."""

    gcs_object_crc32c_hash: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="gcsObjectCRC32CHash"
    )
    """CRC32C hash of this object."""

    gcs_object_md5_hash: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="gcsObjectMD5Hash"
    )
    """MD5 hash of this object."""

    gcs_object_data_last_modified_time: Union[int, None, UnsetType] = UNSET
    """Time (epoch) at which this object's data was last modified, in milliseconds."""

    gcs_object_content_type: Union[str, None, UnsetType] = UNSET
    """Type of content in this object."""

    gcs_object_content_encoding: Union[str, None, UnsetType] = UNSET
    """Content encoding of this object."""

    gcs_object_content_disposition: Union[str, None, UnsetType] = UNSET
    """Information about how this object's content should be presented."""

    gcs_object_content_language: Union[str, None, UnsetType] = UNSET
    """Language of this object's contents."""

    gcs_object_retention_expiration_date: Union[int, None, UnsetType] = UNSET
    """Retention expiration date of this object."""

    gcs_storage_class: Union[str, None, UnsetType] = UNSET
    """Storage class of this asset."""

    gcs_encryption_type: Union[str, None, UnsetType] = UNSET
    """Encryption algorithm used to encrypt this asset."""

    gcs_etag: Union[str, None, UnsetType] = msgspec.field(default=UNSET, name="gcsETag")
    """Entity tag for the asset. An entity tag is a hash of the object and represents changes to the contents of an object only, not its metadata."""

    gcs_requester_pays: Union[bool, None, UnsetType] = UNSET
    """Whether the requester pays header was sent when this asset was created (true) or not (false)."""

    gcs_access_control: Union[str, None, UnsetType] = UNSET
    """Access control list for this asset."""

    gcs_meta_generation_id: Union[int, None, UnsetType] = UNSET
    """Version of metadata for this asset at this generation. Used for preconditions and detecting changes in metadata. A metageneration number is only meaningful in the context of a particular generation of a particular asset."""

    google_service: Union[str, None, UnsetType] = UNSET
    """Service in Google in which the asset exists."""

    google_project_name: Union[str, None, UnsetType] = UNSET
    """Name of the project in which the asset exists."""

    google_project_id: Union[str, None, UnsetType] = UNSET
    """ID of the project in which the asset exists."""

    google_project_number: Union[int, None, UnsetType] = UNSET
    """Number of the project in which the asset exists."""

    google_location: Union[str, None, UnsetType] = UNSET
    """Location of this asset in Google."""

    google_location_type: Union[str, None, UnsetType] = UNSET
    """Type of location of this asset in Google."""

    google_labels: Union[List[Dict[str, Any]], None, UnsetType] = UNSET
    """List of labels that have been applied to the asset in Google."""

    google_tags: Union[List[Dict[str, Any]], None, UnsetType] = UNSET
    """List of tags that have been applied to the asset in Google."""

    cloud_uniform_resource_name: Union[str, None, UnsetType] = UNSET
    """Uniform resource name (URN) for the asset: AWS ARN, Google Cloud URI, Azure resource ID, Oracle OCID, and so on."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[
        List[RelatedModelAttribute], None, UnsetType
    ] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    gcs_bucket: Union[RelatedGCSBucket, None, UnsetType] = UNSET
    """GCS bucket in which the object exists."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """"""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        self.type_name = "GCSObject"

    # =========================================================================
    # SDK Methods
    # =========================================================================

    _QUALIFIED_NAME_PATTERN: ClassVar[re.Pattern] = re.compile(r"^.+/[^/]+/[^/]+$")

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return self.to_nested_bytes(serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    def to_nested_bytes(self, serde: Serde | None = None) -> bytes:
        """Serialize to Atlas nested-format JSON bytes (pure msgspec, no dict intermediate)."""
        if serde is None:
            serde = get_serde()
        return _gcs_object_to_nested_bytes(self, serde)

    @staticmethod
    def from_json(json_data: str | bytes, serde: Serde | None = None) -> GCSObject:
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            GCSObject instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _gcs_object_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class GCSObjectAttributes(AssetAttributes):
    """GCSObject-specific attributes for nested API format."""

    gcs_bucket_name: Union[str, None, UnsetType] = UNSET
    """Simple name of the bucket in which this object exists."""

    gcs_bucket_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the bucket in which this object exists."""

    gcs_object_size: Union[int, None, UnsetType] = UNSET
    """Object size in bytes."""

    gcs_object_key: Union[str, None, UnsetType] = UNSET
    """Key of this object, in GCS."""

    gcs_object_media_link: Union[str, None, UnsetType] = UNSET
    """Media link to this object."""

    gcs_object_hold_type: Union[str, None, UnsetType] = UNSET
    """Type of hold on this object."""

    gcs_object_generation_id: Union[int, None, UnsetType] = UNSET
    """Generation ID of this object."""

    gcs_object_crc32c_hash: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="gcsObjectCRC32CHash"
    )
    """CRC32C hash of this object."""

    gcs_object_md5_hash: Union[str, None, UnsetType] = msgspec.field(
        default=UNSET, name="gcsObjectMD5Hash"
    )
    """MD5 hash of this object."""

    gcs_object_data_last_modified_time: Union[int, None, UnsetType] = UNSET
    """Time (epoch) at which this object's data was last modified, in milliseconds."""

    gcs_object_content_type: Union[str, None, UnsetType] = UNSET
    """Type of content in this object."""

    gcs_object_content_encoding: Union[str, None, UnsetType] = UNSET
    """Content encoding of this object."""

    gcs_object_content_disposition: Union[str, None, UnsetType] = UNSET
    """Information about how this object's content should be presented."""

    gcs_object_content_language: Union[str, None, UnsetType] = UNSET
    """Language of this object's contents."""

    gcs_object_retention_expiration_date: Union[int, None, UnsetType] = UNSET
    """Retention expiration date of this object."""

    gcs_storage_class: Union[str, None, UnsetType] = UNSET
    """Storage class of this asset."""

    gcs_encryption_type: Union[str, None, UnsetType] = UNSET
    """Encryption algorithm used to encrypt this asset."""

    gcs_etag: Union[str, None, UnsetType] = msgspec.field(default=UNSET, name="gcsETag")
    """Entity tag for the asset. An entity tag is a hash of the object and represents changes to the contents of an object only, not its metadata."""

    gcs_requester_pays: Union[bool, None, UnsetType] = UNSET
    """Whether the requester pays header was sent when this asset was created (true) or not (false)."""

    gcs_access_control: Union[str, None, UnsetType] = UNSET
    """Access control list for this asset."""

    gcs_meta_generation_id: Union[int, None, UnsetType] = UNSET
    """Version of metadata for this asset at this generation. Used for preconditions and detecting changes in metadata. A metageneration number is only meaningful in the context of a particular generation of a particular asset."""

    google_service: Union[str, None, UnsetType] = UNSET
    """Service in Google in which the asset exists."""

    google_project_name: Union[str, None, UnsetType] = UNSET
    """Name of the project in which the asset exists."""

    google_project_id: Union[str, None, UnsetType] = UNSET
    """ID of the project in which the asset exists."""

    google_project_number: Union[int, None, UnsetType] = UNSET
    """Number of the project in which the asset exists."""

    google_location: Union[str, None, UnsetType] = UNSET
    """Location of this asset in Google."""

    google_location_type: Union[str, None, UnsetType] = UNSET
    """Type of location of this asset in Google."""

    google_labels: Union[List[Dict[str, Any]], None, UnsetType] = UNSET
    """List of labels that have been applied to the asset in Google."""

    google_tags: Union[List[Dict[str, Any]], None, UnsetType] = UNSET
    """List of tags that have been applied to the asset in Google."""

    cloud_uniform_resource_name: Union[str, None, UnsetType] = UNSET
    """Uniform resource name (URN) for the asset: AWS ARN, Google Cloud URI, Azure resource ID, Oracle OCID, and so on."""


class GCSObjectRelationshipAttributes(AssetRelationshipAttributes):
    """GCSObject-specific relationship attributes for nested API format."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[
        List[RelatedModelAttribute], None, UnsetType
    ] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    gcs_bucket: Union[RelatedGCSBucket, None, UnsetType] = UNSET
    """GCS bucket in which the object exists."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """"""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""


class GCSObjectNested(AssetNested):
    """GCSObject in nested API format for high-performance serialization."""

    attributes: Union[GCSObjectAttributes, UnsetType] = UNSET
    relationship_attributes: Union[GCSObjectRelationshipAttributes, UnsetType] = UNSET
    append_relationship_attributes: Union[
        GCSObjectRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        GCSObjectRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION HELPERS & CONSTANTS
# =============================================================================

_GCS_OBJECT_REL_FIELDS: List[str] = [
    *_ASSET_REL_FIELDS,
    "input_to_airflow_tasks",
    "output_from_airflow_tasks",
    "anomalo_checks",
    "application",
    "application_field",
    "output_port_data_products",
    "input_port_data_products",
    "model_implemented_entities",
    "model_implemented_attributes",
    "metrics",
    "dq_base_dataset_rules",
    "dq_reference_dataset_rules",
    "gcs_bucket",
    "meanings",
    "mc_monitors",
    "mc_incidents",
    "partial_child_fields",
    "partial_child_objects",
    "input_to_processes",
    "output_from_processes",
    "user_def_relationship_to",
    "user_def_relationship_from",
    "files",
    "links",
    "readme",
    "schema_registry_subjects",
    "soda_checks",
    "input_to_spark_jobs",
    "output_from_spark_jobs",
]


def _populate_gcs_object_attrs(attrs: GCSObjectAttributes, obj: GCSObject) -> None:
    """Populate GCSObject-specific attributes on the attrs struct."""
    _populate_asset_attrs(attrs, obj)
    attrs.gcs_bucket_name = obj.gcs_bucket_name
    attrs.gcs_bucket_qualified_name = obj.gcs_bucket_qualified_name
    attrs.gcs_object_size = obj.gcs_object_size
    attrs.gcs_object_key = obj.gcs_object_key
    attrs.gcs_object_media_link = obj.gcs_object_media_link
    attrs.gcs_object_hold_type = obj.gcs_object_hold_type
    attrs.gcs_object_generation_id = obj.gcs_object_generation_id
    attrs.gcs_object_crc32c_hash = obj.gcs_object_crc32c_hash
    attrs.gcs_object_md5_hash = obj.gcs_object_md5_hash
    attrs.gcs_object_data_last_modified_time = obj.gcs_object_data_last_modified_time
    attrs.gcs_object_content_type = obj.gcs_object_content_type
    attrs.gcs_object_content_encoding = obj.gcs_object_content_encoding
    attrs.gcs_object_content_disposition = obj.gcs_object_content_disposition
    attrs.gcs_object_content_language = obj.gcs_object_content_language
    attrs.gcs_object_retention_expiration_date = (
        obj.gcs_object_retention_expiration_date
    )
    attrs.gcs_storage_class = obj.gcs_storage_class
    attrs.gcs_encryption_type = obj.gcs_encryption_type
    attrs.gcs_etag = obj.gcs_etag
    attrs.gcs_requester_pays = obj.gcs_requester_pays
    attrs.gcs_access_control = obj.gcs_access_control
    attrs.gcs_meta_generation_id = obj.gcs_meta_generation_id
    attrs.google_service = obj.google_service
    attrs.google_project_name = obj.google_project_name
    attrs.google_project_id = obj.google_project_id
    attrs.google_project_number = obj.google_project_number
    attrs.google_location = obj.google_location
    attrs.google_location_type = obj.google_location_type
    attrs.google_labels = obj.google_labels
    attrs.google_tags = obj.google_tags
    attrs.cloud_uniform_resource_name = obj.cloud_uniform_resource_name


def _extract_gcs_object_attrs(attrs: GCSObjectAttributes) -> dict:
    """Extract all GCSObject attributes from the attrs struct into a flat dict."""
    result = _extract_asset_attrs(attrs)
    result["gcs_bucket_name"] = attrs.gcs_bucket_name
    result["gcs_bucket_qualified_name"] = attrs.gcs_bucket_qualified_name
    result["gcs_object_size"] = attrs.gcs_object_size
    result["gcs_object_key"] = attrs.gcs_object_key
    result["gcs_object_media_link"] = attrs.gcs_object_media_link
    result["gcs_object_hold_type"] = attrs.gcs_object_hold_type
    result["gcs_object_generation_id"] = attrs.gcs_object_generation_id
    result["gcs_object_crc32c_hash"] = attrs.gcs_object_crc32c_hash
    result["gcs_object_md5_hash"] = attrs.gcs_object_md5_hash
    result["gcs_object_data_last_modified_time"] = (
        attrs.gcs_object_data_last_modified_time
    )
    result["gcs_object_content_type"] = attrs.gcs_object_content_type
    result["gcs_object_content_encoding"] = attrs.gcs_object_content_encoding
    result["gcs_object_content_disposition"] = attrs.gcs_object_content_disposition
    result["gcs_object_content_language"] = attrs.gcs_object_content_language
    result["gcs_object_retention_expiration_date"] = (
        attrs.gcs_object_retention_expiration_date
    )
    result["gcs_storage_class"] = attrs.gcs_storage_class
    result["gcs_encryption_type"] = attrs.gcs_encryption_type
    result["gcs_etag"] = attrs.gcs_etag
    result["gcs_requester_pays"] = attrs.gcs_requester_pays
    result["gcs_access_control"] = attrs.gcs_access_control
    result["gcs_meta_generation_id"] = attrs.gcs_meta_generation_id
    result["google_service"] = attrs.google_service
    result["google_project_name"] = attrs.google_project_name
    result["google_project_id"] = attrs.google_project_id
    result["google_project_number"] = attrs.google_project_number
    result["google_location"] = attrs.google_location
    result["google_location_type"] = attrs.google_location_type
    result["google_labels"] = attrs.google_labels
    result["google_tags"] = attrs.google_tags
    result["cloud_uniform_resource_name"] = attrs.cloud_uniform_resource_name
    return result


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _gcs_object_to_nested(gcs_object: GCSObject) -> GCSObjectNested:
    """Convert flat GCSObject to nested format."""
    attrs = GCSObjectAttributes()
    _populate_gcs_object_attrs(attrs, gcs_object)
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    replace_rels, append_rels, remove_rels = categorize_relationships(
        gcs_object, _GCS_OBJECT_REL_FIELDS, GCSObjectRelationshipAttributes
    )
    return GCSObjectNested(
        guid=gcs_object.guid,
        type_name=gcs_object.type_name,
        status=gcs_object.status,
        version=gcs_object.version,
        create_time=gcs_object.create_time,
        update_time=gcs_object.update_time,
        created_by=gcs_object.created_by,
        updated_by=gcs_object.updated_by,
        classifications=gcs_object.classifications,
        classification_names=gcs_object.classification_names,
        meanings=gcs_object.meanings,
        labels=gcs_object.labels,
        business_attributes=gcs_object.business_attributes,
        custom_attributes=gcs_object.custom_attributes,
        pending_tasks=gcs_object.pending_tasks,
        proxy=gcs_object.proxy,
        is_incomplete=gcs_object.is_incomplete,
        provenance_type=gcs_object.provenance_type,
        home_id=gcs_object.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _gcs_object_from_nested(nested: GCSObjectNested) -> GCSObject:
    """Convert nested format to flat GCSObject."""
    attrs = (
        nested.attributes if nested.attributes is not UNSET else GCSObjectAttributes()
    )
    # Merge relationships from all three buckets
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        _GCS_OBJECT_REL_FIELDS,
        GCSObjectRelationshipAttributes,
    )
    return GCSObject(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        **_extract_gcs_object_attrs(attrs),
        # Merged relationship attributes
        **merged_rels,
    )


def _gcs_object_to_nested_bytes(gcs_object: GCSObject, serde: Serde) -> bytes:
    """Convert flat GCSObject to nested JSON bytes."""
    return serde.encode(_gcs_object_to_nested(gcs_object))


def _gcs_object_from_nested_bytes(data: bytes, serde: Serde) -> GCSObject:
    """Convert nested JSON bytes to flat GCSObject."""
    nested = serde.decode(data, GCSObjectNested)
    return _gcs_object_from_nested(nested)


# ---------------------------------------------------------------------------
# Deferred field descriptor initialization
# ---------------------------------------------------------------------------
from pyatlan.model.fields.atlan_fields import (  # noqa: E402
    BooleanField,
    KeywordField,
    KeywordTextField,
    NumericField,
    RelationField,
)

GCSObject.GCS_BUCKET_NAME = KeywordField("gcsBucketName", "gcsBucketName")
GCSObject.GCS_BUCKET_QUALIFIED_NAME = KeywordTextField(
    "gcsBucketQualifiedName", "gcsBucketQualifiedName", "gcsBucketQualifiedName.text"
)
GCSObject.GCS_OBJECT_SIZE = NumericField("gcsObjectSize", "gcsObjectSize")
GCSObject.GCS_OBJECT_KEY = KeywordTextField(
    "gcsObjectKey", "gcsObjectKey", "gcsObjectKey.text"
)
GCSObject.GCS_OBJECT_MEDIA_LINK = KeywordTextField(
    "gcsObjectMediaLink", "gcsObjectMediaLink", "gcsObjectMediaLink.text"
)
GCSObject.GCS_OBJECT_HOLD_TYPE = KeywordField("gcsObjectHoldType", "gcsObjectHoldType")
GCSObject.GCS_OBJECT_GENERATION_ID = NumericField(
    "gcsObjectGenerationId", "gcsObjectGenerationId"
)
GCSObject.GCS_OBJECT_CRC32C_HASH = KeywordField(
    "gcsObjectCRC32CHash", "gcsObjectCRC32CHash"
)
GCSObject.GCS_OBJECT_MD5_HASH = KeywordField("gcsObjectMD5Hash", "gcsObjectMD5Hash")
GCSObject.GCS_OBJECT_DATA_LAST_MODIFIED_TIME = NumericField(
    "gcsObjectDataLastModifiedTime", "gcsObjectDataLastModifiedTime"
)
GCSObject.GCS_OBJECT_CONTENT_TYPE = KeywordField(
    "gcsObjectContentType", "gcsObjectContentType"
)
GCSObject.GCS_OBJECT_CONTENT_ENCODING = KeywordField(
    "gcsObjectContentEncoding", "gcsObjectContentEncoding"
)
GCSObject.GCS_OBJECT_CONTENT_DISPOSITION = KeywordField(
    "gcsObjectContentDisposition", "gcsObjectContentDisposition"
)
GCSObject.GCS_OBJECT_CONTENT_LANGUAGE = KeywordField(
    "gcsObjectContentLanguage", "gcsObjectContentLanguage"
)
GCSObject.GCS_OBJECT_RETENTION_EXPIRATION_DATE = NumericField(
    "gcsObjectRetentionExpirationDate", "gcsObjectRetentionExpirationDate"
)
GCSObject.GCS_STORAGE_CLASS = KeywordField("gcsStorageClass", "gcsStorageClass")
GCSObject.GCS_ENCRYPTION_TYPE = KeywordField("gcsEncryptionType", "gcsEncryptionType")
GCSObject.GCS_ETAG = KeywordField("gcsETag", "gcsETag")
GCSObject.GCS_REQUESTER_PAYS = BooleanField("gcsRequesterPays", "gcsRequesterPays")
GCSObject.GCS_ACCESS_CONTROL = KeywordField("gcsAccessControl", "gcsAccessControl")
GCSObject.GCS_META_GENERATION_ID = NumericField(
    "gcsMetaGenerationId", "gcsMetaGenerationId"
)
GCSObject.GOOGLE_SERVICE = KeywordField("googleService", "googleService")
GCSObject.GOOGLE_PROJECT_NAME = KeywordTextField(
    "googleProjectName", "googleProjectName", "googleProjectName.text"
)
GCSObject.GOOGLE_PROJECT_ID = KeywordTextField(
    "googleProjectId", "googleProjectId", "googleProjectId.text"
)
GCSObject.GOOGLE_PROJECT_NUMBER = NumericField(
    "googleProjectNumber", "googleProjectNumber"
)
GCSObject.GOOGLE_LOCATION = KeywordField("googleLocation", "googleLocation")
GCSObject.GOOGLE_LOCATION_TYPE = KeywordField(
    "googleLocationType", "googleLocationType"
)
GCSObject.GOOGLE_LABELS = KeywordField("googleLabels", "googleLabels")
GCSObject.GOOGLE_TAGS = KeywordField("googleTags", "googleTags")
GCSObject.CLOUD_UNIFORM_RESOURCE_NAME = KeywordField(
    "cloudUniformResourceName", "cloudUniformResourceName"
)
GCSObject.INPUT_TO_AIRFLOW_TASKS = RelationField("inputToAirflowTasks")
GCSObject.OUTPUT_FROM_AIRFLOW_TASKS = RelationField("outputFromAirflowTasks")
GCSObject.ANOMALO_CHECKS = RelationField("anomaloChecks")
GCSObject.APPLICATION = RelationField("application")
GCSObject.APPLICATION_FIELD = RelationField("applicationField")
GCSObject.OUTPUT_PORT_DATA_PRODUCTS = RelationField("outputPortDataProducts")
GCSObject.INPUT_PORT_DATA_PRODUCTS = RelationField("inputPortDataProducts")
GCSObject.MODEL_IMPLEMENTED_ENTITIES = RelationField("modelImplementedEntities")
GCSObject.MODEL_IMPLEMENTED_ATTRIBUTES = RelationField("modelImplementedAttributes")
GCSObject.METRICS = RelationField("metrics")
GCSObject.DQ_BASE_DATASET_RULES = RelationField("dqBaseDatasetRules")
GCSObject.DQ_REFERENCE_DATASET_RULES = RelationField("dqReferenceDatasetRules")
GCSObject.GCS_BUCKET = RelationField("gcsBucket")
GCSObject.MEANINGS = RelationField("meanings")
GCSObject.MC_MONITORS = RelationField("mcMonitors")
GCSObject.MC_INCIDENTS = RelationField("mcIncidents")
GCSObject.PARTIAL_CHILD_FIELDS = RelationField("partialChildFields")
GCSObject.PARTIAL_CHILD_OBJECTS = RelationField("partialChildObjects")
GCSObject.INPUT_TO_PROCESSES = RelationField("inputToProcesses")
GCSObject.OUTPUT_FROM_PROCESSES = RelationField("outputFromProcesses")
GCSObject.USER_DEF_RELATIONSHIP_TO = RelationField("userDefRelationshipTo")
GCSObject.USER_DEF_RELATIONSHIP_FROM = RelationField("userDefRelationshipFrom")
GCSObject.FILES = RelationField("files")
GCSObject.LINKS = RelationField("links")
GCSObject.README = RelationField("readme")
GCSObject.SCHEMA_REGISTRY_SUBJECTS = RelationField("schemaRegistrySubjects")
GCSObject.SODA_CHECKS = RelationField("sodaChecks")
GCSObject.INPUT_TO_SPARK_JOBS = RelationField("inputToSparkJobs")
GCSObject.OUTPUT_FROM_SPARK_JOBS = RelationField("outputFromSparkJobs")
