# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
Related type classes for GTC module.

This module contains all Related{Type} classes for the GTC type hierarchy.
These classes are used for relationship attributes to reference related entities.
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from .asset_related import RelatedAsset
from .referenceable_related import RelatedReferenceable

__all__ = [
    "RelatedAtlasGlossary",
    "RelatedAtlasGlossaryCategory",
    "RelatedAtlasGlossaryTerm",
]


class RelatedAtlasGlossary(RelatedAsset):
    """
    Related entity reference for AtlasGlossary assets.

    Extends RelatedAsset with AtlasGlossary-specific attributes.
    """

    # type_name inherited from parent with default=UNSET
    # __post_init__ sets it to "AtlasGlossary" so it serializes correctly

    short_description: Union[str, None, UnsetType] = UNSET
    """Unused. A short definition of the glossary. See 'description' and 'userDescription' instead."""

    long_description: Union[str, None, UnsetType] = UNSET
    """Unused. A longer description of the glossary. See 'readme' instead."""

    language: Union[str, None, UnsetType] = UNSET
    """Unused. Language of the glossary's contents."""

    usage: Union[str, None, UnsetType] = UNSET
    """Unused. Inteded usage for the glossary."""

    additional_attributes: Union[dict[str, str], None, UnsetType] = UNSET
    """Unused. Arbitrary set of additional attributes associated with this glossary."""

    glossary_type: Union[str, None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        RelatedReferenceable.__post_init__(self)
        self.type_name = "AtlasGlossary"


class RelatedAtlasGlossaryCategory(RelatedAsset):
    """
    Related entity reference for AtlasGlossaryCategory assets.

    Extends RelatedAsset with AtlasGlossaryCategory-specific attributes.
    """

    # type_name inherited from parent with default=UNSET
    # __post_init__ sets it to "AtlasGlossaryCategory" so it serializes correctly

    short_description: Union[str, None, UnsetType] = UNSET
    """Unused. Brief summary of the category. See 'description' and 'userDescription' instead."""

    long_description: Union[str, None, UnsetType] = UNSET
    """Unused. Detailed description of the category. See 'readme' instead."""

    additional_attributes: Union[dict[str, str], None, UnsetType] = UNSET
    """Unused. Arbitrary set of additional attributes associated with the category."""

    category_type: Union[str, None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        RelatedReferenceable.__post_init__(self)
        self.type_name = "AtlasGlossaryCategory"


class RelatedAtlasGlossaryTerm(RelatedAsset):
    """
    Related entity reference for AtlasGlossaryTerm assets.

    Extends RelatedAsset with AtlasGlossaryTerm-specific attributes.
    """

    # type_name inherited from parent with default=UNSET
    # __post_init__ sets it to "AtlasGlossaryTerm" so it serializes correctly

    short_description: Union[str, None, UnsetType] = UNSET
    """Unused. Brief summary of the term. See 'description' and 'userDescription' instead."""

    long_description: Union[str, None, UnsetType] = UNSET
    """Unused. Detailed definition of the term. See 'readme' instead."""

    examples: Union[list[str], None, UnsetType] = UNSET
    """Unused. Exmaples of the term."""

    abbreviation: Union[str, None, UnsetType] = UNSET
    """Unused. Abbreviation of the term."""

    usage: Union[str, None, UnsetType] = UNSET
    """Unused. Intended usage for the term."""

    additional_attributes: Union[dict[str, str], None, UnsetType] = UNSET
    """Unused. Arbitrary set of additional attributes for the terrm."""

    term_type: Union[str, None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        RelatedReferenceable.__post_init__(self)
        self.type_name = "AtlasGlossaryTerm"
