# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# ruff: noqa: ARG002
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
MatillionComponent asset model with flattened inheritance.

This module provides:
- MatillionComponent: Flat asset class (easy to use)
- MatillionComponentAttributes: Nested attributes struct (extends AssetAttributes)
- MatillionComponentNested: Nested API format struct
"""

from __future__ import annotations

import re
from typing import Any, ClassVar, Union

import msgspec
from msgspec import UNSET, UnsetType

from .airflow_related import RelatedAirflowTask
from .anomalo_related import RelatedAnomaloCheck
from .app_related import RelatedApplication, RelatedApplicationField
from .asset import (
    _ASSET_REL_FIELDS,
    Asset,
    AssetAttributes,
    AssetNested,
    AssetRelationshipAttributes,
    _extract_asset_attrs,
    _populate_asset_attrs,
)
from .data_mesh_related import RelatedDataProduct
from .data_quality_related import RelatedDataQualityRule, RelatedMetric
from .gtc_related import RelatedAtlasGlossaryTerm
from .model_related import RelatedModelAttribute, RelatedModelEntity
from .monte_carlo_related import RelatedMCIncident, RelatedMCMonitor
from .partial_related import RelatedPartialField, RelatedPartialObject
from .process_related import RelatedProcess
from .referenceable_related import RelatedReferenceable
from .resource_related import RelatedFile, RelatedLink, RelatedReadme
from .schema_registry_related import RelatedSchemaRegistrySubject
from .soda_related import RelatedSodaCheck
from .spark_related import RelatedSparkJob
from pyatlan_v9.model.conversion_utils import categorize_relationships, merge_relationships
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset

from .matillion_related import RelatedMatillionComponent, RelatedMatillionJob

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================

@register_asset
class MatillionComponent(Asset):
    """
    Instance of a Matillion component in Atlan. Components in Matillion are a part of a job, where each component is responsible for accomplishing a task based on the type of component used.
    """

    MATILLION_COMPONENT_ID: ClassVar[Any] = None
    MATILLION_COMPONENT_IMPLEMENTATION_ID: ClassVar[Any] = None
    MATILLION_COMPONENT_LINKED_JOB: ClassVar[Any] = None
    MATILLION_COMPONENT_LAST_RUN_STATUS: ClassVar[Any] = None
    MATILLION_COMPONENT_LAST_FIVE_RUN_STATUS: ClassVar[Any] = None
    MATILLION_COMPONENT_SQLS: ClassVar[Any] = None
    MATILLION_JOB_NAME: ClassVar[Any] = None
    MATILLION_JOB_QUALIFIED_NAME: ClassVar[Any] = None
    MATILLION_VERSION: ClassVar[Any] = None
    INPUT_TO_AIRFLOW_TASKS: ClassVar[Any] = None
    OUTPUT_FROM_AIRFLOW_TASKS: ClassVar[Any] = None
    ANOMALO_CHECKS: ClassVar[Any] = None
    APPLICATION: ClassVar[Any] = None
    APPLICATION_FIELD: ClassVar[Any] = None
    OUTPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    INPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ENTITIES: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ATTRIBUTES: ClassVar[Any] = None
    METRICS: ClassVar[Any] = None
    DQ_BASE_DATASET_RULES: ClassVar[Any] = None
    DQ_REFERENCE_DATASET_RULES: ClassVar[Any] = None
    MEANINGS: ClassVar[Any] = None
    MATILLION_JOB: ClassVar[Any] = None
    MATILLION_PROCESS: ClassVar[Any] = None
    MC_MONITORS: ClassVar[Any] = None
    MC_INCIDENTS: ClassVar[Any] = None
    PARTIAL_CHILD_FIELDS: ClassVar[Any] = None
    PARTIAL_CHILD_OBJECTS: ClassVar[Any] = None
    INPUT_TO_PROCESSES: ClassVar[Any] = None
    OUTPUT_FROM_PROCESSES: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_TO: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_FROM: ClassVar[Any] = None
    FILES: ClassVar[Any] = None
    LINKS: ClassVar[Any] = None
    README: ClassVar[Any] = None
    SCHEMA_REGISTRY_SUBJECTS: ClassVar[Any] = None
    SODA_CHECKS: ClassVar[Any] = None
    INPUT_TO_SPARK_JOBS: ClassVar[Any] = None
    OUTPUT_FROM_SPARK_JOBS: ClassVar[Any] = None

    type_name: Union[str, UnsetType] = "MatillionComponent"

    matillion_component_id: str | None | UnsetType = UNSET
    """Unique identifier of the component in Matillion."""

    matillion_component_implementation_id: str | None | UnsetType = UNSET
    """Unique identifier for the type of the component in Matillion."""

    matillion_component_linked_job: dict[str, str] | None | UnsetType = UNSET
    """Job details of the job to which the component internally links."""

    matillion_component_last_run_status: str | None | UnsetType = UNSET
    """Latest run status of the component within a job."""

    matillion_component_last_five_run_status: str | None | UnsetType = UNSET
    """Last five run statuses of the component within a job."""

    matillion_component_sqls: list[str] | None | UnsetType = UNSET
    """SQL queries used by the component."""

    matillion_job_name: str | None | UnsetType = UNSET
    """Simple name of the job to which the component belongs."""

    matillion_job_qualified_name: str | None | UnsetType = UNSET
    """Unique name of the job to which the component belongs."""

    matillion_version: str | None | UnsetType = UNSET
    """Current point in time state of a project."""

    input_to_airflow_tasks: list[RelatedAirflowTask] | None | UnsetType = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: list[RelatedAirflowTask] | None | UnsetType = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: list[RelatedAnomaloCheck] | None | UnsetType = UNSET
    """Checks that run on this asset."""

    application: RelatedApplication | None | UnsetType = UNSET
    """Application owning the Asset."""

    application_field: RelatedApplicationField | None | UnsetType = UNSET
    """ApplicationField owning the Asset."""

    output_port_data_products: list[RelatedDataProduct] | None | UnsetType = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: list[RelatedDataProduct] | None | UnsetType = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: list[RelatedModelEntity] | None | UnsetType = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: list[RelatedModelAttribute] | None | UnsetType = UNSET
    """Attributes implemented by this asset."""

    metrics: list[RelatedMetric] | None | UnsetType = UNSET
    """"""

    dq_base_dataset_rules: list[RelatedDataQualityRule] | None | UnsetType = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: list[RelatedDataQualityRule] | None | UnsetType = UNSET
    """Rules where this dataset is referenced."""

    meanings: list[RelatedAtlasGlossaryTerm] | None | UnsetType = UNSET
    """Glossary terms that are linked to this asset."""

    matillion_job: RelatedMatillionJob | None | UnsetType = UNSET
    """Job in which this component exists."""

    matillion_process: RelatedProcess | None | UnsetType = UNSET
    """Lineage process that represents this Matillion component."""

    mc_monitors: list[RelatedMCMonitor] | None | UnsetType = UNSET
    """Monitors that observe this asset."""

    mc_incidents: list[RelatedMCIncident] | None | UnsetType = UNSET
    """"""

    partial_child_fields: list[RelatedPartialField] | None | UnsetType = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: list[RelatedPartialObject] | None | UnsetType = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: list[RelatedProcess] | None | UnsetType = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: list[RelatedProcess] | None | UnsetType = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: list[RelatedReferenceable] | None | UnsetType = UNSET
    """"""

    user_def_relationship_from: list[RelatedReferenceable] | None | UnsetType = UNSET
    """"""

    files: list[RelatedFile] | None | UnsetType = UNSET
    """"""

    links: list[RelatedLink] | None | UnsetType = UNSET
    """Links that are attached to this asset."""

    readme: RelatedReadme | None | UnsetType = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: list[RelatedSchemaRegistrySubject] | None | UnsetType = UNSET
    """"""

    soda_checks: list[RelatedSodaCheck] | None | UnsetType = UNSET
    """"""

    input_to_spark_jobs: list[RelatedSparkJob] | None | UnsetType = UNSET
    """"""

    output_from_spark_jobs: list[RelatedSparkJob] | None | UnsetType = UNSET
    """"""

    def __post_init__(self) -> None:
        self.type_name = "MatillionComponent"

    # =========================================================================
    # SDK Methods
    # =========================================================================

    _QUALIFIED_NAME_PATTERN: ClassVar[re.Pattern] = re.compile(
        r"^.+/[^/]+/[^/]+/[^/]+/[^/]+$"
    )

    def validate(self, for_creation: bool = False) -> None:
        errors: list[str] = []
        if self.type_name is UNSET:
            errors.append("type_name is required")
        if self.name is UNSET:
            errors.append("name is required")
        if self.qualified_name is UNSET or self.qualified_name is None:
            errors.append("qualified_name is required")
        elif not self._QUALIFIED_NAME_PATTERN.match(self.qualified_name):
            errors.append(
                f"qualified_name '{self.qualified_name}' does not match expected "
                f"pattern: {self._QUALIFIED_NAME_PATTERN.pattern}"
            )
        if for_creation:
            if self.connection_qualified_name is UNSET:
                errors.append("connection_qualified_name is required for creation")
            if self.matillion_job is UNSET:
                errors.append("matillion_job is required for creation")
            if self.matillion_job_name is UNSET:
                errors.append("matillion_job_name is required for creation")
            if self.matillion_job_qualified_name is UNSET:
                errors.append("matillion_job_qualified_name is required for creation")
        if errors:
            raise ValueError(f"MatillionComponent validation failed: {errors}")

    def minimize(self) -> "MatillionComponent":
        self.validate()
        return MatillionComponent(qualified_name=self.qualified_name, name=self.name)

    def relate(self) -> "RelatedMatillionComponent":
        if self.guid is not UNSET:
            return RelatedMatillionComponent(guid=self.guid)
        return RelatedMatillionComponent(qualified_name=self.qualified_name)

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return self.to_nested_bytes(serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    def to_nested_bytes(self, serde: Serde | None = None) -> bytes:
        """Serialize to Atlas nested-format JSON bytes (pure msgspec, no dict intermediate)."""
        if serde is None:
            serde = get_serde()
        return _matillion_component_to_nested_bytes(self, serde)

    @staticmethod
    def from_json(json_data: str | bytes, serde: Serde | None = None) -> MatillionComponent:
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            MatillionComponent instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _matillion_component_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================

class MatillionComponentAttributes(AssetAttributes):
    """MatillionComponent-specific attributes for nested API format."""

    matillion_component_id: str | None | UnsetType = UNSET
    """Unique identifier of the component in Matillion."""

    matillion_component_implementation_id: str | None | UnsetType = UNSET
    """Unique identifier for the type of the component in Matillion."""

    matillion_component_linked_job: dict[str, str] | None | UnsetType = UNSET
    """Job details of the job to which the component internally links."""

    matillion_component_last_run_status: str | None | UnsetType = UNSET
    """Latest run status of the component within a job."""

    matillion_component_last_five_run_status: str | None | UnsetType = UNSET
    """Last five run statuses of the component within a job."""

    matillion_component_sqls: list[str] | None | UnsetType = UNSET
    """SQL queries used by the component."""

    matillion_job_name: str | None | UnsetType = UNSET
    """Simple name of the job to which the component belongs."""

    matillion_job_qualified_name: str | None | UnsetType = UNSET
    """Unique name of the job to which the component belongs."""

    matillion_version: str | None | UnsetType = UNSET
    """Current point in time state of a project."""

class MatillionComponentRelationshipAttributes(AssetRelationshipAttributes):
    """MatillionComponent-specific relationship attributes for nested API format."""

    input_to_airflow_tasks: list[RelatedAirflowTask] | None | UnsetType = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: list[RelatedAirflowTask] | None | UnsetType = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: list[RelatedAnomaloCheck] | None | UnsetType = UNSET
    """Checks that run on this asset."""

    application: RelatedApplication | None | UnsetType = UNSET
    """Application owning the Asset."""

    application_field: RelatedApplicationField | None | UnsetType = UNSET
    """ApplicationField owning the Asset."""

    output_port_data_products: list[RelatedDataProduct] | None | UnsetType = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: list[RelatedDataProduct] | None | UnsetType = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: list[RelatedModelEntity] | None | UnsetType = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: list[RelatedModelAttribute] | None | UnsetType = UNSET
    """Attributes implemented by this asset."""

    metrics: list[RelatedMetric] | None | UnsetType = UNSET
    """"""

    dq_base_dataset_rules: list[RelatedDataQualityRule] | None | UnsetType = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: list[RelatedDataQualityRule] | None | UnsetType = UNSET
    """Rules where this dataset is referenced."""

    meanings: list[RelatedAtlasGlossaryTerm] | None | UnsetType = UNSET
    """Glossary terms that are linked to this asset."""

    matillion_job: RelatedMatillionJob | None | UnsetType = UNSET
    """Job in which this component exists."""

    matillion_process: RelatedProcess | None | UnsetType = UNSET
    """Lineage process that represents this Matillion component."""

    mc_monitors: list[RelatedMCMonitor] | None | UnsetType = UNSET
    """Monitors that observe this asset."""

    mc_incidents: list[RelatedMCIncident] | None | UnsetType = UNSET
    """"""

    partial_child_fields: list[RelatedPartialField] | None | UnsetType = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: list[RelatedPartialObject] | None | UnsetType = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: list[RelatedProcess] | None | UnsetType = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: list[RelatedProcess] | None | UnsetType = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: list[RelatedReferenceable] | None | UnsetType = UNSET
    """"""

    user_def_relationship_from: list[RelatedReferenceable] | None | UnsetType = UNSET
    """"""

    files: list[RelatedFile] | None | UnsetType = UNSET
    """"""

    links: list[RelatedLink] | None | UnsetType = UNSET
    """Links that are attached to this asset."""

    readme: RelatedReadme | None | UnsetType = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: list[RelatedSchemaRegistrySubject] | None | UnsetType = UNSET
    """"""

    soda_checks: list[RelatedSodaCheck] | None | UnsetType = UNSET
    """"""

    input_to_spark_jobs: list[RelatedSparkJob] | None | UnsetType = UNSET
    """"""

    output_from_spark_jobs: list[RelatedSparkJob] | None | UnsetType = UNSET
    """"""

class MatillionComponentNested(AssetNested):
    """MatillionComponent in nested API format for high-performance serialization."""

    attributes: MatillionComponentAttributes | UnsetType = UNSET
    relationship_attributes: MatillionComponentRelationshipAttributes | UnsetType = UNSET
    append_relationship_attributes: MatillionComponentRelationshipAttributes | UnsetType = UNSET
    remove_relationship_attributes: MatillionComponentRelationshipAttributes | UnsetType = UNSET

# =============================================================================
# CONVERSION HELPERS & CONSTANTS
# =============================================================================

_MATILLION_COMPONENT_REL_FIELDS: list[str] = [
    *_ASSET_REL_FIELDS,
    "input_to_airflow_tasks",
    "output_from_airflow_tasks",
    "anomalo_checks",
    "application",
    "application_field",
    "output_port_data_products",
    "input_port_data_products",
    "model_implemented_entities",
    "model_implemented_attributes",
    "metrics",
    "dq_base_dataset_rules",
    "dq_reference_dataset_rules",
    "meanings",
    "matillion_job",
    "matillion_process",
    "mc_monitors",
    "mc_incidents",
    "partial_child_fields",
    "partial_child_objects",
    "input_to_processes",
    "output_from_processes",
    "user_def_relationship_to",
    "user_def_relationship_from",
    "files",
    "links",
    "readme",
    "schema_registry_subjects",
    "soda_checks",
    "input_to_spark_jobs",
    "output_from_spark_jobs",
]

def _populate_matillion_component_attrs(attrs: MatillionComponentAttributes, obj: MatillionComponent) -> None:
    """Populate MatillionComponent-specific attributes on the attrs struct."""
    _populate_asset_attrs(attrs, obj)
    attrs.matillion_component_id = obj.matillion_component_id
    attrs.matillion_component_implementation_id = obj.matillion_component_implementation_id
    attrs.matillion_component_linked_job = obj.matillion_component_linked_job
    attrs.matillion_component_last_run_status = obj.matillion_component_last_run_status
    attrs.matillion_component_last_five_run_status = obj.matillion_component_last_five_run_status
    attrs.matillion_component_sqls = obj.matillion_component_sqls
    attrs.matillion_job_name = obj.matillion_job_name
    attrs.matillion_job_qualified_name = obj.matillion_job_qualified_name
    attrs.matillion_version = obj.matillion_version

def _extract_matillion_component_attrs(attrs: MatillionComponentAttributes) -> dict:
    """Extract all MatillionComponent attributes from the attrs struct into a flat dict."""
    result = _extract_asset_attrs(attrs)
    result["matillion_component_id"] = attrs.matillion_component_id
    result["matillion_component_implementation_id"] = attrs.matillion_component_implementation_id
    result["matillion_component_linked_job"] = attrs.matillion_component_linked_job
    result["matillion_component_last_run_status"] = attrs.matillion_component_last_run_status
    result["matillion_component_last_five_run_status"] = attrs.matillion_component_last_five_run_status
    result["matillion_component_sqls"] = attrs.matillion_component_sqls
    result["matillion_job_name"] = attrs.matillion_job_name
    result["matillion_job_qualified_name"] = attrs.matillion_job_qualified_name
    result["matillion_version"] = attrs.matillion_version
    return result

# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _matillion_component_to_nested(matillion_component: MatillionComponent) -> MatillionComponentNested:
    """Convert flat MatillionComponent to nested format."""
    attrs = MatillionComponentAttributes()
    _populate_matillion_component_attrs(attrs, matillion_component)
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    replace_rels, append_rels, remove_rels = categorize_relationships(
        matillion_component, _MATILLION_COMPONENT_REL_FIELDS, MatillionComponentRelationshipAttributes
    )
    return MatillionComponentNested(
        guid=matillion_component.guid,
        type_name=matillion_component.type_name,
        status=matillion_component.status,
        version=matillion_component.version,
        create_time=matillion_component.create_time,
        update_time=matillion_component.update_time,
        created_by=matillion_component.created_by,
        updated_by=matillion_component.updated_by,
        classifications=matillion_component.classifications,
        classification_names=matillion_component.classification_names,
        meanings=matillion_component.meanings,
        labels=matillion_component.labels,
        business_attributes=matillion_component.business_attributes,
        custom_attributes=matillion_component.custom_attributes,
        pending_tasks=matillion_component.pending_tasks,
        proxy=matillion_component.proxy,
        is_incomplete=matillion_component.is_incomplete,
        provenance_type=matillion_component.provenance_type,
        home_id=matillion_component.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )

def _matillion_component_from_nested(nested: MatillionComponentNested) -> MatillionComponent:
    """Convert nested format to flat MatillionComponent."""
    attrs = nested.attributes if nested.attributes is not UNSET else MatillionComponentAttributes()
    # Merge relationships from all three buckets
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        _MATILLION_COMPONENT_REL_FIELDS,
        MatillionComponentRelationshipAttributes
    )
    return MatillionComponent(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        **_extract_matillion_component_attrs(attrs),
        # Merged relationship attributes
        **merged_rels,
    )

def _matillion_component_to_nested_bytes(matillion_component: MatillionComponent, serde: Serde) -> bytes:
    """Convert flat MatillionComponent to nested JSON bytes."""
    return serde.encode(_matillion_component_to_nested(matillion_component))


def _matillion_component_from_nested_bytes(data: bytes, serde: Serde) -> MatillionComponent:
    """Convert nested JSON bytes to flat MatillionComponent."""
    nested = serde.decode(data, MatillionComponentNested)
    return _matillion_component_from_nested(nested)

# ---------------------------------------------------------------------------
# Deferred field descriptor initialization
# ---------------------------------------------------------------------------
from pyatlan.model.fields.atlan_fields import (  # noqa: E402
    KeywordField,
    KeywordTextField,
    RelationField,
)

MatillionComponent.MATILLION_COMPONENT_ID = KeywordField("matillionComponentId", "matillionComponentId")
MatillionComponent.MATILLION_COMPONENT_IMPLEMENTATION_ID = KeywordField("matillionComponentImplementationId", "matillionComponentImplementationId")
MatillionComponent.MATILLION_COMPONENT_LINKED_JOB = KeywordField("matillionComponentLinkedJob", "matillionComponentLinkedJob")
MatillionComponent.MATILLION_COMPONENT_LAST_RUN_STATUS = KeywordField("matillionComponentLastRunStatus", "matillionComponentLastRunStatus")
MatillionComponent.MATILLION_COMPONENT_LAST_FIVE_RUN_STATUS = KeywordField("matillionComponentLastFiveRunStatus", "matillionComponentLastFiveRunStatus")
MatillionComponent.MATILLION_COMPONENT_SQLS = KeywordField("matillionComponentSqls", "matillionComponentSqls")
MatillionComponent.MATILLION_JOB_NAME = KeywordTextField("matillionJobName", "matillionJobName", "matillionJobName.text")
MatillionComponent.MATILLION_JOB_QUALIFIED_NAME = KeywordTextField("matillionJobQualifiedName", "matillionJobQualifiedName", "matillionJobQualifiedName.text")
MatillionComponent.MATILLION_VERSION = KeywordField("matillionVersion", "matillionVersion")
MatillionComponent.INPUT_TO_AIRFLOW_TASKS = RelationField("inputToAirflowTasks")
MatillionComponent.OUTPUT_FROM_AIRFLOW_TASKS = RelationField("outputFromAirflowTasks")
MatillionComponent.ANOMALO_CHECKS = RelationField("anomaloChecks")
MatillionComponent.APPLICATION = RelationField("application")
MatillionComponent.APPLICATION_FIELD = RelationField("applicationField")
MatillionComponent.OUTPUT_PORT_DATA_PRODUCTS = RelationField("outputPortDataProducts")
MatillionComponent.INPUT_PORT_DATA_PRODUCTS = RelationField("inputPortDataProducts")
MatillionComponent.MODEL_IMPLEMENTED_ENTITIES = RelationField("modelImplementedEntities")
MatillionComponent.MODEL_IMPLEMENTED_ATTRIBUTES = RelationField("modelImplementedAttributes")
MatillionComponent.METRICS = RelationField("metrics")
MatillionComponent.DQ_BASE_DATASET_RULES = RelationField("dqBaseDatasetRules")
MatillionComponent.DQ_REFERENCE_DATASET_RULES = RelationField("dqReferenceDatasetRules")
MatillionComponent.MEANINGS = RelationField("meanings")
MatillionComponent.MATILLION_JOB = RelationField("matillionJob")
MatillionComponent.MATILLION_PROCESS = RelationField("matillionProcess")
MatillionComponent.MC_MONITORS = RelationField("mcMonitors")
MatillionComponent.MC_INCIDENTS = RelationField("mcIncidents")
MatillionComponent.PARTIAL_CHILD_FIELDS = RelationField("partialChildFields")
MatillionComponent.PARTIAL_CHILD_OBJECTS = RelationField("partialChildObjects")
MatillionComponent.INPUT_TO_PROCESSES = RelationField("inputToProcesses")
MatillionComponent.OUTPUT_FROM_PROCESSES = RelationField("outputFromProcesses")
MatillionComponent.USER_DEF_RELATIONSHIP_TO = RelationField("userDefRelationshipTo")
MatillionComponent.USER_DEF_RELATIONSHIP_FROM = RelationField("userDefRelationshipFrom")
MatillionComponent.FILES = RelationField("files")
MatillionComponent.LINKS = RelationField("links")
MatillionComponent.README = RelationField("readme")
MatillionComponent.SCHEMA_REGISTRY_SUBJECTS = RelationField("schemaRegistrySubjects")
MatillionComponent.SODA_CHECKS = RelationField("sodaChecks")
MatillionComponent.INPUT_TO_SPARK_JOBS = RelationField("inputToSparkJobs")
MatillionComponent.OUTPUT_FROM_SPARK_JOBS = RelationField("outputFromSparkJobs")