# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# ruff: noqa: ARG002
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
QuickSightAnalysisVisual asset model with flattened inheritance.

This module provides:
- QuickSightAnalysisVisual: Flat asset class (easy to use)
- QuickSightAnalysisVisualAttributes: Nested attributes struct (extends AssetAttributes)
- QuickSightAnalysisVisualNested: Nested API format struct
"""

from __future__ import annotations

import re
from typing import Any, ClassVar, List, Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.model.conversion_utils import (
    categorize_relationships,
    merge_relationships,
)
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset
from pyatlan_v9.utils import init_guid, validate_required_fields

from .airflow_related import RelatedAirflowTask
from .anomalo_related import RelatedAnomaloCheck
from .app_related import RelatedApplication, RelatedApplicationField
from .asset import (
    _ASSET_REL_FIELDS,
    Asset,
    AssetAttributes,
    AssetNested,
    AssetRelationshipAttributes,
    _extract_asset_attrs,
    _populate_asset_attrs,
)
from .data_contract_related import RelatedDataContract
from .data_mesh_related import RelatedDataProduct
from .data_quality_related import RelatedDataQualityRule, RelatedMetric
from .gtc_related import RelatedAtlasGlossaryTerm
from .model_related import RelatedModelAttribute, RelatedModelEntity
from .monte_carlo_related import RelatedMCIncident, RelatedMCMonitor
from .partial_related import RelatedPartialField, RelatedPartialObject
from .process_related import RelatedProcess
from .quick_sight_related import RelatedQuickSightAnalysis
from .referenceable_related import RelatedReferenceable
from .resource_related import RelatedFile, RelatedLink, RelatedReadme
from .schema_registry_related import RelatedSchemaRegistrySubject
from .soda_related import RelatedSodaCheck
from .spark_related import RelatedSparkJob

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class QuickSightAnalysisVisual(Asset):
    """
    Instance of a QuickSight analysis visual in Atlan. These represent individual visuals inside an analysis.
    """

    QUICK_SIGHT_ANALYSIS_QUALIFIED_NAME: ClassVar[Any] = None
    QUICK_SIGHT_ID: ClassVar[Any] = None
    QUICK_SIGHT_SHEET_ID: ClassVar[Any] = None
    QUICK_SIGHT_SHEET_NAME: ClassVar[Any] = None
    CATALOG_DATASET_GUID: ClassVar[Any] = None
    INPUT_TO_AIRFLOW_TASKS: ClassVar[Any] = None
    OUTPUT_FROM_AIRFLOW_TASKS: ClassVar[Any] = None
    ANOMALO_CHECKS: ClassVar[Any] = None
    APPLICATION: ClassVar[Any] = None
    APPLICATION_FIELD: ClassVar[Any] = None
    DATA_CONTRACT_LATEST: ClassVar[Any] = None
    DATA_CONTRACT_LATEST_CERTIFIED: ClassVar[Any] = None
    OUTPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    INPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ENTITIES: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ATTRIBUTES: ClassVar[Any] = None
    METRICS: ClassVar[Any] = None
    DQ_BASE_DATASET_RULES: ClassVar[Any] = None
    DQ_REFERENCE_DATASET_RULES: ClassVar[Any] = None
    MEANINGS: ClassVar[Any] = None
    MC_MONITORS: ClassVar[Any] = None
    MC_INCIDENTS: ClassVar[Any] = None
    PARTIAL_CHILD_FIELDS: ClassVar[Any] = None
    PARTIAL_CHILD_OBJECTS: ClassVar[Any] = None
    INPUT_TO_PROCESSES: ClassVar[Any] = None
    OUTPUT_FROM_PROCESSES: ClassVar[Any] = None
    QUICK_SIGHT_ANALYSIS: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_TO: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_FROM: ClassVar[Any] = None
    FILES: ClassVar[Any] = None
    LINKS: ClassVar[Any] = None
    README: ClassVar[Any] = None
    SCHEMA_REGISTRY_SUBJECTS: ClassVar[Any] = None
    SODA_CHECKS: ClassVar[Any] = None
    INPUT_TO_SPARK_JOBS: ClassVar[Any] = None
    OUTPUT_FROM_SPARK_JOBS: ClassVar[Any] = None

    type_name: Union[str, UnsetType] = "QuickSightAnalysisVisual"

    quick_sight_analysis_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the QuickSight analysis in which this visual exists."""

    quick_sight_id: Union[str, None, UnsetType] = UNSET
    """Unique identifier for the QuickSight asset."""

    quick_sight_sheet_id: Union[str, None, UnsetType] = UNSET
    """Unique identifier for the QuickSight sheet."""

    quick_sight_sheet_name: Union[str, None, UnsetType] = UNSET
    """Name of the QuickSight sheet."""

    catalog_dataset_guid: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the dataset this asset belongs to."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    data_contract_latest: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest version of the data contract (in any status) for this asset."""

    data_contract_latest_certified: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest certified version of the data contract for this asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[
        List[RelatedModelAttribute], None, UnsetType
    ] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    quick_sight_analysis: Union[RelatedQuickSightAnalysis, None, UnsetType] = UNSET
    """Analysis in which this visual exists."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """Schema registry subjects associated with this asset."""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        self.type_name = "QuickSightAnalysisVisual"

    # =========================================================================
    # SDK Methods
    # =========================================================================

    _QUALIFIED_NAME_PATTERN: ClassVar[re.Pattern] = re.compile(
        r"^.+/[^/]+/[^/]+/[^/]+$"
    )

    @classmethod
    @init_guid
    def creator(
        cls,
        *,
        name: str,
        quick_sight_id: str,
        quick_sight_sheet_id: str,
        quick_sight_sheet_name: str,
        quick_sight_analysis_qualified_name: str,
        connection_qualified_name: Union[str, None] = None,
    ) -> "QuickSightAnalysisVisual":
        validate_required_fields(
            [
                "name",
                "quick_sight_id",
                "quick_sight_sheet_id",
                "quick_sight_sheet_name",
                "quick_sight_analysis_qualified_name",
            ],
            [
                name,
                quick_sight_id,
                quick_sight_sheet_id,
                quick_sight_sheet_name,
                quick_sight_analysis_qualified_name,
            ],
        )
        if connection_qualified_name:
            fields = connection_qualified_name.split("/")
            connector_name = fields[1] if len(fields) > 1 else None
        else:
            parts = quick_sight_analysis_qualified_name.split("/")
            connector_name = parts[1] if len(parts) > 1 else None
            connection_qualified_name = (
                "/".join(parts[:3])
                if len(parts) >= 3
                else quick_sight_analysis_qualified_name
            )
        qualified_name = f"{quick_sight_analysis_qualified_name}/{quick_sight_sheet_id}/{quick_sight_id}"
        return cls(
            name=name,
            quick_sight_id=quick_sight_id,
            quick_sight_sheet_id=quick_sight_sheet_id,
            quick_sight_sheet_name=quick_sight_sheet_name,
            quick_sight_analysis_qualified_name=quick_sight_analysis_qualified_name,
            qualified_name=qualified_name,
            connection_qualified_name=connection_qualified_name,
            connector_name=connector_name,
        )

    @classmethod
    def updater(cls, *, qualified_name: str, name: str) -> "QuickSightAnalysisVisual":
        """Create a QuickSightAnalysisVisual instance for update operations."""
        validate_required_fields(["qualified_name", "name"], [qualified_name, name])
        return cls(qualified_name=qualified_name, name=name)

    def trim_to_required(self) -> "QuickSightAnalysisVisual":
        """Return only fields required for update operations."""
        return QuickSightAnalysisVisual.updater(
            qualified_name=self.qualified_name, name=self.name
        )

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return self.to_nested_bytes(serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    def to_nested_bytes(self, serde: Serde | None = None) -> bytes:
        """Serialize to Atlas nested-format JSON bytes (pure msgspec, no dict intermediate)."""
        if serde is None:
            serde = get_serde()
        return _quick_sight_analysis_visual_to_nested_bytes(self, serde)

    @staticmethod
    def from_json(
        json_data: str | bytes, serde: Serde | None = None
    ) -> QuickSightAnalysisVisual:
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            QuickSightAnalysisVisual instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _quick_sight_analysis_visual_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class QuickSightAnalysisVisualAttributes(AssetAttributes):
    """QuickSightAnalysisVisual-specific attributes for nested API format."""

    quick_sight_analysis_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the QuickSight analysis in which this visual exists."""

    quick_sight_id: Union[str, None, UnsetType] = UNSET
    """Unique identifier for the QuickSight asset."""

    quick_sight_sheet_id: Union[str, None, UnsetType] = UNSET
    """Unique identifier for the QuickSight sheet."""

    quick_sight_sheet_name: Union[str, None, UnsetType] = UNSET
    """Name of the QuickSight sheet."""

    catalog_dataset_guid: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the dataset this asset belongs to."""


class QuickSightAnalysisVisualRelationshipAttributes(AssetRelationshipAttributes):
    """QuickSightAnalysisVisual-specific relationship attributes for nested API format."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    data_contract_latest: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest version of the data contract (in any status) for this asset."""

    data_contract_latest_certified: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest certified version of the data contract for this asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[
        List[RelatedModelAttribute], None, UnsetType
    ] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = (
        UNSET
    )
    """Rules where this dataset is referenced."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    quick_sight_analysis: Union[RelatedQuickSightAnalysis, None, UnsetType] = UNSET
    """Analysis in which this visual exists."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = (
        UNSET
    )
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[
        List[RelatedSchemaRegistrySubject], None, UnsetType
    ] = UNSET
    """Schema registry subjects associated with this asset."""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""


class QuickSightAnalysisVisualNested(AssetNested):
    """QuickSightAnalysisVisual in nested API format for high-performance serialization."""

    attributes: Union[QuickSightAnalysisVisualAttributes, UnsetType] = UNSET
    relationship_attributes: Union[
        QuickSightAnalysisVisualRelationshipAttributes, UnsetType
    ] = UNSET
    append_relationship_attributes: Union[
        QuickSightAnalysisVisualRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        QuickSightAnalysisVisualRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION HELPERS & CONSTANTS
# =============================================================================

_QUICK_SIGHT_ANALYSIS_VISUAL_REL_FIELDS: List[str] = [
    *_ASSET_REL_FIELDS,
    "input_to_airflow_tasks",
    "output_from_airflow_tasks",
    "anomalo_checks",
    "application",
    "application_field",
    "data_contract_latest",
    "data_contract_latest_certified",
    "output_port_data_products",
    "input_port_data_products",
    "model_implemented_entities",
    "model_implemented_attributes",
    "metrics",
    "dq_base_dataset_rules",
    "dq_reference_dataset_rules",
    "meanings",
    "mc_monitors",
    "mc_incidents",
    "partial_child_fields",
    "partial_child_objects",
    "input_to_processes",
    "output_from_processes",
    "quick_sight_analysis",
    "user_def_relationship_to",
    "user_def_relationship_from",
    "files",
    "links",
    "readme",
    "schema_registry_subjects",
    "soda_checks",
    "input_to_spark_jobs",
    "output_from_spark_jobs",
]


def _populate_quick_sight_analysis_visual_attrs(
    attrs: QuickSightAnalysisVisualAttributes, obj: QuickSightAnalysisVisual
) -> None:
    """Populate QuickSightAnalysisVisual-specific attributes on the attrs struct."""
    _populate_asset_attrs(attrs, obj)
    attrs.quick_sight_analysis_qualified_name = obj.quick_sight_analysis_qualified_name
    attrs.quick_sight_id = obj.quick_sight_id
    attrs.quick_sight_sheet_id = obj.quick_sight_sheet_id
    attrs.quick_sight_sheet_name = obj.quick_sight_sheet_name
    attrs.catalog_dataset_guid = obj.catalog_dataset_guid


def _extract_quick_sight_analysis_visual_attrs(
    attrs: QuickSightAnalysisVisualAttributes,
) -> dict:
    """Extract all QuickSightAnalysisVisual attributes from the attrs struct into a flat dict."""
    result = _extract_asset_attrs(attrs)
    result["quick_sight_analysis_qualified_name"] = (
        attrs.quick_sight_analysis_qualified_name
    )
    result["quick_sight_id"] = attrs.quick_sight_id
    result["quick_sight_sheet_id"] = attrs.quick_sight_sheet_id
    result["quick_sight_sheet_name"] = attrs.quick_sight_sheet_name
    result["catalog_dataset_guid"] = attrs.catalog_dataset_guid
    return result


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _quick_sight_analysis_visual_to_nested(
    quick_sight_analysis_visual: QuickSightAnalysisVisual,
) -> QuickSightAnalysisVisualNested:
    """Convert flat QuickSightAnalysisVisual to nested format."""
    attrs = QuickSightAnalysisVisualAttributes()
    _populate_quick_sight_analysis_visual_attrs(attrs, quick_sight_analysis_visual)
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    replace_rels, append_rels, remove_rels = categorize_relationships(
        quick_sight_analysis_visual,
        _QUICK_SIGHT_ANALYSIS_VISUAL_REL_FIELDS,
        QuickSightAnalysisVisualRelationshipAttributes,
    )
    return QuickSightAnalysisVisualNested(
        guid=quick_sight_analysis_visual.guid,
        type_name=quick_sight_analysis_visual.type_name,
        status=quick_sight_analysis_visual.status,
        version=quick_sight_analysis_visual.version,
        create_time=quick_sight_analysis_visual.create_time,
        update_time=quick_sight_analysis_visual.update_time,
        created_by=quick_sight_analysis_visual.created_by,
        updated_by=quick_sight_analysis_visual.updated_by,
        classifications=quick_sight_analysis_visual.classifications,
        classification_names=quick_sight_analysis_visual.classification_names,
        meanings=quick_sight_analysis_visual.meanings,
        labels=quick_sight_analysis_visual.labels,
        business_attributes=quick_sight_analysis_visual.business_attributes,
        custom_attributes=quick_sight_analysis_visual.custom_attributes,
        pending_tasks=quick_sight_analysis_visual.pending_tasks,
        proxy=quick_sight_analysis_visual.proxy,
        is_incomplete=quick_sight_analysis_visual.is_incomplete,
        provenance_type=quick_sight_analysis_visual.provenance_type,
        home_id=quick_sight_analysis_visual.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _quick_sight_analysis_visual_from_nested(
    nested: QuickSightAnalysisVisualNested,
) -> QuickSightAnalysisVisual:
    """Convert nested format to flat QuickSightAnalysisVisual."""
    attrs = (
        nested.attributes
        if nested.attributes is not UNSET
        else QuickSightAnalysisVisualAttributes()
    )
    # Merge relationships from all three buckets
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        _QUICK_SIGHT_ANALYSIS_VISUAL_REL_FIELDS,
        QuickSightAnalysisVisualRelationshipAttributes,
    )
    return QuickSightAnalysisVisual(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        **_extract_quick_sight_analysis_visual_attrs(attrs),
        # Merged relationship attributes
        **merged_rels,
    )


def _quick_sight_analysis_visual_to_nested_bytes(
    quick_sight_analysis_visual: QuickSightAnalysisVisual, serde: Serde
) -> bytes:
    """Convert flat QuickSightAnalysisVisual to nested JSON bytes."""
    return serde.encode(
        _quick_sight_analysis_visual_to_nested(quick_sight_analysis_visual)
    )


def _quick_sight_analysis_visual_from_nested_bytes(
    data: bytes, serde: Serde
) -> QuickSightAnalysisVisual:
    """Convert nested JSON bytes to flat QuickSightAnalysisVisual."""
    nested = serde.decode(data, QuickSightAnalysisVisualNested)
    return _quick_sight_analysis_visual_from_nested(nested)


# ---------------------------------------------------------------------------
# Deferred field descriptor initialization
# ---------------------------------------------------------------------------
from pyatlan.model.fields.atlan_fields import (  # noqa: E402
    KeywordField,
    KeywordTextField,
    RelationField,
)

QuickSightAnalysisVisual.QUICK_SIGHT_ANALYSIS_QUALIFIED_NAME = KeywordTextField(
    "quickSightAnalysisQualifiedName",
    "quickSightAnalysisQualifiedName",
    "quickSightAnalysisQualifiedName.text",
)
QuickSightAnalysisVisual.QUICK_SIGHT_ID = KeywordField("quickSightId", "quickSightId")
QuickSightAnalysisVisual.QUICK_SIGHT_SHEET_ID = KeywordField(
    "quickSightSheetId", "quickSightSheetId"
)
QuickSightAnalysisVisual.QUICK_SIGHT_SHEET_NAME = KeywordTextField(
    "quickSightSheetName", "quickSightSheetName", "quickSightSheetName.text"
)
QuickSightAnalysisVisual.CATALOG_DATASET_GUID = KeywordField(
    "catalogDatasetGuid", "catalogDatasetGuid"
)
QuickSightAnalysisVisual.INPUT_TO_AIRFLOW_TASKS = RelationField("inputToAirflowTasks")
QuickSightAnalysisVisual.OUTPUT_FROM_AIRFLOW_TASKS = RelationField(
    "outputFromAirflowTasks"
)
QuickSightAnalysisVisual.ANOMALO_CHECKS = RelationField("anomaloChecks")
QuickSightAnalysisVisual.APPLICATION = RelationField("application")
QuickSightAnalysisVisual.APPLICATION_FIELD = RelationField("applicationField")
QuickSightAnalysisVisual.DATA_CONTRACT_LATEST = RelationField("dataContractLatest")
QuickSightAnalysisVisual.DATA_CONTRACT_LATEST_CERTIFIED = RelationField(
    "dataContractLatestCertified"
)
QuickSightAnalysisVisual.OUTPUT_PORT_DATA_PRODUCTS = RelationField(
    "outputPortDataProducts"
)
QuickSightAnalysisVisual.INPUT_PORT_DATA_PRODUCTS = RelationField(
    "inputPortDataProducts"
)
QuickSightAnalysisVisual.MODEL_IMPLEMENTED_ENTITIES = RelationField(
    "modelImplementedEntities"
)
QuickSightAnalysisVisual.MODEL_IMPLEMENTED_ATTRIBUTES = RelationField(
    "modelImplementedAttributes"
)
QuickSightAnalysisVisual.METRICS = RelationField("metrics")
QuickSightAnalysisVisual.DQ_BASE_DATASET_RULES = RelationField("dqBaseDatasetRules")
QuickSightAnalysisVisual.DQ_REFERENCE_DATASET_RULES = RelationField(
    "dqReferenceDatasetRules"
)
QuickSightAnalysisVisual.MEANINGS = RelationField("meanings")
QuickSightAnalysisVisual.MC_MONITORS = RelationField("mcMonitors")
QuickSightAnalysisVisual.MC_INCIDENTS = RelationField("mcIncidents")
QuickSightAnalysisVisual.PARTIAL_CHILD_FIELDS = RelationField("partialChildFields")
QuickSightAnalysisVisual.PARTIAL_CHILD_OBJECTS = RelationField("partialChildObjects")
QuickSightAnalysisVisual.INPUT_TO_PROCESSES = RelationField("inputToProcesses")
QuickSightAnalysisVisual.OUTPUT_FROM_PROCESSES = RelationField("outputFromProcesses")
QuickSightAnalysisVisual.QUICK_SIGHT_ANALYSIS = RelationField("quickSightAnalysis")
QuickSightAnalysisVisual.USER_DEF_RELATIONSHIP_TO = RelationField(
    "userDefRelationshipTo"
)
QuickSightAnalysisVisual.USER_DEF_RELATIONSHIP_FROM = RelationField(
    "userDefRelationshipFrom"
)
QuickSightAnalysisVisual.FILES = RelationField("files")
QuickSightAnalysisVisual.LINKS = RelationField("links")
QuickSightAnalysisVisual.README = RelationField("readme")
QuickSightAnalysisVisual.SCHEMA_REGISTRY_SUBJECTS = RelationField(
    "schemaRegistrySubjects"
)
QuickSightAnalysisVisual.SODA_CHECKS = RelationField("sodaChecks")
QuickSightAnalysisVisual.INPUT_TO_SPARK_JOBS = RelationField("inputToSparkJobs")
QuickSightAnalysisVisual.OUTPUT_FROM_SPARK_JOBS = RelationField("outputFromSparkJobs")
