# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# ruff: noqa: ARG002
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
SSRS asset model with flattened inheritance.

This module provides:
- SSRS: Flat asset class (easy to use)
- SSRSAttributes: Nested attributes struct (extends AssetAttributes)
- SSRSNested: Nested API format struct
"""

from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Set, Union

import msgspec
from msgspec import UNSET, UnsetType

from .airflow_related import RelatedAirflowTask
from .anomalo_related import RelatedAnomaloCheck
from .app_related import RelatedApplication, RelatedApplicationField
from .asset import (
    _ASSET_REL_FIELDS,
    Asset,
    AssetAttributes,
    AssetNested,
    AssetRelationshipAttributes,
    _extract_asset_attrs,
    _populate_asset_attrs,
)
from .context_related import RelatedContextRepository
from .data_contract_related import RelatedDataContract
from .data_mesh_related import RelatedDataProduct
from .data_quality_related import RelatedDataQualityRule, RelatedMetric
from .gcp_dataplex_related import RelatedGCPDataplexAspectType
from .gtc_related import RelatedAtlasGlossaryTerm
from .model_related import RelatedModelAttribute, RelatedModelEntity
from .monte_carlo_related import RelatedMCIncident, RelatedMCMonitor
from .partial_related import RelatedPartialField, RelatedPartialObject
from .process_related import RelatedProcess
from .referenceable_related import RelatedReferenceable
from .resource_related import RelatedFile, RelatedLink, RelatedReadme
from .schema_registry_related import RelatedSchemaRegistrySubject
from .soda_related import RelatedSodaCheck
from .spark_related import RelatedSparkJob
from pyatlan_v9.model.conversion_utils import categorize_relationships, merge_relationships
from pyatlan_v9.model.serde import Serde, get_serde
from pyatlan_v9.model.transform import register_asset

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================

@register_asset
class SSRS(Asset):
    """
    Base class for SQL Server Reporting Services assets.
    """

    SSRS_PATH: ClassVar[Any] = None
    SSRS_USED_IN_REPORTS: ClassVar[Any] = None
    SSRS_HIDDEN: ClassVar[Any] = None
    SSRS_TABLE_NAME: ClassVar[Any] = None
    SSRS_SCHEMA_NAME: ClassVar[Any] = None
    SSRS_CATALOG_NAME: ClassVar[Any] = None
    SSRS_REFERENCE_REPOSITORY_ID: ClassVar[Any] = None
    SSRS_PARENT_FOLDER_QUALIFIED_NAME: ClassVar[Any] = None
    SSRS_FOLDER_HIERARCHIES: ClassVar[Any] = None
    SSRS_REPORT_QUALIFIED_NAME: ClassVar[Any] = None
    SSRS_REPORT_NAME: ClassVar[Any] = None
    SSRS_DATA_SET_QUALIFIED_NAME: ClassVar[Any] = None
    SSRS_DATA_SET_NAME: ClassVar[Any] = None
    CATALOG_DATASET_GUID: ClassVar[Any] = None
    INPUT_TO_AIRFLOW_TASKS: ClassVar[Any] = None
    OUTPUT_FROM_AIRFLOW_TASKS: ClassVar[Any] = None
    ANOMALO_CHECKS: ClassVar[Any] = None
    APPLICATION: ClassVar[Any] = None
    APPLICATION_FIELD: ClassVar[Any] = None
    CONTEXT_REPOSITORIES: ClassVar[Any] = None
    DATA_CONTRACT_LATEST: ClassVar[Any] = None
    DATA_CONTRACT_LATEST_CERTIFIED: ClassVar[Any] = None
    OUTPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    INPUT_PORT_DATA_PRODUCTS: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ENTITIES: ClassVar[Any] = None
    MODEL_IMPLEMENTED_ATTRIBUTES: ClassVar[Any] = None
    METRICS: ClassVar[Any] = None
    DQ_BASE_DATASET_RULES: ClassVar[Any] = None
    DQ_REFERENCE_DATASET_RULES: ClassVar[Any] = None
    GCP_DATAPLEX_ASPECT_TYPE_METADATA_ENTITIES: ClassVar[Any] = None
    MEANINGS: ClassVar[Any] = None
    MC_MONITORS: ClassVar[Any] = None
    MC_INCIDENTS: ClassVar[Any] = None
    PARTIAL_CHILD_FIELDS: ClassVar[Any] = None
    PARTIAL_CHILD_OBJECTS: ClassVar[Any] = None
    INPUT_TO_PROCESSES: ClassVar[Any] = None
    OUTPUT_FROM_PROCESSES: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_TO: ClassVar[Any] = None
    USER_DEF_RELATIONSHIP_FROM: ClassVar[Any] = None
    FILES: ClassVar[Any] = None
    LINKS: ClassVar[Any] = None
    README: ClassVar[Any] = None
    SCHEMA_REGISTRY_SUBJECTS: ClassVar[Any] = None
    SODA_CHECKS: ClassVar[Any] = None
    INPUT_TO_SPARK_JOBS: ClassVar[Any] = None
    OUTPUT_FROM_SPARK_JOBS: ClassVar[Any] = None

    type_name: Union[str, UnsetType] = "SSRS"

    ssrs_path: Union[str, None, UnsetType] = UNSET
    """Path of the asset in SSRS."""

    ssrs_used_in_reports: Union[bool, None, UnsetType] = UNSET
    """Whether the asset is used in a report."""

    ssrs_hidden: Union[bool, None, UnsetType] = UNSET
    """Whether the asset is hidden."""

    ssrs_table_name: Union[str, None, UnsetType] = UNSET
    """Table name associated with this asset in the source system."""

    ssrs_schema_name: Union[str, None, UnsetType] = UNSET
    """Schema name associated with this asset in the source system."""

    ssrs_catalog_name: Union[str, None, UnsetType] = UNSET
    """Catalog name associated with this asset in the source system."""

    ssrs_reference_repository_id: Union[str, None, UnsetType] = UNSET
    """Reference repository ID for this asset."""

    ssrs_parent_folder_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the immediate parent folder containing this asset."""

    ssrs_folder_hierarchies: Union[List[Dict[str, str]], None, UnsetType] = UNSET
    """Ordered array of folder assets with qualified name and name representing the complete folder hierarchy path for this asset, from immediate parent to root folder."""

    ssrs_report_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the Report asset that contains this asset."""

    ssrs_report_name: Union[str, None, UnsetType] = UNSET
    """Simple name of the Report asset that contains this asset."""

    ssrs_data_set_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the DataSet asset that contains this asset."""

    ssrs_data_set_name: Union[str, None, UnsetType] = UNSET
    """Simple name of the DataSet asset that contains this asset."""

    catalog_dataset_guid: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the dataset this asset belongs to."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    context_repositories: Union[List[RelatedContextRepository], None, UnsetType] = UNSET
    """Context repositories that use this asset as input."""

    data_contract_latest: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest version of the data contract (in any status) for this asset."""

    data_contract_latest_certified: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest certified version of the data contract for this asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[List[RelatedModelAttribute], None, UnsetType] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules where this dataset is referenced."""

    gcp_dataplex_aspect_type_metadata_entities: Union[List[RelatedGCPDataplexAspectType], None, UnsetType] = UNSET
    """Dataplex entries (assets) that have aspects of this Aspect Type attached."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[List[RelatedSchemaRegistrySubject], None, UnsetType] = UNSET
    """Schema registry subjects associated with this asset."""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    def __post_init__(self) -> None:
        self.type_name = "SSRS"



    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return self.to_nested_bytes(serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    def to_nested_bytes(self, serde: Serde | None = None) -> bytes:
        """Serialize to Atlas nested-format JSON bytes (pure msgspec, no dict intermediate)."""
        if serde is None:
            serde = get_serde()
        return _ssrs_to_nested_bytes(self, serde)

    @staticmethod
    def from_json(json_data: str | bytes, serde: Serde | None = None) -> SSRS:
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            SSRS instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _ssrs_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================

class SSRSAttributes(AssetAttributes):
    """SSRS-specific attributes for nested API format."""

    ssrs_path: Union[str, None, UnsetType] = UNSET
    """Path of the asset in SSRS."""

    ssrs_used_in_reports: Union[bool, None, UnsetType] = UNSET
    """Whether the asset is used in a report."""

    ssrs_hidden: Union[bool, None, UnsetType] = UNSET
    """Whether the asset is hidden."""

    ssrs_table_name: Union[str, None, UnsetType] = UNSET
    """Table name associated with this asset in the source system."""

    ssrs_schema_name: Union[str, None, UnsetType] = UNSET
    """Schema name associated with this asset in the source system."""

    ssrs_catalog_name: Union[str, None, UnsetType] = UNSET
    """Catalog name associated with this asset in the source system."""

    ssrs_reference_repository_id: Union[str, None, UnsetType] = UNSET
    """Reference repository ID for this asset."""

    ssrs_parent_folder_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the immediate parent folder containing this asset."""

    ssrs_folder_hierarchies: Union[List[Dict[str, str]], None, UnsetType] = UNSET
    """Ordered array of folder assets with qualified name and name representing the complete folder hierarchy path for this asset, from immediate parent to root folder."""

    ssrs_report_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the Report asset that contains this asset."""

    ssrs_report_name: Union[str, None, UnsetType] = UNSET
    """Simple name of the Report asset that contains this asset."""

    ssrs_data_set_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the DataSet asset that contains this asset."""

    ssrs_data_set_name: Union[str, None, UnsetType] = UNSET
    """Simple name of the DataSet asset that contains this asset."""

    catalog_dataset_guid: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the dataset this asset belongs to."""

class SSRSRelationshipAttributes(AssetRelationshipAttributes):
    """SSRS-specific relationship attributes for nested API format."""

    input_to_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks to which this asset provides input."""

    output_from_airflow_tasks: Union[List[RelatedAirflowTask], None, UnsetType] = UNSET
    """Tasks from which this asset is output."""

    anomalo_checks: Union[List[RelatedAnomaloCheck], None, UnsetType] = UNSET
    """Checks that run on this asset."""

    application: Union[RelatedApplication, None, UnsetType] = UNSET
    """Application owning the Asset."""

    application_field: Union[RelatedApplicationField, None, UnsetType] = UNSET
    """ApplicationField owning the Asset."""

    context_repositories: Union[List[RelatedContextRepository], None, UnsetType] = UNSET
    """Context repositories that use this asset as input."""

    data_contract_latest: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest version of the data contract (in any status) for this asset."""

    data_contract_latest_certified: Union[RelatedDataContract, None, UnsetType] = UNSET
    """Latest certified version of the data contract for this asset."""

    output_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an output port."""

    input_port_data_products: Union[List[RelatedDataProduct], None, UnsetType] = UNSET
    """Data products for which this asset is an input port."""

    model_implemented_entities: Union[List[RelatedModelEntity], None, UnsetType] = UNSET
    """Entities implemented by this asset."""

    model_implemented_attributes: Union[List[RelatedModelAttribute], None, UnsetType] = UNSET
    """Attributes implemented by this asset."""

    metrics: Union[List[RelatedMetric], None, UnsetType] = UNSET
    """"""

    dq_base_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules that are applied on this dataset."""

    dq_reference_dataset_rules: Union[List[RelatedDataQualityRule], None, UnsetType] = UNSET
    """Rules where this dataset is referenced."""

    gcp_dataplex_aspect_type_metadata_entities: Union[List[RelatedGCPDataplexAspectType], None, UnsetType] = UNSET
    """Dataplex entries (assets) that have aspects of this Aspect Type attached."""

    meanings: Union[List[RelatedAtlasGlossaryTerm], None, UnsetType] = UNSET
    """Glossary terms that are linked to this asset."""

    mc_monitors: Union[List[RelatedMCMonitor], None, UnsetType] = UNSET
    """Monitors that observe this asset."""

    mc_incidents: Union[List[RelatedMCIncident], None, UnsetType] = UNSET
    """"""

    partial_child_fields: Union[List[RelatedPartialField], None, UnsetType] = UNSET
    """Partial fields contained in the asset."""

    partial_child_objects: Union[List[RelatedPartialObject], None, UnsetType] = UNSET
    """Partial objects contained in the asset."""

    input_to_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes to which this asset provides input."""

    output_from_processes: Union[List[RelatedProcess], None, UnsetType] = UNSET
    """Processes from which this asset is produced as output."""

    user_def_relationship_to: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    user_def_relationship_from: Union[List[RelatedReferenceable], None, UnsetType] = UNSET
    """"""

    files: Union[List[RelatedFile], None, UnsetType] = UNSET
    """"""

    links: Union[List[RelatedLink], None, UnsetType] = UNSET
    """Links that are attached to this asset."""

    readme: Union[RelatedReadme, None, UnsetType] = UNSET
    """README that is linked to this asset."""

    schema_registry_subjects: Union[List[RelatedSchemaRegistrySubject], None, UnsetType] = UNSET
    """Schema registry subjects associated with this asset."""

    soda_checks: Union[List[RelatedSodaCheck], None, UnsetType] = UNSET
    """"""

    input_to_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

    output_from_spark_jobs: Union[List[RelatedSparkJob], None, UnsetType] = UNSET
    """"""

class SSRSNested(AssetNested):
    """SSRS in nested API format for high-performance serialization."""

    attributes: Union[SSRSAttributes, UnsetType] = UNSET
    relationship_attributes: Union[SSRSRelationshipAttributes, UnsetType] = UNSET
    append_relationship_attributes: Union[SSRSRelationshipAttributes, UnsetType] = UNSET
    remove_relationship_attributes: Union[SSRSRelationshipAttributes, UnsetType] = UNSET

# =============================================================================
# CONVERSION HELPERS & CONSTANTS
# =============================================================================

_SSRS_REL_FIELDS: List[str] = [
    *_ASSET_REL_FIELDS,
    "input_to_airflow_tasks",
    "output_from_airflow_tasks",
    "anomalo_checks",
    "application",
    "application_field",
    "context_repositories",
    "data_contract_latest",
    "data_contract_latest_certified",
    "output_port_data_products",
    "input_port_data_products",
    "model_implemented_entities",
    "model_implemented_attributes",
    "metrics",
    "dq_base_dataset_rules",
    "dq_reference_dataset_rules",
    "gcp_dataplex_aspect_type_metadata_entities",
    "meanings",
    "mc_monitors",
    "mc_incidents",
    "partial_child_fields",
    "partial_child_objects",
    "input_to_processes",
    "output_from_processes",
    "user_def_relationship_to",
    "user_def_relationship_from",
    "files",
    "links",
    "readme",
    "schema_registry_subjects",
    "soda_checks",
    "input_to_spark_jobs",
    "output_from_spark_jobs",
]

def _populate_ssrs_attrs(attrs: SSRSAttributes, obj: SSRS) -> None:
    """Populate SSRS-specific attributes on the attrs struct."""
    _populate_asset_attrs(attrs, obj)
    attrs.ssrs_path = obj.ssrs_path
    attrs.ssrs_used_in_reports = obj.ssrs_used_in_reports
    attrs.ssrs_hidden = obj.ssrs_hidden
    attrs.ssrs_table_name = obj.ssrs_table_name
    attrs.ssrs_schema_name = obj.ssrs_schema_name
    attrs.ssrs_catalog_name = obj.ssrs_catalog_name
    attrs.ssrs_reference_repository_id = obj.ssrs_reference_repository_id
    attrs.ssrs_parent_folder_qualified_name = obj.ssrs_parent_folder_qualified_name
    attrs.ssrs_folder_hierarchies = obj.ssrs_folder_hierarchies
    attrs.ssrs_report_qualified_name = obj.ssrs_report_qualified_name
    attrs.ssrs_report_name = obj.ssrs_report_name
    attrs.ssrs_data_set_qualified_name = obj.ssrs_data_set_qualified_name
    attrs.ssrs_data_set_name = obj.ssrs_data_set_name
    attrs.catalog_dataset_guid = obj.catalog_dataset_guid

def _extract_ssrs_attrs(attrs: SSRSAttributes) -> dict:
    """Extract all SSRS attributes from the attrs struct into a flat dict."""
    result = _extract_asset_attrs(attrs)
    result["ssrs_path"] = attrs.ssrs_path
    result["ssrs_used_in_reports"] = attrs.ssrs_used_in_reports
    result["ssrs_hidden"] = attrs.ssrs_hidden
    result["ssrs_table_name"] = attrs.ssrs_table_name
    result["ssrs_schema_name"] = attrs.ssrs_schema_name
    result["ssrs_catalog_name"] = attrs.ssrs_catalog_name
    result["ssrs_reference_repository_id"] = attrs.ssrs_reference_repository_id
    result["ssrs_parent_folder_qualified_name"] = attrs.ssrs_parent_folder_qualified_name
    result["ssrs_folder_hierarchies"] = attrs.ssrs_folder_hierarchies
    result["ssrs_report_qualified_name"] = attrs.ssrs_report_qualified_name
    result["ssrs_report_name"] = attrs.ssrs_report_name
    result["ssrs_data_set_qualified_name"] = attrs.ssrs_data_set_qualified_name
    result["ssrs_data_set_name"] = attrs.ssrs_data_set_name
    result["catalog_dataset_guid"] = attrs.catalog_dataset_guid
    return result

# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _ssrs_to_nested(ssrs: SSRS) -> SSRSNested:
    """Convert flat SSRS to nested format."""
    attrs = SSRSAttributes()
    _populate_ssrs_attrs(attrs, ssrs)
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    replace_rels, append_rels, remove_rels = categorize_relationships(
        ssrs, _SSRS_REL_FIELDS, SSRSRelationshipAttributes
    )
    return SSRSNested(
        guid=ssrs.guid,
        type_name=ssrs.type_name,
        status=ssrs.status,
        version=ssrs.version,
        create_time=ssrs.create_time,
        update_time=ssrs.update_time,
        created_by=ssrs.created_by,
        updated_by=ssrs.updated_by,
        classifications=ssrs.classifications,
        classification_names=ssrs.classification_names,
        meanings=ssrs.meanings,
        labels=ssrs.labels,
        business_attributes=ssrs.business_attributes,
        custom_attributes=ssrs.custom_attributes,
        pending_tasks=ssrs.pending_tasks,
        proxy=ssrs.proxy,
        is_incomplete=ssrs.is_incomplete,
        provenance_type=ssrs.provenance_type,
        home_id=ssrs.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )

def _ssrs_from_nested(nested: SSRSNested) -> SSRS:
    """Convert nested format to flat SSRS."""
    attrs = nested.attributes if nested.attributes is not UNSET else SSRSAttributes()
    # Merge relationships from all three buckets
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        _SSRS_REL_FIELDS,
        SSRSRelationshipAttributes
    )
    return SSRS(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        **_extract_ssrs_attrs(attrs),
        # Merged relationship attributes
        **merged_rels,
    )

def _ssrs_to_nested_bytes(ssrs: SSRS, serde: Serde) -> bytes:
    """Convert flat SSRS to nested JSON bytes."""
    return serde.encode(_ssrs_to_nested(ssrs))


def _ssrs_from_nested_bytes(data: bytes, serde: Serde) -> SSRS:
    """Convert nested JSON bytes to flat SSRS."""
    nested = serde.decode(data, SSRSNested)
    return _ssrs_from_nested(nested)

# ---------------------------------------------------------------------------
# Deferred field descriptor initialization
# ---------------------------------------------------------------------------
from pyatlan.model.fields.atlan_fields import (  # noqa: E402
    BooleanField,
    KeywordField,
    RelationField,
)

SSRS.SSRS_PATH = KeywordField("ssrsPath", "ssrsPath")
SSRS.SSRS_USED_IN_REPORTS = BooleanField("ssrsUsedInReports", "ssrsUsedInReports")
SSRS.SSRS_HIDDEN = BooleanField("ssrsHidden", "ssrsHidden")
SSRS.SSRS_TABLE_NAME = KeywordField("ssrsTableName", "ssrsTableName")
SSRS.SSRS_SCHEMA_NAME = KeywordField("ssrsSchemaName", "ssrsSchemaName")
SSRS.SSRS_CATALOG_NAME = KeywordField("ssrsCatalogName", "ssrsCatalogName")
SSRS.SSRS_REFERENCE_REPOSITORY_ID = KeywordField("ssrsReferenceRepositoryId", "ssrsReferenceRepositoryId")
SSRS.SSRS_PARENT_FOLDER_QUALIFIED_NAME = KeywordField("ssrsParentFolderQualifiedName", "ssrsParentFolderQualifiedName")
SSRS.SSRS_FOLDER_HIERARCHIES = KeywordField("ssrsFolderHierarchies", "ssrsFolderHierarchies")
SSRS.SSRS_REPORT_QUALIFIED_NAME = KeywordField("ssrsReportQualifiedName", "ssrsReportQualifiedName")
SSRS.SSRS_REPORT_NAME = KeywordField("ssrsReportName", "ssrsReportName")
SSRS.SSRS_DATA_SET_QUALIFIED_NAME = KeywordField("ssrsDataSetQualifiedName", "ssrsDataSetQualifiedName")
SSRS.SSRS_DATA_SET_NAME = KeywordField("ssrsDataSetName", "ssrsDataSetName")
SSRS.CATALOG_DATASET_GUID = KeywordField("catalogDatasetGuid", "catalogDatasetGuid")
SSRS.INPUT_TO_AIRFLOW_TASKS = RelationField("inputToAirflowTasks")
SSRS.OUTPUT_FROM_AIRFLOW_TASKS = RelationField("outputFromAirflowTasks")
SSRS.ANOMALO_CHECKS = RelationField("anomaloChecks")
SSRS.APPLICATION = RelationField("application")
SSRS.APPLICATION_FIELD = RelationField("applicationField")
SSRS.CONTEXT_REPOSITORIES = RelationField("contextRepositories")
SSRS.DATA_CONTRACT_LATEST = RelationField("dataContractLatest")
SSRS.DATA_CONTRACT_LATEST_CERTIFIED = RelationField("dataContractLatestCertified")
SSRS.OUTPUT_PORT_DATA_PRODUCTS = RelationField("outputPortDataProducts")
SSRS.INPUT_PORT_DATA_PRODUCTS = RelationField("inputPortDataProducts")
SSRS.MODEL_IMPLEMENTED_ENTITIES = RelationField("modelImplementedEntities")
SSRS.MODEL_IMPLEMENTED_ATTRIBUTES = RelationField("modelImplementedAttributes")
SSRS.METRICS = RelationField("metrics")
SSRS.DQ_BASE_DATASET_RULES = RelationField("dqBaseDatasetRules")
SSRS.DQ_REFERENCE_DATASET_RULES = RelationField("dqReferenceDatasetRules")
SSRS.GCP_DATAPLEX_ASPECT_TYPE_METADATA_ENTITIES = RelationField("gcpDataplexAspectTypeMetadataEntities")
SSRS.MEANINGS = RelationField("meanings")
SSRS.MC_MONITORS = RelationField("mcMonitors")
SSRS.MC_INCIDENTS = RelationField("mcIncidents")
SSRS.PARTIAL_CHILD_FIELDS = RelationField("partialChildFields")
SSRS.PARTIAL_CHILD_OBJECTS = RelationField("partialChildObjects")
SSRS.INPUT_TO_PROCESSES = RelationField("inputToProcesses")
SSRS.OUTPUT_FROM_PROCESSES = RelationField("outputFromProcesses")
SSRS.USER_DEF_RELATIONSHIP_TO = RelationField("userDefRelationshipTo")
SSRS.USER_DEF_RELATIONSHIP_FROM = RelationField("userDefRelationshipFrom")
SSRS.FILES = RelationField("files")
SSRS.LINKS = RelationField("links")
SSRS.README = RelationField("readme")
SSRS.SCHEMA_REGISTRY_SUBJECTS = RelationField("schemaRegistrySubjects")
SSRS.SODA_CHECKS = RelationField("sodaChecks")
SSRS.INPUT_TO_SPARK_JOBS = RelationField("inputToSparkJobs")
SSRS.OUTPUT_FROM_SPARK_JOBS = RelationField("outputFromSparkJobs")