# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
Related type classes for Task module.

This module contains all Related{Type} classes for the Task type hierarchy.
These classes are used for relationship attributes to reference related entities.
"""

from __future__ import annotations

from typing import Any

from msgspec import UNSET, UnsetType

from .asset_related import RelatedAsset
from .referenceable_related import RelatedReferenceable

__all__ = [
    "RelatedTask",
]


class RelatedTask(RelatedAsset):
    """
    Related entity reference for Task assets.

    Extends RelatedAsset with Task-specific attributes.
    """

    # type_name inherited from parent with default=UNSET
    # __post_init__ sets it to "Task" so it serializes correctly

    task_recipient: str | None | UnsetType = UNSET
    """Recipient of the task."""

    task_type: str | None | UnsetType = UNSET
    """Type of task."""

    task_requestor: str | None | UnsetType = UNSET
    """Requestor of the task."""

    task_is_read: bool | None | UnsetType = UNSET
    """Flag to make task read/unread."""

    task_requestor_comment: str | None | UnsetType = UNSET
    """Comment of requestor for the task."""

    task_related_asset_guid: str | None | UnsetType = UNSET
    """Unique identifier of the asset to preview."""

    task_proposals: str | None | UnsetType = UNSET
    """Contains the payload that is proposed to the task."""

    task_expires_at: int | None | UnsetType = UNSET
    """Time (epoch) at which the task expires."""

    task_actions: list[dict[str, Any]] | None | UnsetType = UNSET
    """List of actions associated with this task."""

    task_execution_comment: str | None | UnsetType = UNSET
    """Comment for the action executed by user."""

    task_execution_action: str | None | UnsetType = UNSET
    """Action executed by the recipient."""

    task_integration_config: str | None | UnsetType = UNSET
    """Contains external integration config for the task."""

    task_created_by: str | None | UnsetType = UNSET
    """Username of the user who created this task."""

    task_updated_by: str | None | UnsetType = UNSET
    """Username of the user who updated this task."""

    def __post_init__(self) -> None:
        RelatedReferenceable.__post_init__(self)
        self.type_name = "Task"
