# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
Cognite asset model with flattened inheritance.

This module provides:
- Cognite: Flat asset class (easy to use)
- CogniteAttributes: Nested attributes struct (extends AssetAttributes)
- CogniteNested: Nested API format struct
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.conversion_utils import categorize_relationships, merge_relationships
from pyatlan_v9.serde import Serde, get_serde
from pyatlan_v9.transform import register_asset

from .asset import Asset, AssetAttributes, AssetNested, AssetRelationshipAttributes

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class Cognite(Asset):
    """
    Base class for Cognite assets.
    """

    # Override type_name with Cognite-specific default
    type_name: Union[str, UnsetType] = "Cognite"

    pass

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return _cognite_to_nested_bytes(self, serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    @staticmethod
    def from_json(
        json_data: Union[str, bytes], serde: Serde | None = None
    ) -> "Cognite":
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            Cognite instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _cognite_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class CogniteAttributes(AssetAttributes):
    """Cognite-specific attributes for nested API format."""

    pass


class CogniteRelationshipAttributes(AssetRelationshipAttributes):
    """Cognite-specific relationship attributes for nested API format."""

    pass


class CogniteNested(AssetNested):
    """Cognite in nested API format for high-performance serialization."""

    attributes: Union[CogniteAttributes, UnsetType] = UNSET
    relationship_attributes: Union[CogniteRelationshipAttributes, UnsetType] = UNSET
    append_relationship_attributes: Union[CogniteRelationshipAttributes, UnsetType] = (
        UNSET
    )
    remove_relationship_attributes: Union[CogniteRelationshipAttributes, UnsetType] = (
        UNSET
    )


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _cognite_to_nested(cognite: Cognite) -> CogniteNested:
    """Convert flat Cognite to nested format."""
    attrs = CogniteAttributes()
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    rel_fields: list[str] = []
    replace_rels, append_rels, remove_rels = categorize_relationships(
        cognite, rel_fields, CogniteRelationshipAttributes
    )
    return CogniteNested(
        guid=cognite.guid,
        type_name=cognite.type_name,
        status=cognite.status,
        version=cognite.version,
        create_time=cognite.create_time,
        update_time=cognite.update_time,
        created_by=cognite.created_by,
        updated_by=cognite.updated_by,
        classifications=cognite.classifications,
        classification_names=cognite.classification_names,
        meanings=cognite.meanings,
        labels=cognite.labels,
        business_attributes=cognite.business_attributes,
        custom_attributes=cognite.custom_attributes,
        pending_tasks=cognite.pending_tasks,
        proxy=cognite.proxy,
        is_incomplete=cognite.is_incomplete,
        provenance_type=cognite.provenance_type,
        home_id=cognite.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _cognite_from_nested(nested: CogniteNested) -> Cognite:
    """Convert nested format to flat Cognite."""
    attrs = nested.attributes if nested.attributes is not UNSET else CogniteAttributes()
    # Merge relationships from all three buckets
    rel_fields: list[str] = []
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        rel_fields,
        CogniteRelationshipAttributes,
    )
    return Cognite(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        # Merged relationship attributes
        **merged_rels,
    )


def _cognite_to_nested_bytes(cognite: Cognite, serde: Serde) -> bytes:
    """Convert flat Cognite to nested JSON bytes."""
    return serde.encode(_cognite_to_nested(cognite))


def _cognite_from_nested_bytes(data: bytes, serde: Serde) -> Cognite:
    """Convert nested JSON bytes to flat Cognite."""
    nested = serde.decode(data, CogniteNested)
    return _cognite_from_nested(nested)
