# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
FivetranConnector asset model with flattened inheritance.

This module provides:
- FivetranConnector: Flat asset class (easy to use)
- FivetranConnectorAttributes: Nested attributes struct (extends AssetAttributes)
- FivetranConnectorNested: Nested API format struct
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.conversion_utils import categorize_relationships, merge_relationships
from pyatlan_v9.serde import Serde, get_serde
from pyatlan_v9.transform import register_asset

from .asset import Asset, AssetAttributes, AssetNested, AssetRelationshipAttributes
from .process_related import RelatedProcess

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class FivetranConnector(Asset):
    """
    Instance of a Fivetran connector asset in Atlan.
    """

    # Override type_name with FivetranConnector-specific default
    type_name: Union[str, UnsetType] = "FivetranConnector"

    fivetran_last_sync_id: Union[str, None, UnsetType] = UNSET
    """ID of the latest sync"""

    fivetran_last_sync_started_at: Union[int, None, UnsetType] = UNSET
    """Timestamp (epoch) when the latest sync started on Fivetran, in milliseconds"""

    fivetran_last_sync_finished_at: Union[int, None, UnsetType] = UNSET
    """Timestamp (epoch) when the latest sync finished on Fivetran, in milliseconds"""

    fivetran_last_sync_reason: Union[str, None, UnsetType] = UNSET
    """Failure reason for the latest sync on Fivetran. If status is FAILURE, this is the description of the reason why the sync failed. If status is FAILURE_WITH_TASK, this is the description of the Error. If status is RESCHEDULED, this is the description of the reason why the sync is rescheduled."""

    fivetran_last_sync_task_type: Union[str, None, UnsetType] = UNSET
    """Failure task type for the latest sync on Fivetran. If status is FAILURE_WITH_TASK or RESCHEDULED, this field displays the type of the Error that caused the failure or rescheduling, respectively, e.g., reconnect, update_service_account, etc."""

    fivetran_last_sync_rescheduled_at: Union[int, None, UnsetType] = UNSET
    """Timestamp (epoch) at which the latest sync is rescheduled at on Fivetran"""

    fivetran_last_sync_tables_synced: Union[int, None, UnsetType] = UNSET
    """Number of tables synced in the latest sync on Fivetran"""

    fivetran_last_sync_extract_time_seconds: Union[float, None, UnsetType] = UNSET
    """Extract time in seconds in the latest sync on fivetran"""

    fivetran_last_sync_extract_volume_megabytes: Union[float, None, UnsetType] = UNSET
    """Extracted data volume in metabytes in the latest sync on Fivetran"""

    fivetran_last_sync_load_time_seconds: Union[float, None, UnsetType] = UNSET
    """Load time in seconds in the latest sync on Fivetran"""

    fivetran_last_sync_load_volume_megabytes: Union[float, None, UnsetType] = UNSET
    """Loaded data volume in metabytes in the latest sync on Fivetran"""

    fivetran_last_sync_process_time_seconds: Union[float, None, UnsetType] = UNSET
    """Process time in seconds in the latest sync on Fivetran"""

    fivetran_last_sync_process_volume_megabytes: Union[float, None, UnsetType] = UNSET
    """Process volume in metabytes in the latest sync on Fivetran"""

    fivetran_last_sync_total_time_seconds: Union[float, None, UnsetType] = UNSET
    """Total sync time in seconds in the latest sync on Fivetran"""

    fivetran_name: Union[str, None, UnsetType] = UNSET
    """Connector name added by the user on Fivetran"""

    fivetran_type: Union[str, None, UnsetType] = UNSET
    """Type of connector on Fivetran. Eg: snowflake, google_analytics, notion etc."""

    fivetran_url: Union[str, None, UnsetType] = UNSET
    """URL to open the connector details on Fivetran"""

    fivetran_destination_name: Union[str, None, UnsetType] = UNSET
    """Destination name added by the user on Fivetran"""

    fivetran_destination_type: Union[str, None, UnsetType] = UNSET
    """Type of destination on Fivetran. Eg: redshift, bigquery etc."""

    fivetran_destination_url: Union[str, None, UnsetType] = UNSET
    """URL to open the destination details on Fivetran"""

    fivetran_sync_setup_on: Union[int, None, UnsetType] = UNSET
    """Timestamp (epoch) on which the connector was setup on Fivetran, in milliseconds"""

    fivetran_sync_frequency: Union[str, None, UnsetType] = UNSET
    """Sync frequency for the connector in number of hours. Eg: Every 6 hours"""

    fivetran_sync_paused: Union[bool, None, UnsetType] = UNSET
    """Boolean to indicate whether the sync for this connector is paused or not"""

    fivetran_sync_setup_user_full_name: Union[str, None, UnsetType] = UNSET
    """Full name of the user who setup the connector on Fivetran"""

    fivetran_sync_setup_user_email: Union[str, None, UnsetType] = UNSET
    """Email ID of the user who setpu the connector on Fivetran"""

    fivetran_monthly_active_rows_free: Union[int, None, UnsetType] = UNSET
    """Free Monthly Active Rows used by the connector in the past month"""

    fivetran_monthly_active_rows_paid: Union[int, None, UnsetType] = UNSET
    """Paid Monthly Active Rows used by the connector in the past month"""

    fivetran_monthly_active_rows_total: Union[int, None, UnsetType] = UNSET
    """Total Monthly Active Rows used by the connector in the past month"""

    fivetran_monthly_active_rows_change_percentage_free: Union[
        float, None, UnsetType
    ] = UNSET
    """Increase in the percentage of free MAR compared to the previous month"""

    fivetran_monthly_active_rows_change_percentage_paid: Union[
        float, None, UnsetType
    ] = UNSET
    """Increase in the percentage of paid MAR compared to the previous month"""

    fivetran_monthly_active_rows_change_percentage_total: Union[
        float, None, UnsetType
    ] = UNSET
    """Increase in the percentage of total MAR compared to the previous month"""

    fivetran_monthly_active_rows_free_percentage_of_account: Union[
        float, None, UnsetType
    ] = UNSET
    """Percentage of the account's total free MAR used by this connector"""

    fivetran_monthly_active_rows_paid_percentage_of_account: Union[
        float, None, UnsetType
    ] = UNSET
    """Percentage of the account's total paid MAR used by this connector"""

    fivetran_monthly_active_rows_total_percentage_of_account: Union[
        float, None, UnsetType
    ] = UNSET
    """Percentage of the account's total MAR used by this connector"""

    fivetran_total_tables_synced: Union[int, None, UnsetType] = UNSET
    """Total number of tables synced by this connector"""

    fivetran_connector_top_tables_by_mar: Union[str, None, UnsetType] = UNSET
    """Total five tables sorted by MAR synced by this connector"""

    fivetran_usage_cost: Union[float, None, UnsetType] = UNSET
    """Total usage cost by this destination"""

    fivetran_credits_used: Union[float, None, UnsetType] = UNSET
    """Total credits used by this destination"""

    fivetran_workflow_name: Union[str, None, UnsetType] = UNSET
    """Name of the atlan fivetran workflow that updated this asset"""

    fivetran_last_sync_status: Union[str, None, UnsetType] = UNSET
    """Status of the latest sync on Fivetran."""

    fivetran_last_sync_records_updated: Union[int, None, UnsetType] = UNSET
    """Number of records updated in the latest sync on Fivetran"""

    processes: Union[list[RelatedProcess], None, UnsetType] = UNSET
    """Processes related to this Fivetran connector"""

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return _fivetran_connector_to_nested_bytes(self, serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    @staticmethod
    def from_json(
        json_data: Union[str, bytes], serde: Serde | None = None
    ) -> "FivetranConnector":
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            FivetranConnector instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _fivetran_connector_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class FivetranConnectorAttributes(AssetAttributes):
    """FivetranConnector-specific attributes for nested API format."""

    fivetran_last_sync_id: Union[str, None, UnsetType] = UNSET
    """ID of the latest sync"""

    fivetran_last_sync_started_at: Union[int, None, UnsetType] = UNSET
    """Timestamp (epoch) when the latest sync started on Fivetran, in milliseconds"""

    fivetran_last_sync_finished_at: Union[int, None, UnsetType] = UNSET
    """Timestamp (epoch) when the latest sync finished on Fivetran, in milliseconds"""

    fivetran_last_sync_reason: Union[str, None, UnsetType] = UNSET
    """Failure reason for the latest sync on Fivetran. If status is FAILURE, this is the description of the reason why the sync failed. If status is FAILURE_WITH_TASK, this is the description of the Error. If status is RESCHEDULED, this is the description of the reason why the sync is rescheduled."""

    fivetran_last_sync_task_type: Union[str, None, UnsetType] = UNSET
    """Failure task type for the latest sync on Fivetran. If status is FAILURE_WITH_TASK or RESCHEDULED, this field displays the type of the Error that caused the failure or rescheduling, respectively, e.g., reconnect, update_service_account, etc."""

    fivetran_last_sync_rescheduled_at: Union[int, None, UnsetType] = UNSET
    """Timestamp (epoch) at which the latest sync is rescheduled at on Fivetran"""

    fivetran_last_sync_tables_synced: Union[int, None, UnsetType] = UNSET
    """Number of tables synced in the latest sync on Fivetran"""

    fivetran_last_sync_extract_time_seconds: Union[float, None, UnsetType] = UNSET
    """Extract time in seconds in the latest sync on fivetran"""

    fivetran_last_sync_extract_volume_megabytes: Union[float, None, UnsetType] = UNSET
    """Extracted data volume in metabytes in the latest sync on Fivetran"""

    fivetran_last_sync_load_time_seconds: Union[float, None, UnsetType] = UNSET
    """Load time in seconds in the latest sync on Fivetran"""

    fivetran_last_sync_load_volume_megabytes: Union[float, None, UnsetType] = UNSET
    """Loaded data volume in metabytes in the latest sync on Fivetran"""

    fivetran_last_sync_process_time_seconds: Union[float, None, UnsetType] = UNSET
    """Process time in seconds in the latest sync on Fivetran"""

    fivetran_last_sync_process_volume_megabytes: Union[float, None, UnsetType] = UNSET
    """Process volume in metabytes in the latest sync on Fivetran"""

    fivetran_last_sync_total_time_seconds: Union[float, None, UnsetType] = UNSET
    """Total sync time in seconds in the latest sync on Fivetran"""

    fivetran_name: Union[str, None, UnsetType] = UNSET
    """Connector name added by the user on Fivetran"""

    fivetran_type: Union[str, None, UnsetType] = UNSET
    """Type of connector on Fivetran. Eg: snowflake, google_analytics, notion etc."""

    fivetran_url: Union[str, None, UnsetType] = UNSET
    """URL to open the connector details on Fivetran"""

    fivetran_destination_name: Union[str, None, UnsetType] = UNSET
    """Destination name added by the user on Fivetran"""

    fivetran_destination_type: Union[str, None, UnsetType] = UNSET
    """Type of destination on Fivetran. Eg: redshift, bigquery etc."""

    fivetran_destination_url: Union[str, None, UnsetType] = UNSET
    """URL to open the destination details on Fivetran"""

    fivetran_sync_setup_on: Union[int, None, UnsetType] = UNSET
    """Timestamp (epoch) on which the connector was setup on Fivetran, in milliseconds"""

    fivetran_sync_frequency: Union[str, None, UnsetType] = UNSET
    """Sync frequency for the connector in number of hours. Eg: Every 6 hours"""

    fivetran_sync_paused: Union[bool, None, UnsetType] = UNSET
    """Boolean to indicate whether the sync for this connector is paused or not"""

    fivetran_sync_setup_user_full_name: Union[str, None, UnsetType] = UNSET
    """Full name of the user who setup the connector on Fivetran"""

    fivetran_sync_setup_user_email: Union[str, None, UnsetType] = UNSET
    """Email ID of the user who setpu the connector on Fivetran"""

    fivetran_monthly_active_rows_free: Union[int, None, UnsetType] = UNSET
    """Free Monthly Active Rows used by the connector in the past month"""

    fivetran_monthly_active_rows_paid: Union[int, None, UnsetType] = UNSET
    """Paid Monthly Active Rows used by the connector in the past month"""

    fivetran_monthly_active_rows_total: Union[int, None, UnsetType] = UNSET
    """Total Monthly Active Rows used by the connector in the past month"""

    fivetran_monthly_active_rows_change_percentage_free: Union[
        float, None, UnsetType
    ] = UNSET
    """Increase in the percentage of free MAR compared to the previous month"""

    fivetran_monthly_active_rows_change_percentage_paid: Union[
        float, None, UnsetType
    ] = UNSET
    """Increase in the percentage of paid MAR compared to the previous month"""

    fivetran_monthly_active_rows_change_percentage_total: Union[
        float, None, UnsetType
    ] = UNSET
    """Increase in the percentage of total MAR compared to the previous month"""

    fivetran_monthly_active_rows_free_percentage_of_account: Union[
        float, None, UnsetType
    ] = UNSET
    """Percentage of the account's total free MAR used by this connector"""

    fivetran_monthly_active_rows_paid_percentage_of_account: Union[
        float, None, UnsetType
    ] = UNSET
    """Percentage of the account's total paid MAR used by this connector"""

    fivetran_monthly_active_rows_total_percentage_of_account: Union[
        float, None, UnsetType
    ] = UNSET
    """Percentage of the account's total MAR used by this connector"""

    fivetran_total_tables_synced: Union[int, None, UnsetType] = UNSET
    """Total number of tables synced by this connector"""

    fivetran_connector_top_tables_by_mar: Union[str, None, UnsetType] = UNSET
    """Total five tables sorted by MAR synced by this connector"""

    fivetran_usage_cost: Union[float, None, UnsetType] = UNSET
    """Total usage cost by this destination"""

    fivetran_credits_used: Union[float, None, UnsetType] = UNSET
    """Total credits used by this destination"""

    fivetran_workflow_name: Union[str, None, UnsetType] = UNSET
    """Name of the atlan fivetran workflow that updated this asset"""

    fivetran_last_sync_status: Union[str, None, UnsetType] = UNSET
    """Status of the latest sync on Fivetran."""

    fivetran_last_sync_records_updated: Union[int, None, UnsetType] = UNSET
    """Number of records updated in the latest sync on Fivetran"""


class FivetranConnectorRelationshipAttributes(AssetRelationshipAttributes):
    """FivetranConnector-specific relationship attributes for nested API format."""

    processes: Union[list[RelatedProcess], None, UnsetType] = UNSET
    """Processes related to this Fivetran connector"""


class FivetranConnectorNested(AssetNested):
    """FivetranConnector in nested API format for high-performance serialization."""

    attributes: Union[FivetranConnectorAttributes, UnsetType] = UNSET
    relationship_attributes: Union[
        FivetranConnectorRelationshipAttributes, UnsetType
    ] = UNSET
    append_relationship_attributes: Union[
        FivetranConnectorRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        FivetranConnectorRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _fivetran_connector_to_nested(
    fivetran_connector: FivetranConnector,
) -> FivetranConnectorNested:
    """Convert flat FivetranConnector to nested format."""
    attrs = FivetranConnectorAttributes(
        fivetran_last_sync_id=fivetran_connector.fivetran_last_sync_id,
        fivetran_last_sync_started_at=fivetran_connector.fivetran_last_sync_started_at,
        fivetran_last_sync_finished_at=fivetran_connector.fivetran_last_sync_finished_at,
        fivetran_last_sync_reason=fivetran_connector.fivetran_last_sync_reason,
        fivetran_last_sync_task_type=fivetran_connector.fivetran_last_sync_task_type,
        fivetran_last_sync_rescheduled_at=fivetran_connector.fivetran_last_sync_rescheduled_at,
        fivetran_last_sync_tables_synced=fivetran_connector.fivetran_last_sync_tables_synced,
        fivetran_last_sync_extract_time_seconds=fivetran_connector.fivetran_last_sync_extract_time_seconds,
        fivetran_last_sync_extract_volume_megabytes=fivetran_connector.fivetran_last_sync_extract_volume_megabytes,
        fivetran_last_sync_load_time_seconds=fivetran_connector.fivetran_last_sync_load_time_seconds,
        fivetran_last_sync_load_volume_megabytes=fivetran_connector.fivetran_last_sync_load_volume_megabytes,
        fivetran_last_sync_process_time_seconds=fivetran_connector.fivetran_last_sync_process_time_seconds,
        fivetran_last_sync_process_volume_megabytes=fivetran_connector.fivetran_last_sync_process_volume_megabytes,
        fivetran_last_sync_total_time_seconds=fivetran_connector.fivetran_last_sync_total_time_seconds,
        fivetran_name=fivetran_connector.fivetran_name,
        fivetran_type=fivetran_connector.fivetran_type,
        fivetran_url=fivetran_connector.fivetran_url,
        fivetran_destination_name=fivetran_connector.fivetran_destination_name,
        fivetran_destination_type=fivetran_connector.fivetran_destination_type,
        fivetran_destination_url=fivetran_connector.fivetran_destination_url,
        fivetran_sync_setup_on=fivetran_connector.fivetran_sync_setup_on,
        fivetran_sync_frequency=fivetran_connector.fivetran_sync_frequency,
        fivetran_sync_paused=fivetran_connector.fivetran_sync_paused,
        fivetran_sync_setup_user_full_name=fivetran_connector.fivetran_sync_setup_user_full_name,
        fivetran_sync_setup_user_email=fivetran_connector.fivetran_sync_setup_user_email,
        fivetran_monthly_active_rows_free=fivetran_connector.fivetran_monthly_active_rows_free,
        fivetran_monthly_active_rows_paid=fivetran_connector.fivetran_monthly_active_rows_paid,
        fivetran_monthly_active_rows_total=fivetran_connector.fivetran_monthly_active_rows_total,
        fivetran_monthly_active_rows_change_percentage_free=fivetran_connector.fivetran_monthly_active_rows_change_percentage_free,
        fivetran_monthly_active_rows_change_percentage_paid=fivetran_connector.fivetran_monthly_active_rows_change_percentage_paid,
        fivetran_monthly_active_rows_change_percentage_total=fivetran_connector.fivetran_monthly_active_rows_change_percentage_total,
        fivetran_monthly_active_rows_free_percentage_of_account=fivetran_connector.fivetran_monthly_active_rows_free_percentage_of_account,
        fivetran_monthly_active_rows_paid_percentage_of_account=fivetran_connector.fivetran_monthly_active_rows_paid_percentage_of_account,
        fivetran_monthly_active_rows_total_percentage_of_account=fivetran_connector.fivetran_monthly_active_rows_total_percentage_of_account,
        fivetran_total_tables_synced=fivetran_connector.fivetran_total_tables_synced,
        fivetran_connector_top_tables_by_mar=fivetran_connector.fivetran_connector_top_tables_by_mar,
        fivetran_usage_cost=fivetran_connector.fivetran_usage_cost,
        fivetran_credits_used=fivetran_connector.fivetran_credits_used,
        fivetran_workflow_name=fivetran_connector.fivetran_workflow_name,
        fivetran_last_sync_status=fivetran_connector.fivetran_last_sync_status,
        fivetran_last_sync_records_updated=fivetran_connector.fivetran_last_sync_records_updated,
    )
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    rel_fields: list[str] = ["processes"]
    replace_rels, append_rels, remove_rels = categorize_relationships(
        fivetran_connector, rel_fields, FivetranConnectorRelationshipAttributes
    )
    return FivetranConnectorNested(
        guid=fivetran_connector.guid,
        type_name=fivetran_connector.type_name,
        status=fivetran_connector.status,
        version=fivetran_connector.version,
        create_time=fivetran_connector.create_time,
        update_time=fivetran_connector.update_time,
        created_by=fivetran_connector.created_by,
        updated_by=fivetran_connector.updated_by,
        classifications=fivetran_connector.classifications,
        classification_names=fivetran_connector.classification_names,
        meanings=fivetran_connector.meanings,
        labels=fivetran_connector.labels,
        business_attributes=fivetran_connector.business_attributes,
        custom_attributes=fivetran_connector.custom_attributes,
        pending_tasks=fivetran_connector.pending_tasks,
        proxy=fivetran_connector.proxy,
        is_incomplete=fivetran_connector.is_incomplete,
        provenance_type=fivetran_connector.provenance_type,
        home_id=fivetran_connector.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _fivetran_connector_from_nested(
    nested: FivetranConnectorNested,
) -> FivetranConnector:
    """Convert nested format to flat FivetranConnector."""
    attrs = (
        nested.attributes
        if nested.attributes is not UNSET
        else FivetranConnectorAttributes()
    )
    # Merge relationships from all three buckets
    rel_fields: list[str] = ["processes"]
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        rel_fields,
        FivetranConnectorRelationshipAttributes,
    )
    return FivetranConnector(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        fivetran_last_sync_id=attrs.fivetran_last_sync_id,
        fivetran_last_sync_started_at=attrs.fivetran_last_sync_started_at,
        fivetran_last_sync_finished_at=attrs.fivetran_last_sync_finished_at,
        fivetran_last_sync_reason=attrs.fivetran_last_sync_reason,
        fivetran_last_sync_task_type=attrs.fivetran_last_sync_task_type,
        fivetran_last_sync_rescheduled_at=attrs.fivetran_last_sync_rescheduled_at,
        fivetran_last_sync_tables_synced=attrs.fivetran_last_sync_tables_synced,
        fivetran_last_sync_extract_time_seconds=attrs.fivetran_last_sync_extract_time_seconds,
        fivetran_last_sync_extract_volume_megabytes=attrs.fivetran_last_sync_extract_volume_megabytes,
        fivetran_last_sync_load_time_seconds=attrs.fivetran_last_sync_load_time_seconds,
        fivetran_last_sync_load_volume_megabytes=attrs.fivetran_last_sync_load_volume_megabytes,
        fivetran_last_sync_process_time_seconds=attrs.fivetran_last_sync_process_time_seconds,
        fivetran_last_sync_process_volume_megabytes=attrs.fivetran_last_sync_process_volume_megabytes,
        fivetran_last_sync_total_time_seconds=attrs.fivetran_last_sync_total_time_seconds,
        fivetran_name=attrs.fivetran_name,
        fivetran_type=attrs.fivetran_type,
        fivetran_url=attrs.fivetran_url,
        fivetran_destination_name=attrs.fivetran_destination_name,
        fivetran_destination_type=attrs.fivetran_destination_type,
        fivetran_destination_url=attrs.fivetran_destination_url,
        fivetran_sync_setup_on=attrs.fivetran_sync_setup_on,
        fivetran_sync_frequency=attrs.fivetran_sync_frequency,
        fivetran_sync_paused=attrs.fivetran_sync_paused,
        fivetran_sync_setup_user_full_name=attrs.fivetran_sync_setup_user_full_name,
        fivetran_sync_setup_user_email=attrs.fivetran_sync_setup_user_email,
        fivetran_monthly_active_rows_free=attrs.fivetran_monthly_active_rows_free,
        fivetran_monthly_active_rows_paid=attrs.fivetran_monthly_active_rows_paid,
        fivetran_monthly_active_rows_total=attrs.fivetran_monthly_active_rows_total,
        fivetran_monthly_active_rows_change_percentage_free=attrs.fivetran_monthly_active_rows_change_percentage_free,
        fivetran_monthly_active_rows_change_percentage_paid=attrs.fivetran_monthly_active_rows_change_percentage_paid,
        fivetran_monthly_active_rows_change_percentage_total=attrs.fivetran_monthly_active_rows_change_percentage_total,
        fivetran_monthly_active_rows_free_percentage_of_account=attrs.fivetran_monthly_active_rows_free_percentage_of_account,
        fivetran_monthly_active_rows_paid_percentage_of_account=attrs.fivetran_monthly_active_rows_paid_percentage_of_account,
        fivetran_monthly_active_rows_total_percentage_of_account=attrs.fivetran_monthly_active_rows_total_percentage_of_account,
        fivetran_total_tables_synced=attrs.fivetran_total_tables_synced,
        fivetran_connector_top_tables_by_mar=attrs.fivetran_connector_top_tables_by_mar,
        fivetran_usage_cost=attrs.fivetran_usage_cost,
        fivetran_credits_used=attrs.fivetran_credits_used,
        fivetran_workflow_name=attrs.fivetran_workflow_name,
        fivetran_last_sync_status=attrs.fivetran_last_sync_status,
        fivetran_last_sync_records_updated=attrs.fivetran_last_sync_records_updated,
        # Merged relationship attributes
        **merged_rels,
    )


def _fivetran_connector_to_nested_bytes(
    fivetran_connector: FivetranConnector, serde: Serde
) -> bytes:
    """Convert flat FivetranConnector to nested JSON bytes."""
    return serde.encode(_fivetran_connector_to_nested(fivetran_connector))


def _fivetran_connector_from_nested_bytes(
    data: bytes, serde: Serde
) -> FivetranConnector:
    """Convert nested JSON bytes to flat FivetranConnector."""
    nested = serde.decode(data, FivetranConnectorNested)
    return _fivetran_connector_from_nested(nested)
