# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
MicroStrategyColumn asset model with flattened inheritance.

This module provides:
- MicroStrategyColumn: Flat asset class (easy to use)
- MicroStrategyColumnAttributes: Nested attributes struct (extends AssetAttributes)
- MicroStrategyColumnNested: Nested API format struct
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.conversion_utils import categorize_relationships, merge_relationships
from pyatlan_v9.serde import Serde, get_serde
from pyatlan_v9.transform import register_asset

from .asset import Asset, AssetAttributes, AssetNested, AssetRelationshipAttributes
from .micro_strategy_related import (
    RelatedMicroStrategyAttribute,
    RelatedMicroStrategyCube,
    RelatedMicroStrategyDocument,
    RelatedMicroStrategyDossier,
    RelatedMicroStrategyFact,
    RelatedMicroStrategyMetric,
    RelatedMicroStrategyReport,
)

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class MicroStrategyColumn(Asset):
    """
    Base class for MicroStrategy column assets in Atlan.
    """

    # Override type_name with MicroStrategyColumn-specific default
    type_name: Union[str, UnsetType] = "MicroStrategyColumn"

    micro_strategy_column_id: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the column in MicroStrategy."""

    micro_strategy_column_type: Union[str, None, UnsetType] = UNSET
    """Type of the column (Eg attribute_column, fact_column, metric_column etc)."""

    micro_strategy_data_type: Union[str, None, UnsetType] = UNSET
    """Data type of the column."""

    micro_strategy_column_attribute_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Attribute in which this column exists."""

    micro_strategy_column_fact_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Fact in which this column exists."""

    micro_strategy_column_metric_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Metric in which this column exists."""

    micro_strategy_column_cube_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Cube in which this column exists."""

    micro_strategy_column_report_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Report in which this column exists."""

    micro_strategy_column_dossier_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Dossier in which this column exists."""

    micro_strategy_column_document_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Document in which this column exists."""

    micro_strategy_parent_name: Union[str, None, UnsetType] = UNSET
    """Name of the parent asset."""

    micro_strategy_column_expression: Union[str, None, UnsetType] = UNSET
    """Expression or formula used to define this column."""

    micro_strategy_project_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the project in which this asset exists."""

    micro_strategy_project_name: Union[str, None, UnsetType] = UNSET
    """Simple name of the project in which this asset exists."""

    micro_strategy_cube_qualified_names: Union[list[str], None, UnsetType] = UNSET
    """Unique names of the cubes related to this asset."""

    micro_strategy_cube_names: Union[list[str], None, UnsetType] = UNSET
    """Simple names of the cubes related to this asset."""

    micro_strategy_report_qualified_names: Union[list[str], None, UnsetType] = UNSET
    """Unique names of the reports related to this asset."""

    micro_strategy_report_names: Union[list[str], None, UnsetType] = UNSET
    """Simple names of the reports related to this asset."""

    micro_strategy_is_certified: Union[bool, None, UnsetType] = UNSET
    """Whether the asset is certified in MicroStrategy (true) or not (false)."""

    micro_strategy_certified_by: Union[str, None, UnsetType] = UNSET
    """User who certified this asset, in MicroStrategy."""

    micro_strategy_certified_at: Union[int, None, UnsetType] = UNSET
    """Time (epoch) this asset was certified in MicroStrategy, in milliseconds."""

    micro_strategy_location: Union[list[dict[str, str]], None, UnsetType] = UNSET
    """Location of this asset in MicroStrategy."""

    micro_strategy_attribute: Union[RelatedMicroStrategyAttribute, None, UnsetType] = (
        UNSET
    )
    """Attribute containing the column."""

    micro_strategy_cube: Union[RelatedMicroStrategyCube, None, UnsetType] = UNSET
    """Cube containing the column."""

    micro_strategy_document: Union[RelatedMicroStrategyDocument, None, UnsetType] = (
        UNSET
    )
    """Document containing the column."""

    micro_strategy_dossier: Union[RelatedMicroStrategyDossier, None, UnsetType] = UNSET
    """Dossier containing the column."""

    micro_strategy_fact: Union[RelatedMicroStrategyFact, None, UnsetType] = UNSET
    """Fact containing the column."""

    micro_strategy_metric: Union[RelatedMicroStrategyMetric, None, UnsetType] = UNSET
    """Metric containing the column."""

    micro_strategy_report: Union[RelatedMicroStrategyReport, None, UnsetType] = UNSET
    """Report containing the column."""

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return _micro_strategy_column_to_nested_bytes(self, serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    @staticmethod
    def from_json(
        json_data: Union[str, bytes], serde: Serde | None = None
    ) -> "MicroStrategyColumn":
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            MicroStrategyColumn instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _micro_strategy_column_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class MicroStrategyColumnAttributes(AssetAttributes):
    """MicroStrategyColumn-specific attributes for nested API format."""

    micro_strategy_column_id: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the column in MicroStrategy."""

    micro_strategy_column_type: Union[str, None, UnsetType] = UNSET
    """Type of the column (Eg attribute_column, fact_column, metric_column etc)."""

    micro_strategy_data_type: Union[str, None, UnsetType] = UNSET
    """Data type of the column."""

    micro_strategy_column_attribute_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Attribute in which this column exists."""

    micro_strategy_column_fact_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Fact in which this column exists."""

    micro_strategy_column_metric_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Metric in which this column exists."""

    micro_strategy_column_cube_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Cube in which this column exists."""

    micro_strategy_column_report_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Report in which this column exists."""

    micro_strategy_column_dossier_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Dossier in which this column exists."""

    micro_strategy_column_document_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique identifier of the Document in which this column exists."""

    micro_strategy_parent_name: Union[str, None, UnsetType] = UNSET
    """Name of the parent asset."""

    micro_strategy_column_expression: Union[str, None, UnsetType] = UNSET
    """Expression or formula used to define this column."""

    micro_strategy_project_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the project in which this asset exists."""

    micro_strategy_project_name: Union[str, None, UnsetType] = UNSET
    """Simple name of the project in which this asset exists."""

    micro_strategy_cube_qualified_names: Union[list[str], None, UnsetType] = UNSET
    """Unique names of the cubes related to this asset."""

    micro_strategy_cube_names: Union[list[str], None, UnsetType] = UNSET
    """Simple names of the cubes related to this asset."""

    micro_strategy_report_qualified_names: Union[list[str], None, UnsetType] = UNSET
    """Unique names of the reports related to this asset."""

    micro_strategy_report_names: Union[list[str], None, UnsetType] = UNSET
    """Simple names of the reports related to this asset."""

    micro_strategy_is_certified: Union[bool, None, UnsetType] = UNSET
    """Whether the asset is certified in MicroStrategy (true) or not (false)."""

    micro_strategy_certified_by: Union[str, None, UnsetType] = UNSET
    """User who certified this asset, in MicroStrategy."""

    micro_strategy_certified_at: Union[int, None, UnsetType] = UNSET
    """Time (epoch) this asset was certified in MicroStrategy, in milliseconds."""

    micro_strategy_location: Union[list[dict[str, str]], None, UnsetType] = UNSET
    """Location of this asset in MicroStrategy."""


class MicroStrategyColumnRelationshipAttributes(AssetRelationshipAttributes):
    """MicroStrategyColumn-specific relationship attributes for nested API format."""

    micro_strategy_attribute: Union[RelatedMicroStrategyAttribute, None, UnsetType] = (
        UNSET
    )
    """Attribute containing the column."""

    micro_strategy_cube: Union[RelatedMicroStrategyCube, None, UnsetType] = UNSET
    """Cube containing the column."""

    micro_strategy_document: Union[RelatedMicroStrategyDocument, None, UnsetType] = (
        UNSET
    )
    """Document containing the column."""

    micro_strategy_dossier: Union[RelatedMicroStrategyDossier, None, UnsetType] = UNSET
    """Dossier containing the column."""

    micro_strategy_fact: Union[RelatedMicroStrategyFact, None, UnsetType] = UNSET
    """Fact containing the column."""

    micro_strategy_metric: Union[RelatedMicroStrategyMetric, None, UnsetType] = UNSET
    """Metric containing the column."""

    micro_strategy_report: Union[RelatedMicroStrategyReport, None, UnsetType] = UNSET
    """Report containing the column."""


class MicroStrategyColumnNested(AssetNested):
    """MicroStrategyColumn in nested API format for high-performance serialization."""

    attributes: Union[MicroStrategyColumnAttributes, UnsetType] = UNSET
    relationship_attributes: Union[
        MicroStrategyColumnRelationshipAttributes, UnsetType
    ] = UNSET
    append_relationship_attributes: Union[
        MicroStrategyColumnRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        MicroStrategyColumnRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _micro_strategy_column_to_nested(
    micro_strategy_column: MicroStrategyColumn,
) -> MicroStrategyColumnNested:
    """Convert flat MicroStrategyColumn to nested format."""
    attrs = MicroStrategyColumnAttributes(
        micro_strategy_column_id=micro_strategy_column.micro_strategy_column_id,
        micro_strategy_column_type=micro_strategy_column.micro_strategy_column_type,
        micro_strategy_data_type=micro_strategy_column.micro_strategy_data_type,
        micro_strategy_column_attribute_qualified_name=micro_strategy_column.micro_strategy_column_attribute_qualified_name,
        micro_strategy_column_fact_qualified_name=micro_strategy_column.micro_strategy_column_fact_qualified_name,
        micro_strategy_column_metric_qualified_name=micro_strategy_column.micro_strategy_column_metric_qualified_name,
        micro_strategy_column_cube_qualified_name=micro_strategy_column.micro_strategy_column_cube_qualified_name,
        micro_strategy_column_report_qualified_name=micro_strategy_column.micro_strategy_column_report_qualified_name,
        micro_strategy_column_dossier_qualified_name=micro_strategy_column.micro_strategy_column_dossier_qualified_name,
        micro_strategy_column_document_qualified_name=micro_strategy_column.micro_strategy_column_document_qualified_name,
        micro_strategy_parent_name=micro_strategy_column.micro_strategy_parent_name,
        micro_strategy_column_expression=micro_strategy_column.micro_strategy_column_expression,
        micro_strategy_project_qualified_name=micro_strategy_column.micro_strategy_project_qualified_name,
        micro_strategy_project_name=micro_strategy_column.micro_strategy_project_name,
        micro_strategy_cube_qualified_names=micro_strategy_column.micro_strategy_cube_qualified_names,
        micro_strategy_cube_names=micro_strategy_column.micro_strategy_cube_names,
        micro_strategy_report_qualified_names=micro_strategy_column.micro_strategy_report_qualified_names,
        micro_strategy_report_names=micro_strategy_column.micro_strategy_report_names,
        micro_strategy_is_certified=micro_strategy_column.micro_strategy_is_certified,
        micro_strategy_certified_by=micro_strategy_column.micro_strategy_certified_by,
        micro_strategy_certified_at=micro_strategy_column.micro_strategy_certified_at,
        micro_strategy_location=micro_strategy_column.micro_strategy_location,
    )
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    rel_fields: list[str] = [
        "micro_strategy_attribute",
        "micro_strategy_cube",
        "micro_strategy_document",
        "micro_strategy_dossier",
        "micro_strategy_fact",
        "micro_strategy_metric",
        "micro_strategy_report",
    ]
    replace_rels, append_rels, remove_rels = categorize_relationships(
        micro_strategy_column, rel_fields, MicroStrategyColumnRelationshipAttributes
    )
    return MicroStrategyColumnNested(
        guid=micro_strategy_column.guid,
        type_name=micro_strategy_column.type_name,
        status=micro_strategy_column.status,
        version=micro_strategy_column.version,
        create_time=micro_strategy_column.create_time,
        update_time=micro_strategy_column.update_time,
        created_by=micro_strategy_column.created_by,
        updated_by=micro_strategy_column.updated_by,
        classifications=micro_strategy_column.classifications,
        classification_names=micro_strategy_column.classification_names,
        meanings=micro_strategy_column.meanings,
        labels=micro_strategy_column.labels,
        business_attributes=micro_strategy_column.business_attributes,
        custom_attributes=micro_strategy_column.custom_attributes,
        pending_tasks=micro_strategy_column.pending_tasks,
        proxy=micro_strategy_column.proxy,
        is_incomplete=micro_strategy_column.is_incomplete,
        provenance_type=micro_strategy_column.provenance_type,
        home_id=micro_strategy_column.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _micro_strategy_column_from_nested(
    nested: MicroStrategyColumnNested,
) -> MicroStrategyColumn:
    """Convert nested format to flat MicroStrategyColumn."""
    attrs = (
        nested.attributes
        if nested.attributes is not UNSET
        else MicroStrategyColumnAttributes()
    )
    # Merge relationships from all three buckets
    rel_fields: list[str] = [
        "micro_strategy_attribute",
        "micro_strategy_cube",
        "micro_strategy_document",
        "micro_strategy_dossier",
        "micro_strategy_fact",
        "micro_strategy_metric",
        "micro_strategy_report",
    ]
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        rel_fields,
        MicroStrategyColumnRelationshipAttributes,
    )
    return MicroStrategyColumn(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        micro_strategy_column_id=attrs.micro_strategy_column_id,
        micro_strategy_column_type=attrs.micro_strategy_column_type,
        micro_strategy_data_type=attrs.micro_strategy_data_type,
        micro_strategy_column_attribute_qualified_name=attrs.micro_strategy_column_attribute_qualified_name,
        micro_strategy_column_fact_qualified_name=attrs.micro_strategy_column_fact_qualified_name,
        micro_strategy_column_metric_qualified_name=attrs.micro_strategy_column_metric_qualified_name,
        micro_strategy_column_cube_qualified_name=attrs.micro_strategy_column_cube_qualified_name,
        micro_strategy_column_report_qualified_name=attrs.micro_strategy_column_report_qualified_name,
        micro_strategy_column_dossier_qualified_name=attrs.micro_strategy_column_dossier_qualified_name,
        micro_strategy_column_document_qualified_name=attrs.micro_strategy_column_document_qualified_name,
        micro_strategy_parent_name=attrs.micro_strategy_parent_name,
        micro_strategy_column_expression=attrs.micro_strategy_column_expression,
        micro_strategy_project_qualified_name=attrs.micro_strategy_project_qualified_name,
        micro_strategy_project_name=attrs.micro_strategy_project_name,
        micro_strategy_cube_qualified_names=attrs.micro_strategy_cube_qualified_names,
        micro_strategy_cube_names=attrs.micro_strategy_cube_names,
        micro_strategy_report_qualified_names=attrs.micro_strategy_report_qualified_names,
        micro_strategy_report_names=attrs.micro_strategy_report_names,
        micro_strategy_is_certified=attrs.micro_strategy_is_certified,
        micro_strategy_certified_by=attrs.micro_strategy_certified_by,
        micro_strategy_certified_at=attrs.micro_strategy_certified_at,
        micro_strategy_location=attrs.micro_strategy_location,
        # Merged relationship attributes
        **merged_rels,
    )


def _micro_strategy_column_to_nested_bytes(
    micro_strategy_column: MicroStrategyColumn, serde: Serde
) -> bytes:
    """Convert flat MicroStrategyColumn to nested JSON bytes."""
    return serde.encode(_micro_strategy_column_to_nested(micro_strategy_column))


def _micro_strategy_column_from_nested_bytes(
    data: bytes, serde: Serde
) -> MicroStrategyColumn:
    """Convert nested JSON bytes to flat MicroStrategyColumn."""
    nested = serde.decode(data, MicroStrategyColumnNested)
    return _micro_strategy_column_from_nested(nested)
