# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
SAP asset model with flattened inheritance.

This module provides:
- SAP: Flat asset class (easy to use)
- SAPAttributes: Nested attributes struct (extends AssetAttributes)
- SAPNested: Nested API format struct
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.conversion_utils import categorize_relationships, merge_relationships
from pyatlan_v9.serde import Serde, get_serde
from pyatlan_v9.transform import register_asset

from .asset import Asset, AssetAttributes, AssetNested, AssetRelationshipAttributes

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class SAP(Asset):
    """
    Base class for SAP assets.
    """

    # Override type_name with SAP-specific default
    type_name: Union[str, UnsetType] = "SAP"

    sap_technical_name: Union[str, None, UnsetType] = UNSET
    """Technical identifier for SAP data objects, used for integration and internal reference."""

    sap_logical_name: Union[str, None, UnsetType] = UNSET
    """Logical, business-friendly identifier for SAP data objects, aligned with business terminology and concepts."""

    sap_package_name: Union[str, None, UnsetType] = UNSET
    """Name of the SAP package, representing a logical grouping of related SAP data objects."""

    sap_component_name: Union[str, None, UnsetType] = UNSET
    """Name of the SAP component, representing a specific functional area in SAP."""

    sap_data_type: Union[str, None, UnsetType] = UNSET
    """SAP-specific data types"""

    sap_field_count: Union[int, None, UnsetType] = UNSET
    """Represents the total number of fields, columns, or child assets present in a given SAP asset."""

    sap_field_order: Union[int, None, UnsetType] = UNSET
    """Indicates the sequential position of a field, column, or child asset within its parent SAP asset, starting from 1."""

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return _sap_to_nested_bytes(self, serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    @staticmethod
    def from_json(json_data: Union[str, bytes], serde: Serde | None = None) -> "SAP":
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            SAP instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _sap_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class SAPAttributes(AssetAttributes):
    """SAP-specific attributes for nested API format."""

    sap_technical_name: Union[str, None, UnsetType] = UNSET
    """Technical identifier for SAP data objects, used for integration and internal reference."""

    sap_logical_name: Union[str, None, UnsetType] = UNSET
    """Logical, business-friendly identifier for SAP data objects, aligned with business terminology and concepts."""

    sap_package_name: Union[str, None, UnsetType] = UNSET
    """Name of the SAP package, representing a logical grouping of related SAP data objects."""

    sap_component_name: Union[str, None, UnsetType] = UNSET
    """Name of the SAP component, representing a specific functional area in SAP."""

    sap_data_type: Union[str, None, UnsetType] = UNSET
    """SAP-specific data types"""

    sap_field_count: Union[int, None, UnsetType] = UNSET
    """Represents the total number of fields, columns, or child assets present in a given SAP asset."""

    sap_field_order: Union[int, None, UnsetType] = UNSET
    """Indicates the sequential position of a field, column, or child asset within its parent SAP asset, starting from 1."""


class SAPRelationshipAttributes(AssetRelationshipAttributes):
    """SAP-specific relationship attributes for nested API format."""

    pass


class SAPNested(AssetNested):
    """SAP in nested API format for high-performance serialization."""

    attributes: Union[SAPAttributes, UnsetType] = UNSET
    relationship_attributes: Union[SAPRelationshipAttributes, UnsetType] = UNSET
    append_relationship_attributes: Union[SAPRelationshipAttributes, UnsetType] = UNSET
    remove_relationship_attributes: Union[SAPRelationshipAttributes, UnsetType] = UNSET


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _sap_to_nested(sap: SAP) -> SAPNested:
    """Convert flat SAP to nested format."""
    attrs = SAPAttributes(
        sap_technical_name=sap.sap_technical_name,
        sap_logical_name=sap.sap_logical_name,
        sap_package_name=sap.sap_package_name,
        sap_component_name=sap.sap_component_name,
        sap_data_type=sap.sap_data_type,
        sap_field_count=sap.sap_field_count,
        sap_field_order=sap.sap_field_order,
    )
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    rel_fields: list[str] = []
    replace_rels, append_rels, remove_rels = categorize_relationships(
        sap, rel_fields, SAPRelationshipAttributes
    )
    return SAPNested(
        guid=sap.guid,
        type_name=sap.type_name,
        status=sap.status,
        version=sap.version,
        create_time=sap.create_time,
        update_time=sap.update_time,
        created_by=sap.created_by,
        updated_by=sap.updated_by,
        classifications=sap.classifications,
        classification_names=sap.classification_names,
        meanings=sap.meanings,
        labels=sap.labels,
        business_attributes=sap.business_attributes,
        custom_attributes=sap.custom_attributes,
        pending_tasks=sap.pending_tasks,
        proxy=sap.proxy,
        is_incomplete=sap.is_incomplete,
        provenance_type=sap.provenance_type,
        home_id=sap.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _sap_from_nested(nested: SAPNested) -> SAP:
    """Convert nested format to flat SAP."""
    attrs = nested.attributes if nested.attributes is not UNSET else SAPAttributes()
    # Merge relationships from all three buckets
    rel_fields: list[str] = []
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        rel_fields,
        SAPRelationshipAttributes,
    )
    return SAP(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        sap_technical_name=attrs.sap_technical_name,
        sap_logical_name=attrs.sap_logical_name,
        sap_package_name=attrs.sap_package_name,
        sap_component_name=attrs.sap_component_name,
        sap_data_type=attrs.sap_data_type,
        sap_field_count=attrs.sap_field_count,
        sap_field_order=attrs.sap_field_order,
        # Merged relationship attributes
        **merged_rels,
    )


def _sap_to_nested_bytes(sap: SAP, serde: Serde) -> bytes:
    """Convert flat SAP to nested JSON bytes."""
    return serde.encode(_sap_to_nested(sap))


def _sap_from_nested_bytes(data: bytes, serde: Serde) -> SAP:
    """Convert nested JSON bytes to flat SAP."""
    nested = serde.decode(data, SAPNested)
    return _sap_from_nested(nested)
