# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
SemanticModel asset model with flattened inheritance.

This module provides:
- SemanticModel: Flat asset class (easy to use)
- SemanticModelAttributes: Nested attributes struct (extends AssetAttributes)
- SemanticModelNested: Nested API format struct
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.conversion_utils import categorize_relationships, merge_relationships
from pyatlan_v9.serde import Serde, get_serde
from pyatlan_v9.transform import register_asset

from .asset import Asset, AssetAttributes, AssetNested, AssetRelationshipAttributes
from .semantic_related import (
    RelatedSemanticDimension,
    RelatedSemanticEntity,
    RelatedSemanticMeasure,
)

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class SemanticModel(Asset):
    """
    Base class for semantic models across different sources.
    """

    # Override type_name with SemanticModel-specific default
    type_name: Union[str, UnsetType] = "SemanticModel"

    semantic_dimensions: Union[list[RelatedSemanticDimension], None, UnsetType] = UNSET
    """Dimensions that exist within this semantic model."""

    semantic_measures: Union[list[RelatedSemanticMeasure], None, UnsetType] = UNSET
    """Measures that exist within this semantic model."""

    semantic_entities: Union[list[RelatedSemanticEntity], None, UnsetType] = UNSET
    """Entities that exist within this semantic model."""

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return _semantic_model_to_nested_bytes(self, serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    @staticmethod
    def from_json(
        json_data: Union[str, bytes], serde: Serde | None = None
    ) -> "SemanticModel":
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            SemanticModel instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _semantic_model_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class SemanticModelAttributes(AssetAttributes):
    """SemanticModel-specific attributes for nested API format."""

    pass


class SemanticModelRelationshipAttributes(AssetRelationshipAttributes):
    """SemanticModel-specific relationship attributes for nested API format."""

    semantic_dimensions: Union[list[RelatedSemanticDimension], None, UnsetType] = UNSET
    """Dimensions that exist within this semantic model."""

    semantic_measures: Union[list[RelatedSemanticMeasure], None, UnsetType] = UNSET
    """Measures that exist within this semantic model."""

    semantic_entities: Union[list[RelatedSemanticEntity], None, UnsetType] = UNSET
    """Entities that exist within this semantic model."""


class SemanticModelNested(AssetNested):
    """SemanticModel in nested API format for high-performance serialization."""

    attributes: Union[SemanticModelAttributes, UnsetType] = UNSET
    relationship_attributes: Union[SemanticModelRelationshipAttributes, UnsetType] = (
        UNSET
    )
    append_relationship_attributes: Union[
        SemanticModelRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        SemanticModelRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _semantic_model_to_nested(semantic_model: SemanticModel) -> SemanticModelNested:
    """Convert flat SemanticModel to nested format."""
    attrs = SemanticModelAttributes()
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    rel_fields: list[str] = [
        "semantic_dimensions",
        "semantic_measures",
        "semantic_entities",
    ]
    replace_rels, append_rels, remove_rels = categorize_relationships(
        semantic_model, rel_fields, SemanticModelRelationshipAttributes
    )
    return SemanticModelNested(
        guid=semantic_model.guid,
        type_name=semantic_model.type_name,
        status=semantic_model.status,
        version=semantic_model.version,
        create_time=semantic_model.create_time,
        update_time=semantic_model.update_time,
        created_by=semantic_model.created_by,
        updated_by=semantic_model.updated_by,
        classifications=semantic_model.classifications,
        classification_names=semantic_model.classification_names,
        meanings=semantic_model.meanings,
        labels=semantic_model.labels,
        business_attributes=semantic_model.business_attributes,
        custom_attributes=semantic_model.custom_attributes,
        pending_tasks=semantic_model.pending_tasks,
        proxy=semantic_model.proxy,
        is_incomplete=semantic_model.is_incomplete,
        provenance_type=semantic_model.provenance_type,
        home_id=semantic_model.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _semantic_model_from_nested(nested: SemanticModelNested) -> SemanticModel:
    """Convert nested format to flat SemanticModel."""
    attrs = (
        nested.attributes
        if nested.attributes is not UNSET
        else SemanticModelAttributes()
    )
    # Merge relationships from all three buckets
    rel_fields: list[str] = [
        "semantic_dimensions",
        "semantic_measures",
        "semantic_entities",
    ]
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        rel_fields,
        SemanticModelRelationshipAttributes,
    )
    return SemanticModel(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        # Merged relationship attributes
        **merged_rels,
    )


def _semantic_model_to_nested_bytes(
    semantic_model: SemanticModel, serde: Serde
) -> bytes:
    """Convert flat SemanticModel to nested JSON bytes."""
    return serde.encode(_semantic_model_to_nested(semantic_model))


def _semantic_model_from_nested_bytes(data: bytes, serde: Serde) -> SemanticModel:
    """Convert nested JSON bytes to flat SemanticModel."""
    nested = serde.decode(data, SemanticModelNested)
    return _semantic_model_from_nested(nested)
