# Auto-generated by PythonMsgspecRenderer.pkl - DO NOT EDIT
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Atlan Pte. Ltd.

"""
TableauDashboard asset model with flattened inheritance.

This module provides:
- TableauDashboard: Flat asset class (easy to use)
- TableauDashboardAttributes: Nested attributes struct (extends AssetAttributes)
- TableauDashboardNested: Nested API format struct
"""

from __future__ import annotations

from typing import Union

from msgspec import UNSET, UnsetType

from pyatlan_v9.conversion_utils import categorize_relationships, merge_relationships
from pyatlan_v9.serde import Serde, get_serde
from pyatlan_v9.transform import register_asset

from .asset import Asset, AssetAttributes, AssetNested, AssetRelationshipAttributes
from .tableau_related import (
    RelatedTableauDashboard,
    RelatedTableauDashboardField,
    RelatedTableauWorkbook,
    RelatedTableauWorksheet,
)

# =============================================================================
# FLAT ASSET CLASS
# =============================================================================


@register_asset
class TableauDashboard(Asset):
    """
    Instance of a Tableau dashboard in Atlan. These are collections of several views, letting you compare a variety of data simultaneously.
    """

    # Override type_name with TableauDashboard-specific default
    type_name: Union[str, UnsetType] = "TableauDashboard"

    site_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the site in which this dashboard exists."""

    project_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the project in which this dashboard exists."""

    workbook_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the workbook in which this dashboard exists."""

    top_level_project_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the top-level project in which this dashboard exists."""

    project_hierarchy: Union[list[dict[str, str]], None, UnsetType] = UNSET
    """List of top-level projects and their nested child projects."""

    tableau_project_hierarchy_qualified_names: Union[list[str], None, UnsetType] = UNSET
    """Array of qualified names representing the project hierarchy for this Tableau asset."""

    workbook: Union[RelatedTableauWorkbook, None, UnsetType] = UNSET
    """Workbook in which this dashboard exists."""

    worksheets: Union[list[RelatedTableauWorksheet], None, UnsetType] = UNSET
    """Worksheets that use this dashboard."""

    tableau_embedded_dashboards: Union[
        list[RelatedTableauDashboard], None, UnsetType
    ] = UNSET
    """Dashboards that are embedded in this dashboard."""

    tableau_parent_dashboards: Union[list[RelatedTableauDashboard], None, UnsetType] = (
        UNSET
    )
    """Dashboards in which this dashboard is embedded in (list of parent dashboards of this dashboard)."""

    tableau_dashboard_fields: Union[
        list[RelatedTableauDashboardField], None, UnsetType
    ] = UNSET
    """Fields that exist within this dashboard."""

    # =========================================================================
    # Optimized Serialization Methods (override Asset base class)
    # =========================================================================

    def to_json(self, nested: bool = True, serde: Serde | None = None) -> str:
        """
        Convert to JSON string using optimized nested struct serialization.

        Args:
            nested: If True (default), use nested API format. If False, use flat format.
            serde: Optional Serde instance for encoder reuse. Uses shared singleton if None.

        Returns:
            JSON string representation
        """
        if serde is None:
            serde = get_serde()
        if nested:
            return _tableau_dashboard_to_nested_bytes(self, serde).decode("utf-8")
        else:
            return serde.encode(self).decode("utf-8")

    @staticmethod
    def from_json(
        json_data: Union[str, bytes], serde: Serde | None = None
    ) -> "TableauDashboard":
        """
        Create from JSON string or bytes using optimized nested struct deserialization.

        Args:
            json_data: JSON string or bytes to deserialize
            serde: Optional Serde instance for decoder reuse. Uses shared singleton if None.

        Returns:
            TableauDashboard instance
        """
        if isinstance(json_data, str):
            json_data = json_data.encode("utf-8")
        if serde is None:
            serde = get_serde()
        return _tableau_dashboard_from_nested_bytes(json_data, serde)


# =============================================================================
# NESTED FORMAT CLASSES
# =============================================================================


class TableauDashboardAttributes(AssetAttributes):
    """TableauDashboard-specific attributes for nested API format."""

    site_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the site in which this dashboard exists."""

    project_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the project in which this dashboard exists."""

    workbook_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the workbook in which this dashboard exists."""

    top_level_project_qualified_name: Union[str, None, UnsetType] = UNSET
    """Unique name of the top-level project in which this dashboard exists."""

    project_hierarchy: Union[list[dict[str, str]], None, UnsetType] = UNSET
    """List of top-level projects and their nested child projects."""

    tableau_project_hierarchy_qualified_names: Union[list[str], None, UnsetType] = UNSET
    """Array of qualified names representing the project hierarchy for this Tableau asset."""


class TableauDashboardRelationshipAttributes(AssetRelationshipAttributes):
    """TableauDashboard-specific relationship attributes for nested API format."""

    workbook: Union[RelatedTableauWorkbook, None, UnsetType] = UNSET
    """Workbook in which this dashboard exists."""

    worksheets: Union[list[RelatedTableauWorksheet], None, UnsetType] = UNSET
    """Worksheets that use this dashboard."""

    tableau_embedded_dashboards: Union[
        list[RelatedTableauDashboard], None, UnsetType
    ] = UNSET
    """Dashboards that are embedded in this dashboard."""

    tableau_parent_dashboards: Union[list[RelatedTableauDashboard], None, UnsetType] = (
        UNSET
    )
    """Dashboards in which this dashboard is embedded in (list of parent dashboards of this dashboard)."""

    tableau_dashboard_fields: Union[
        list[RelatedTableauDashboardField], None, UnsetType
    ] = UNSET
    """Fields that exist within this dashboard."""


class TableauDashboardNested(AssetNested):
    """TableauDashboard in nested API format for high-performance serialization."""

    attributes: Union[TableauDashboardAttributes, UnsetType] = UNSET
    relationship_attributes: Union[
        TableauDashboardRelationshipAttributes, UnsetType
    ] = UNSET
    append_relationship_attributes: Union[
        TableauDashboardRelationshipAttributes, UnsetType
    ] = UNSET
    remove_relationship_attributes: Union[
        TableauDashboardRelationshipAttributes, UnsetType
    ] = UNSET


# =============================================================================
# CONVERSION FUNCTIONS
# =============================================================================


def _tableau_dashboard_to_nested(
    tableau_dashboard: TableauDashboard,
) -> TableauDashboardNested:
    """Convert flat TableauDashboard to nested format."""
    attrs = TableauDashboardAttributes(
        site_qualified_name=tableau_dashboard.site_qualified_name,
        project_qualified_name=tableau_dashboard.project_qualified_name,
        workbook_qualified_name=tableau_dashboard.workbook_qualified_name,
        top_level_project_qualified_name=tableau_dashboard.top_level_project_qualified_name,
        project_hierarchy=tableau_dashboard.project_hierarchy,
        tableau_project_hierarchy_qualified_names=tableau_dashboard.tableau_project_hierarchy_qualified_names,
    )
    # Categorize relationships by save semantic (REPLACE, APPEND, REMOVE)
    rel_fields: list[str] = [
        "workbook",
        "worksheets",
        "tableau_embedded_dashboards",
        "tableau_parent_dashboards",
        "tableau_dashboard_fields",
    ]
    replace_rels, append_rels, remove_rels = categorize_relationships(
        tableau_dashboard, rel_fields, TableauDashboardRelationshipAttributes
    )
    return TableauDashboardNested(
        guid=tableau_dashboard.guid,
        type_name=tableau_dashboard.type_name,
        status=tableau_dashboard.status,
        version=tableau_dashboard.version,
        create_time=tableau_dashboard.create_time,
        update_time=tableau_dashboard.update_time,
        created_by=tableau_dashboard.created_by,
        updated_by=tableau_dashboard.updated_by,
        classifications=tableau_dashboard.classifications,
        classification_names=tableau_dashboard.classification_names,
        meanings=tableau_dashboard.meanings,
        labels=tableau_dashboard.labels,
        business_attributes=tableau_dashboard.business_attributes,
        custom_attributes=tableau_dashboard.custom_attributes,
        pending_tasks=tableau_dashboard.pending_tasks,
        proxy=tableau_dashboard.proxy,
        is_incomplete=tableau_dashboard.is_incomplete,
        provenance_type=tableau_dashboard.provenance_type,
        home_id=tableau_dashboard.home_id,
        attributes=attrs,
        relationship_attributes=replace_rels,
        append_relationship_attributes=append_rels,
        remove_relationship_attributes=remove_rels,
    )


def _tableau_dashboard_from_nested(nested: TableauDashboardNested) -> TableauDashboard:
    """Convert nested format to flat TableauDashboard."""
    attrs = (
        nested.attributes
        if nested.attributes is not UNSET
        else TableauDashboardAttributes()
    )
    # Merge relationships from all three buckets
    rel_fields: list[str] = [
        "workbook",
        "worksheets",
        "tableau_embedded_dashboards",
        "tableau_parent_dashboards",
        "tableau_dashboard_fields",
    ]
    merged_rels = merge_relationships(
        nested.relationship_attributes,
        nested.append_relationship_attributes,
        nested.remove_relationship_attributes,
        rel_fields,
        TableauDashboardRelationshipAttributes,
    )
    return TableauDashboard(
        guid=nested.guid,
        type_name=nested.type_name,
        status=nested.status,
        version=nested.version,
        create_time=nested.create_time,
        update_time=nested.update_time,
        created_by=nested.created_by,
        updated_by=nested.updated_by,
        classifications=nested.classifications,
        classification_names=nested.classification_names,
        meanings=nested.meanings,
        labels=nested.labels,
        business_attributes=nested.business_attributes,
        custom_attributes=nested.custom_attributes,
        pending_tasks=nested.pending_tasks,
        proxy=nested.proxy,
        is_incomplete=nested.is_incomplete,
        provenance_type=nested.provenance_type,
        home_id=nested.home_id,
        site_qualified_name=attrs.site_qualified_name,
        project_qualified_name=attrs.project_qualified_name,
        workbook_qualified_name=attrs.workbook_qualified_name,
        top_level_project_qualified_name=attrs.top_level_project_qualified_name,
        project_hierarchy=attrs.project_hierarchy,
        tableau_project_hierarchy_qualified_names=attrs.tableau_project_hierarchy_qualified_names,
        # Merged relationship attributes
        **merged_rels,
    )


def _tableau_dashboard_to_nested_bytes(
    tableau_dashboard: TableauDashboard, serde: Serde
) -> bytes:
    """Convert flat TableauDashboard to nested JSON bytes."""
    return serde.encode(_tableau_dashboard_to_nested(tableau_dashboard))


def _tableau_dashboard_from_nested_bytes(data: bytes, serde: Serde) -> TableauDashboard:
    """Convert nested JSON bytes to flat TableauDashboard."""
    nested = serde.decode(data, TableauDashboardNested)
    return _tableau_dashboard_from_nested(nested)
