package:
  name: "pyatlan"
  version: "{{ environ['PYATLAN_VERSION'] }}"

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - jinja2 >=3.1.6,<3.2
    - lazy_loader >=0.4,<0.5
    - pip
    - pydantic >=2.11.7,<2.12
    - python
    - requests >=2.32.4,<2.33
    - tenacity >=9.1.2,<9.2
    - urllib3 >=1.26.0,<3
  run:
    - jinja2 >=3.1.6,<3.2
    - lazy_loader >=0.4,<0.5
    - pydantic >=2.11.7,<2.12
    - python
    - requests >=2.32.4,<2.33
    - tenacity >=9.1.2,<9.2
    - urllib3 >=1.26.0,<3


about:
  home: "https://github.com/atlanhq/atlan-python"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  license_url: https://github.com/atlanhq/atlan-python/blob/main/LICENSE
  summary: "Atlan Python Client"
  doc_url: https://developer.atlan.com/sdks/python
  dev_url:

extra:
  recipe-maintainers:
    - https://github.com/ErnestoLoma
    - https://github.com/cmgrote
    - https://github.com/Aryamanz29
    - https://github.com/0xquark
