name: "GlobalProtect VPN Connect"
description: "Connect to GlobalProtect VPN using OpenConnect"
author: "Atlan"

inputs:
  portal-url:
    description: "GlobalProtect portal URL"
    required: true
  username:
    description: "GlobalProtect username"
    required: true
  password:
    description: "GlobalProtect password"
    required: true
  max-attempts:
    description: "Maximum number of connection attempts"
    required: false
    default: "3"

outputs:
  vpn-connected:
    description: "Whether VPN connection was successful"
    value: ${{ steps.openconnect-connection.outputs.connected }}

runs:
  using: "composite"
  steps:
    - name: Connect via OpenConnect
      uses: nick-fields/retry@v3
      id: openconnect-connection
      with:
        max_attempts: ${{ fromJSON(inputs.max-attempts) }}
        timeout_minutes: 10
        shell: bash
        command: |
          echo "Connecting to GlobalProtect VPN using OpenConnect..."

          # Install OpenConnect
          echo "Installing OpenConnect..."
          sudo apt-get update
          sudo apt-get install -y openconnect

          # Check required inputs
          if [ -z "${{ inputs.portal-url }}" ]; then
            echo "portal-url input not provided"
            exit 1
          fi

          if [ -z "${{ inputs.username }}" ]; then
            echo "username input not provided"
            exit 1
          fi

          if [ -z "${{ inputs.password }}" ]; then
            echo "password input not provided"
            exit 1
          fi

          echo "Attempting OpenConnect to: ${{ inputs.portal-url }}"

          # Create credentials file for OpenConnect
          echo "${{ inputs.password }}" | sudo openconnect \
            --protocol=gp \
            --user="${{ inputs.username }}" \
            --passwd-on-stdin \
            --background \
            "${{ inputs.portal-url }}" || {
            echo "OpenConnect connection failed"
            exit 1
          }

          # Wait a moment for connection to establish
          sleep 10

          # Initial connectivity test
          echo "Testing initial connectivity to Phoenix AI..."
          time curl -k -sS https://phoenix-ai.atlan.com -o /dev/null

          if [ $? -eq 0 ]; then
            echo "Initial connectivity test successful"
          else
            echo "Initial connectivity test failed"
            exit 1
          fi

          # Set output to indicate successful connection
          echo "connected=true" >> $GITHUB_OUTPUT
          echo "VPN connection established successfully"
