
name: Build and upload conda packages

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: .conda-envs/build-env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      
      - name: Get version from version.txt
        id: get_version
        run: |
          PYATLAN_VERSION=$(cat pyatlan/version.txt | tr -d ' \n')
          echo "version=$PYATLAN_VERSION" >> $GITHUB_OUTPUT
          echo "PYATLAN_VERSION=$PYATLAN_VERSION" >> $GITHUB_ENV
          echo "Building version: $PYATLAN_VERSION"
      
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          meta_yaml_dir: .conda-envs
          python-version: ${{ matrix.python-version }}
          platform_all: true
          user: atlanhq
          label: main
          token: ${{ secrets.ANACONDA_API_TOKEN }}
          upload: true
          version: ${{ steps.get_version.outputs.version }}
