name: GitHub-Jira Link Action
run-name: ${{ github.actor }} is ensuring Jira ID is present in PR title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  Enforce-GitHub-Jira-Link-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce Pull Request Title includes Jira Issue Key
        uses: ryanvade/enforce-pr-title-style-action@v2.1.1
            
