# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Atlan Pte. Ltd.
name: Pyatlan MkDocs Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    name: "MkDocs"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --group docs

      - name: Build MkDocs
        run: uv run mkdocs build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
